Repository Autodesk/maya-usd, pull requests merged in 2020-12, with the labels that each got.

#953 MAYA-108293 add clang format lint action
  .clang-format-exclude
  .clang-format-ignore
  .github/workflows/maya-usd-clang-format-lint.yml
Labels: build

#949 Improved MAYA_PXR_PLUGINPATH_NAME to handle more checks
  lib/mayaUsd/CMakeLists.txt
  lib/mayaUsd/base/debugCodes.cpp
  lib/mayaUsd/base/debugCodes.h
  lib/mayaUsd/utils/CMakeLists.txt
  lib/mayaUsd/utils/plugRegistryHelper.cpp
  lib/mayaUsd/utils/plugRegistryHelper.h
  test/lib/CMakeLists.txt
  test/lib/testMayaUsdPlugVersionCheck.py
  test/lib/usd/plugin/CMakeLists.txt
  test/lib/usd/plugin/mayaUsdPlugInfo.json
  test/lib/usd/plugin/testPlugModule1.py
  test/lib/usd/plugin/testPlugModule1_plugInfo.json
  test/lib/usd/plugin/testPlugModule2.py
  test/lib/usd/plugin/testPlugModule2_plugInfo.json
  test/lib/usd/plugin/testPlugModule3.py
  test/lib/usd/plugin/testPlugModule3_plugInfo.json
  test/lib/usd/plugin/testPlugModule4.py
  test/lib/usd/plugin/testPlugModule4_plugInfo.json
  test/lib/usd/plugin/testPlugModule5.py
  test/lib/usd/plugin/testPlugModule5_plugInfo.json
  test/lib/usd/plugin/testPlugModule6.py
  test/lib/usd/plugin/testPlugModule6_plugInfo.json
Labels: core, ready-for-merge

#955 MAYA-108270 Improve draw performance for Rprims without extent
  lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
Labels: ready-for-merge, vp2renderdelegate

#948 Integrate Ufe::Transform3d::editTransform3d() hint support.
  lib/mayaUsd/ufe/UsdTransform3d.md
  lib/mayaUsd/ufe/UsdTransform3dCommonAPI.cpp
  lib/mayaUsd/ufe/UsdTransform3dCommonAPI.h
  lib/mayaUsd/ufe/UsdTransform3dFallbackMayaXformStack.cpp
  lib/mayaUsd/ufe/UsdTransform3dFallbackMayaXformStack.h
  lib/mayaUsd/ufe/UsdTransform3dMatrixOp.cpp
  lib/mayaUsd/ufe/UsdTransform3dMatrixOp.h
  lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
  lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.h
  plugin/adsk/plugin/plugin.cpp
Labels: ufe, ufe-usd, workflows

#950 Reuse shader effect for duplicate material networks.
  lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  lib/mayaUsd/render/vp2RenderDelegate/material.h
  lib/mayaUsd/render/vp2RenderDelegate/render_delegate.cpp
  lib/mayaUsd/render/vp2RenderDelegate/render_delegate.h
  lib/mayaUsd/render/vp2RenderDelegate/shader.cpp
  lib/mayaUsd/render/vp2RenderDelegate/shader.h
Labels: ready-for-merge, vp2renderdelegate

#963 MAYA-105734 Fix broken lighting fragment
  lib/mayaUsd/render/vp2ShaderFragments/usdPreviewSurfaceLighting.xml
Labels: ready-for-merge, vp2renderdelegate

#964 MAYA-108214 - Attributes categorized by schema
  lib/mayaUsd/resources/ae/CMakeLists.txt
  lib/mayaUsd/resources/ae/base/ae_template.py
  lib/mayaUsd/resources/ae/camera/ae_template.py
  lib/mayaUsd/resources/ae/capsule/ae_template.py
  lib/mayaUsd/resources/ae/cone/ae_template.py
  lib/mayaUsd/resources/ae/cube/ae_template.py
  lib/mayaUsd/resources/ae/cylinder/ae_template.py
  lib/mayaUsd/resources/ae/material/ae_template.py
  lib/mayaUsd/resources/ae/mesh/ae_template.py
  lib/mayaUsd/resources/ae/scope/ae_template.py
  lib/mayaUsd/resources/ae/shader/ae_template.py
  lib/mayaUsd/resources/ae/sphere/ae_template.py
  lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
  lib/mayaUsd/resources/ae/xform/ae_template.py
  test/lib/ufe/testDuplicateCmd.py
  test/lib/ufe/testGroupCmd.py
Labels: enhancement, ready-for-merge, requires maya

#967 Fix copy paste error and prevent serialization of computed attribute
  lib/mayaUsd/nodes/proxyShapeBase.cpp
Labels: proxy, ready-for-merge

#969 MAYA-108545: Prevent the crash when authoring edits to instance proxies.
  lib/mayaUsd/ufe/UsdTransform3dHandler.cpp
  lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
Labels: core, workflows

#968 [cmake] fix for windows if backslash in Python_EXECUTABLE
  plugin/al/usdtransaction/CMakeLists.txt
Labels: build, ready-for-merge

#954 Add support for UV transform value exports
  lib/usd/translators/shading/usdFileTextureWriter.cpp
  test/lib/usd/translators/CMakeLists.txt
  test/lib/usd/translators/UsdExportUVTransforms/Brazilian_rosewood_pxr128.png
  test/lib/usd/translators/UsdExportUVTransforms/UsdExportUVTransforms.ma
  test/lib/usd/translators/testUsdExportUVTransforms.py
Labels: import-export, ready-for-merge

#961 remove dependencies on old Hydra texture system from hdMaya for USD releases after 20.11
  lib/usd/hdMaya/adapters/aiSkydomeLightAdapter.cpp
  lib/usd/hdMaya/adapters/materialAdapter.cpp
  lib/usd/hdMaya/adapters/materialAdapter.h
  lib/usd/hdMaya/delegates/delegateDebugCodes.cpp
  lib/usd/hdMaya/delegates/delegateDebugCodes.h
  lib/usd/hdMaya/delegates/sceneDelegate.cpp
  lib/usd/hdMaya/delegates/sceneDelegate.h
  lib/usd/hdMaya/utils.cpp
  lib/usd/hdMaya/utils.h
Labels: mtoh, ready-for-merge

#962 Ufe manipulation
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/RotationUtils.cpp
  lib/mayaUsd/ufe/RotationUtils.h
  lib/mayaUsd/ufe/StagesSubject.cpp
  lib/mayaUsd/ufe/StagesSubject.h
  lib/mayaUsd/ufe/UsdRotateUndoableCommand.h
  lib/mayaUsd/ufe/UsdTransform3d.cpp
  lib/mayaUsd/ufe/UsdTransform3d.h
  lib/mayaUsd/ufe/UsdTransform3d.md
  lib/mayaUsd/ufe/UsdTransform3dBase.cpp
  lib/mayaUsd/ufe/UsdTransform3dBase.h
  lib/mayaUsd/ufe/UsdTransform3dCommonAPI.cpp
  lib/mayaUsd/ufe/UsdTransform3dCommonAPI.h
  lib/mayaUsd/ufe/UsdTransform3dFallbackMayaXformStack.cpp
  lib/mayaUsd/ufe/UsdTransform3dFallbackMayaXformStack.h
  lib/mayaUsd/ufe/UsdTransform3dHandler.cpp
  lib/mayaUsd/ufe/UsdTransform3dMatrixOp.cpp
  lib/mayaUsd/ufe/UsdTransform3dMatrixOp.h
  lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
  lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.h
  lib/mayaUsd/ufe/UsdTranslateUndoableCommand.h
  lib/mayaUsd/ufe/Utils.cpp
  lib/mayaUsd/ufe/Utils.h
  lib/mayaUsd/ufe/private/CMakeLists.txt
  lib/mayaUsd/ufe/private/UfeNotifGuard.cpp
  lib/mayaUsd/ufe/private/UfeNotifGuard.h
  lib/mayaUsd/ufe/wrapUtils.cpp
  lib/mayaUsd/undo/UsdUndoManager.cpp
  plugin/adsk/plugin/plugin.cpp
  test/lib/ufe/CMakeLists.txt
  test/lib/ufe/testComboCmd.py
  test/lib/ufe/testTransform3dChainOfResponsibility.py
  test/testSamples/xformOpFallback/fallbackTest.ma
  test/testSamples/xformOpFallback/fallbackTest.usda
Labels: ready-for-merge, ufe, ufe-usd, workflows

#978 MAYA-108261 Fixed regression caused by PR950
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
Labels: bug, regression, vp2renderdelegate

#980 Use RUNPATH instead of RPATH for linux plugins
  CMakeLists.txt
Labels: build, ready-for-merge

#984 Fixed incorrect Transform3d fallback assertion.
  lib/mayaUsd/ufe/UsdTransform3dFallbackMayaXformStack.cpp
  test/lib/ufe/testComboCmd.py
Labels: ready-for-merge

#986 MAYA-108545: update error message string.
  lib/mayaUsd/ufe/UsdTransform3dHandler.cpp
  lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
Labels: core, ready-for-merge, workflows

#985 MAYA-106079 Skip Looks scopes
  lib/usd/translators/scopeReader.cpp
  test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
Labels: import-export, ready-for-merge

#990 Fowlert/maya 108091/save layers dialog
  lib/usd/ui/layerEditor/CMakeLists.txt
  lib/usd/ui/layerEditor/layerEditorWidget.cpp
  lib/usd/ui/layerEditor/layerTreeModel.cpp
  lib/usd/ui/layerEditor/layerTreeModel.h
  lib/usd/ui/layerEditor/loadLayersDialog.cpp
  lib/usd/ui/layerEditor/mayaSessionState.cpp
  lib/usd/ui/layerEditor/saveLayersDialog.cpp
  lib/usd/ui/layerEditor/saveLayersDialog.h
  lib/usd/ui/layerEditor/stringResources.h
Labels: workflows

#979 Use color consolidation support for UsdPreviewSurface and UsdPrimvarReader_color
  lib/mayaUsd/render/vp2ShaderFragments/UsdPreviewSurface.xml
  lib/mayaUsd/render/vp2ShaderFragments/UsdPrimvarReader_color.xml
Labels: pending beta, ready-for-merge, vp2renderdelegate

#1000 Updated change log for 0.6.0
  doc/CHANGELOG.md
Labels: documentation

#915 Add basic tests for HdMaya / mtoh
  cmake/test.cmake
  lib/mayaUsd/render/mayaToHydra/viewCommand.cpp
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testBatchRendererIsolateSelection.py
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testPxrUsdMayaGLInstancerDraw.py
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testRefAssemblyDrawRepresentations.py
  test/lib/mayaUsd/render/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/MtohBasicRenderTest/cube_selected.png
  test/lib/mayaUsd/render/mayaToHydra/MtohBasicRenderTest/cube_unselected.png
  test/lib/mayaUsd/render/mayaToHydra/MtohBasicRenderTest/flat_orange.png
  test/lib/mayaUsd/render/mayaToHydra/MtohBasicRenderTest/flat_orange_bad.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_0.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_1.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_12.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_123.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_1234.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_123456.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_1235.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_3.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_35.png
  test/lib/mayaUsd/render/mayaToHydra/testMtohBasicRender.py
  test/lib/mayaUsd/render/mayaToHydra/testMtohCommand.py
  test/lib/mayaUsd/render/mayaToHydra/testMtohDagChanges.py
  test/lib/mayaUsd/render/mayaToHydra/testMtohVisibility.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawAndTransform.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawColorAccuracy.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawColors.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawLighting.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawPerformance.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawPurpose.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawTimeSampled.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawUsdChangeProcessing.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawVisibility.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDuplicatePerformance.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeLiveSurface.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeRendererSceneMessages.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeSelectionPerformance.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testPxrUsdMayaGL.py
  test/lib/usd/pxrUsdPreviewSurface/testPxrUsdPreviewSurfaceDraw.py
  test/testUtils/fixturesUtils.py
  test/testUtils/imageUtils.py
  test/testUtils/mtohUtils.py
  test/testUtils/testUtils.py
Labels: ready-for-merge, unit test

#991 Avoid return of pointer to temporary.
  lib/mayaUsd/ufe/UsdTransform3dBase.cpp
  lib/mayaUsd/ufe/UsdTransform3dBase.h
  lib/mayaUsd/ufe/UsdTransform3dMatrixOp.cpp
Labels: ready-for-merge

#992 MAYA-108519 Choose an appropriate location to open the file dialog.
  plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
Labels: workflows

#993 Clean up Visibility Logics
  lib/mayaUsd/ufe/UsdObject3d.cpp
Labels: ready-for-merge, workflows

#998 use the PXR_NS macro instead of pxr in the layer editor
  lib/usd/ui/layerEditor/abstractCommandHook.h
  lib/usd/ui/layerEditor/layerTreeItem.cpp
  lib/usd/ui/layerEditor/layerTreeItem.h
  lib/usd/ui/layerEditor/layerTreeModel.h
  lib/usd/ui/layerEditor/layerTreeView.cpp
  lib/usd/ui/layerEditor/mayaCommandHook.cpp
  lib/usd/ui/layerEditor/mayaSessionState.cpp
  lib/usd/ui/layerEditor/mayaSessionState.h
  lib/usd/ui/layerEditor/pathChecker.cpp
  lib/usd/ui/layerEditor/pathChecker.h
  lib/usd/ui/layerEditor/saveLayersDialog.cpp
  lib/usd/ui/layerEditor/sessionState.cpp
  lib/usd/ui/layerEditor/sessionState.h
  lib/usd/ui/layerEditor/stageSelectorWidget.cpp
  lib/usd/ui/layerEditor/stageSelectorWidget.h
Labels: ready-for-merge

#999 remove a stray non-ASCII characters in copyright headers
  lib/mayaUsd/commands/editTargetCommand.cpp
  lib/mayaUsd/commands/layerEditorCommand.cpp
  lib/mayaUsd/commands/layerEditorWindowCommand.cpp
Labels: build, ready-for-merge

#1003 install and remove UsdMayaDiagnosticDelegate for adsk plugin load and unload
  lib/mayaUsd/utils/diagnosticDelegate.cpp
  plugin/adsk/plugin/plugin.cpp
  test/lib/usd/translators/testUsdExportStripNamespaces.py
Labels: adsk, ready-for-merge

#989 Added staticSingleSample flag, and optimize mesh attributes by default
  lib/mayaUsd/commands/baseExportCommand.cpp
  lib/mayaUsd/commands/baseExportCommand.h
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/primWriter.cpp
  lib/mayaUsd/fileio/primWriter.h
  lib/usd/translators/meshWriter.cpp
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
  plugin/pxr/maya/lib/usdMaya/usdTranslatorExport.mel
  test/lib/usd/translators/testUsdExportAnimation.py
  test/lib/usd/translators/testUsdExportAsClip.py
Labels: import-export, ready-for-merge

#970 Convert USD timeSamples to Maya FPS
  lib/mayaUsd/fileio/jobs/readJob.cpp
  lib/mayaUsd/fileio/jobs/readJob.h
  lib/mayaUsd/fileio/jobs/writeJob.cpp
  lib/mayaUsd/fileio/primReaderContext.cpp
  lib/mayaUsd/fileio/primReaderContext.h
  lib/mayaUsd/fileio/translators/translatorCamera.cpp
  lib/mayaUsd/fileio/translators/translatorCurves.cpp
  lib/mayaUsd/fileio/translators/translatorMesh.cpp
  lib/mayaUsd/fileio/translators/translatorMesh.h
  lib/mayaUsd/fileio/translators/translatorNurbsPatch.cpp
  lib/mayaUsd/fileio/translators/translatorPrim.cpp
  lib/mayaUsd/fileio/translators/translatorSkel.cpp
  lib/mayaUsd/fileio/translators/translatorXformable.cpp
  lib/mayaUsd/utils/util.cpp
  lib/mayaUsd/utils/util.h
  lib/usd/translators/meshReader.cpp
  lib/usd/translators/skelReader.cpp
  plugin/pxr/maya/lib/usdMaya/testenv/testUsdImportNestedAssemblyAnimation.py
  test/lib/mayaUsd/nodes/testPointBasedDeformerNode.py
  test/lib/usd/translators/CMakeLists.txt
  test/lib/usd/translators/UsdImportFramerates/framerate.usda
  test/lib/usd/translators/testUsdExportLayerAttributes.py
  test/lib/usd/translators/testUsdImportCamera.py
  test/lib/usd/translators/testUsdImportFramerates.py
  test/lib/usd/translators/testUsdImportRfMLight.py
Labels: import-export, ready-for-merge

#1007 ensure that GL is initialized when mtoh creates the Storm render delegate
  lib/mayaUsd/render/mayaToHydra/utils.cpp
Labels: mtoh, ready-for-merge

#1006 duplicate baseline images for testMtohVisibility to isolate it from other tests
  test/lib/mayaUsd/render/mayaToHydra/MtohVisibilityTest/cube_unselected.png
  test/lib/mayaUsd/render/mayaToHydra/MtohVisibilityTest/nothing.png
  test/lib/mayaUsd/render/mayaToHydra/testMtohVisibility.py
Labels: mtoh, unit test

#1010 Fix 59.95FPS double conversion
  lib/mayaUsd/utils/util.cpp
Labels: import-export

#1012 Add testUsdExportAnimation for staticSingleSamples flag to CMakeList
  test/lib/usd/translators/CMakeLists.txt
Labels: import-export, ready-for-merge

#1013 Fix a build issue on Linux with maya<2020
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeUI.cpp
Labels: build, ready-for-merge

#966 MAYA-106937 Prototype support for GPU Normals and OSD using glsl.
  cmake/modules/FindMaya.cmake
  lib/mayaUsd/render/CMakeLists.txt
  lib/mayaUsd/render/vp2ComputeShaders/CMakeLists.txt
  lib/mayaUsd/render/vp2ComputeShaders/computeNormals.cl
  lib/mayaUsd/render/vp2ComputeShaders/computeNormals.glsl
  lib/mayaUsd/render/vp2ComputeShaders/plugInfo.json
  lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mesh.h
  lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.cpp
  lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.h
Labels: ready-for-merge, vp2renderdelegate

#994 MAYA-107449 Layer disappears when moved under last layer.
  lib/mayaUsd/commands/layerEditorCommand.cpp
  test/lib/testMayaUsdLayerEditorCommands.py
Labels: ready-for-merge

#1009 [tests] interactive tests ensure output streams are flushed before quitting
  plugin/al/plugin/AL_USDMayaTestPlugin/py/testLayerManager.py
  plugin/al/plugin/AL_USDMayaTestPlugin/py/testProxyShape.py
  plugin/al/plugin/AL_USDMayaTestPlugin/py/testTranslators.py
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testBatchRendererIsolateSelection.py
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testPxrUsdMayaGLInstancerDraw.py
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testRefAssemblyDrawRepresentations.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawAndTransform.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawColorAccuracy.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawColors.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawLighting.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawPerformance.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawPurpose.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawTimeSampled.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawUsdChangeProcessing.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDrawVisibility.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeDuplicatePerformance.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeLiveSurface.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeRendererSceneMessages.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeSelectionPerformance.py
  test/lib/mayaUsd/render/pxrUsdMayaGL/testPxrUsdMayaGL.py
  test/lib/usd/pxrUsdPreviewSurface/testPxrUsdPreviewSurfaceDraw.py
Labels: ready-for-merge, unit test

#1015 MAYA-106310 - Crash when querying target layer and nothing is assigne…
  lib/mayaUsd/commands/layerEditorCommand.cpp
  lib/usd/ui/layerEditor/layerTreeItem.cpp
  lib/usd/ui/layerEditor/mayaCommandHook.cpp
  test/lib/testMayaUsdLayerEditorCommands.py
Labels: ready-for-merge, workflows

#1023 [mtoh] don't build Maya-To-Hydra if maya==2019 AND USD==(20.08||20.11)
  CMakeLists.txt
Labels: build, mtoh, ready-for-merge

#1024 Fix incorrect `bindTransforms` being determined during export
  lib/usd/translators/jointWriter.cpp
  test/lib/usd/translators/CMakeLists.txt
  test/lib/usd/translators/UsdExportBindTransformsTest/bindTransformsExport.ma
  test/lib/usd/translators/testUsdExportBindTransform.py
Labels: import-export, ready-for-merge

#1025 updates for building with latest post-20.11 dev branch of core USD
  .clang-format
  doc/build.md
  lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
  lib/mayaUsd/render/mayaToHydra/renderOverride.h
  lib/mayaUsd/render/mayaToHydra/utils.cpp
  lib/mayaUsd/render/px_vp20/glslProgram.cpp
  lib/mayaUsd/render/px_vp20/utils.cpp
  lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.cpp
  lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.h
  lib/mayaUsd/render/pxrUsdMayaGL/proxyShapeDelegate.cpp
  lib/mayaUsd/render/vp2RenderDelegate/instancer.cpp
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.cpp
  lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.h
  lib/mayaUsd/render/vp2RenderDelegate/sampler.h
  lib/usd/hdMaya/delegates/delegate.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/PluginRegister.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp
Labels: build, ready-for-merge
