Repository Autodesk/maya-usd, pull requests merged in 2020-03, with the labels that each got.

#318 Qt support for older versions of Maya
  CMakeLists.txt
  doc/build.md
  lib/usd/ui/views/ItemDelegate.cpp
  lib/usd/ui/views/USDImportDialog.cpp
Labels: enhancement

#292 Fix up mtoh initialization to not create entries for invalid delagates.
  lib/render/mayaToHydra/plugin.cpp
  lib/render/mayaToHydra/renderGlobals.cpp
  lib/render/mayaToHydra/renderGlobals.h
  lib/render/mayaToHydra/tokens.h
  lib/render/mayaToHydra/utils.cpp
  lib/render/mayaToHydra/utils.h
  lib/render/mayaToHydra/viewCommand.cpp
Labels: mtoh

#303 Autodesk/tremblp/maya 103495/contextual operations
  lib/CMakeLists.txt
  lib/ufe/Global.cpp
  lib/ufe/UsdContextOps.cpp
  lib/ufe/UsdContextOps.h
  lib/ufe/UsdContextOpsHandler.cpp
  lib/ufe/UsdContextOpsHandler.h
  test/lib/ufe/CMakeLists.txt
  test/lib/ufe/testContextOps.py
Labels: pending beta, requires maya, ufe, ufe-usd

#312 [hdMaya] Build menu UI from TfEnum
  lib/render/mayaToHydra/renderGlobals.cpp
  lib/render/mayaToHydra/utils.cpp
Labels: mtoh

#328 MAYA-103731 - OAST: Jinja 2.10 WS report of CVE-2019-10906
  cmake/jinja.cmake
Labels: build

#329 Replace PXRUSDMAYA_DEFINE_READER macro with class declaration/definition to make the code easier to read and debug.
  lib/usd/translators/meshReader.cpp
Labels: pxr

#325 Add missing paths in "PXR_PLUGINPATH_NAME"
  plugin/al/plugin/AL_USDMayaTestPlugin/CMakeLists.txt
  plugin/al/plugin/AL_USDMayaTestPlugin/py/CMakeLists.txt
  plugin/al/translators/pxrUsdTranslators/tests/CMakeLists.txt
  plugin/al/translators/tests/CMakeLists.txt
  test/lib/usd/schemas/CMakeLists.txt
Labels: al, unit test

#326 MAYA-103736 Clear frameSamples set
  plugin/adsk/plugin/exportTranslator.cpp
Labels: adsk, import-export

#212 [WIP] [al] re-enable testTranslators.py
  plugin/al/plugin/AL_USDMayaTestPlugin/py/testTranslators.py
Labels: do-not-merge-yet, unit test

#315 add a way for pxrUsdProxyShape to disable subpath selection with the VP2.0 render delegate
  lib/nodes/proxyShapeBase.cpp
  lib/nodes/proxyShapeBase.h
  lib/render/vp2RenderDelegate/proxyRenderDelegate.cpp
  plugin/pxr/maya/lib/usdMaya/proxyShape.cpp
Labels: proxy, vp2renderdelegate, workflows

#311 [hdMaya] remove MtohGetDefaultRenderer
  lib/render/mayaToHydra/utils.cpp
  lib/render/mayaToHydra/utils.h
Labels: mtoh

#323 CMake Modernization and cleanup in lib and plugin/adsk
  CMakeLists.txt
  cmake/jinja.cmake
  cmake/modules/FindMaya.cmake
  cmake/usd.cmake
  cmake/utils.cmake
  lib/CMakeLists.txt
  lib/ae/CMakeLists.txt
  lib/base/CMakeLists.txt
  lib/base/debugCodes.cpp
  lib/fileio/CMakeLists.txt
  lib/fileio/registryHelper.cpp
  lib/listeners/CMakeLists.txt
  lib/nodes/CMakeLists.txt
  lib/python/CMakeLists.txt
  lib/render/CMakeLists.txt
  lib/render/mayaToHydra/CMakeLists.txt
  lib/render/px_vp20/CMakeLists.txt
  lib/render/pxrUsdMayaGL/CMakeLists.txt
  lib/render/vp2RenderDelegate/CMakeLists.txt
  lib/render/vp2ShaderFragments/CMakeLists.txt
  lib/ufe/CMakeLists.txt
  lib/usd/hdMaya/CMakeLists.txt
  lib/usd/schemas/CMakeLists.txt
  lib/usd/schemas/plugInfo.json.in
  lib/usd/schemas/schema.usda.in
  lib/usd/translators/CMakeLists.txt
  lib/usd/translators/plugInfo.json
  lib/usd/ui/CMakeLists.txt
  lib/usd/ui/demo/CMakeLists.txt
  lib/usd/utils/CMakeLists.txt
  lib/utils/CMakeLists.txt
  plugin/adsk/CMakeLists.txt
  plugin/adsk/plugin/CMakeLists.txt
  plugin/adsk/scripts/CMakeLists.txt
  plugin/al/lib/AL_USDMaya/CMakeLists.txt
  plugin/al/plugin/AL_USDMayaPlugin/CMakeLists.txt
  plugin/al/plugin/AL_USDMayaTestPlugin/CMakeLists.txt
  plugin/al/schemas/AL/usd/schemas/maya/CMakeLists.txt
  plugin/al/schemas/AL/usd/schemas/mayatest/CMakeLists.txt
  plugin/al/translators/pxrUsdTranslators/CMakeLists.txt
  plugin/al/usdtransaction/AL/usd/transaction/CMakeLists.txt
  plugin/pxr/cmake/macros/Private.cmake
  test/lib/CMakeLists.txt
  test/lib/ufe/CMakeLists.txt
  test/lib/usd/CMakeLists.txt
  test/lib/usd/schemas/CMakeLists.txt
  test/lib/usd/utils/CMakeLists.txt
Labels: build

#346 Make the build instructions more clear on which version of USD to get.
  doc/build.md
Labels: documentation

#345 adapt to UsdImagingDelegate::PopulateSelection param change
  doc/build.md
  lib/render/vp2RenderDelegate/proxyRenderDelegate.cpp
  lib/usd/hdMaya/adapters/proxyAdapter.cpp
Labels: build

#359 Add change log for v0.1.0
  doc/CHANGELOG.md
Labels: documentation

#347 Fix testPxrUsdPreviewSurfaceExport failure on Windows
  plugin/pxr/maya/plugin/pxrUsdPreviewSurface/CMakeLists.txt
Labels: pxr, unit test

#355 Fixes for staging dir builds
  lib/CMakeLists.txt
  lib/usd/translators/CMakeLists.txt
  plugin/al/CMakeLists.txt
  plugin/al/lib/AL_USDMaya/CMakeLists.txt
  plugin/al/schemas/AL/usd/schemas/maya/CMakeLists.txt
  plugin/al/schemas/AL/usd/schemas/mayatest/CMakeLists.txt
  plugin/al/translators/CMakeLists.txt
  plugin/al/translators/pxrUsdTranslators/CMakeLists.txt
  plugin/al/usdtransaction/CMakeLists.txt
  plugin/pxr/cmake/macros/Public.cmake
Labels: build

#356 Clone from existing shader instance to avoid extra cost.
  lib/render/vp2RenderDelegate/render_delegate.cpp
Labels: vp2renderdelegate

#362 Fix for find_package(GTest) when compiling in Debug
  cmake/CMakeLists_googletest_download.txt.in
  cmake/Googletest.cmake
Labels: build

#354 MAYA-103370 - Traverse instance proxies
  lib/ufe/UsdHierarchy.cpp
Labels: enhancement, ufe-usd

#352 MAYA-103655 Object3d visibility
  lib/ufe/StagesSubject.cpp
  lib/ufe/UsdAttribute.cpp
  lib/ufe/UsdContextOps.cpp
  lib/ufe/UsdObject3d.cpp
  lib/ufe/UsdObject3d.h
  lib/ufe/UsdObject3dHandler.cpp
  test/lib/ufe/CMakeLists.txt
  test/lib/ufe/testObject3d.py
  test/lib/ufe/testRotateCmd.py
  test/lib/ufe/testScaleCmd.py
  test/lib/ufe/testTRSBase.py
  test/lib/ufe/testTransform3dTranslate.py
Labels: ufe, ufe-usd, workflows

#242 [tests] add cmake functions for adding tests
  CMakeLists.txt
  cmake/test.cmake
  cmake/utils.cmake
  plugin/al/mayautils/AL/maya/tests/mayaplugintest/CMakeLists.txt
  plugin/al/plugin/AL_USDMayaTestPlugin/CMakeLists.txt
  plugin/al/plugin/AL_USDMayaTestPlugin/py/CMakeLists.txt
  plugin/al/plugin/AL_USDMayaTestPlugin/py/testUSDMayaPythonModuleOnly.py
  plugin/al/schemas/AL/usd/schemas/maya/tests/CMakeLists.txt
  plugin/al/translators/pxrUsdTranslators/tests/CMakeLists.txt
  plugin/al/translators/tests/CMakeLists.txt
  plugin/al/usdtransaction/AL/usd/transaction/tests/CMakeLists.txt
  test/lib/CMakeLists.txt
  test/lib/ufe/CMakeLists.txt
  test/lib/usd/schemas/CMakeLists.txt
Labels: unit test

#343 Pixar Mesh read translator/utilities refactoring
  lib/fileio/CMakeLists.txt
  lib/fileio/translators/translatorMesh.cpp
  lib/fileio/translators/translatorMesh.h
  lib/fileio/translators/translatorMesh_PrimVars.cpp
  lib/fileio/translators/translatorMesh_SubDiv.cpp
  lib/fileio/utils/meshUtil.cpp
  lib/fileio/utils/meshUtil.h
  lib/usd/translators/meshReader.cpp
  lib/utils/util.cpp
  lib/utils/util.h
Labels: core, import-export

#372 Adopt to the new way of adding unit test.
  lib/usd/utils/CMakeLists.txt
  test/lib/usd/utils/CMakeLists.txt
Labels: build, unit test

#376 [al] fixed up some doxygen warnings
  plugin/al/lib/AL_USDMaya/AL/usdmaya/SelectabilityDB.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapePostLoadProcess.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/ExportParams.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/ImportParams.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/TransformIterator.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TestExtraDataPlugin.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TransformTranslator.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorBase.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorContext.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/BasicTransformationMatrix.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Transform.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.h
Labels: al, documentation

#357 Support animated transform ops
  lib/ufe/UsdTransform3d.cpp
Labels: ufe-usd, workflows

#374 [AL] Ensure UsdGeomXformOp names match Common API
  plugin/al/lib/AL_USDMaya/AL/usdmaya/Version.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TransformTranslator.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.cpp
Labels: al, import-export

#375 [AL] Added support of animated near/far clipping planes
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/AnimationTranslator.cpp
  plugin/al/mayatest/AL/maya/test/testHelpers.cpp
  plugin/al/mayatest/AL/maya/test/testHelpers.h
  plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_CameraTranslator.cpp
  plugin/al/translators/Camera.cpp
  plugin/al/usdmayautils/AL/usdmaya/utils/AnimationTranslator.h
  plugin/al/usdmayautils/AL/usdmaya/utils/DgNodeHelper.cpp
  plugin/al/usdmayautils/AL/usdmaya/utils/DgNodeHelper.h
Labels: al, import-export

#364 Fix for installing the gtest shared library on Linux/Mac.
  cmake/Googletest.cmake
Labels: build

#369 clean up part1
  lib/CMakeLists.txt
  lib/python/CMakeLists.txt
  lib/render/mayaToHydra/CMakeLists.txt
  lib/ufe/CMakeLists.txt
  lib/usd/hdMaya/CMakeLists.txt
  lib/usd/ui/CMakeLists.txt
  lib/usd/ui/demo/CMakeLists.txt
Labels: build

#382 Rename googletest file names to match the naming convention in the cmake system.
  CMakeLists.txt
  cmake/googletest.cmake
  cmake/googletest_download.txt.in
  cmake/googletest_src.txt.in
Labels: enhancement

#380 Add coding guidelines for maya-usd repository
  README.md
  doc/codingGuidelines.md
Labels: documentation

#384 add Markdown version of Pixar Maya USD Plugin Doc
  plugin/pxr/doc/README.md
Labels: documentation, pxr

#383 MAYA-104008 - UFE AE : Transform Attributes in Several Sections
  lib/ae/base/ae_template.py
Labels: ufe-usd, workflows

#368 Tremblp/maya 103295/ufe path string usd
  lib/ufe/Global.cpp
  test/lib/ufe/testDeleteCmd.py
Labels: ufe-usd, workflows

#381 MAYA-103421 - UFE selecting certain USD objects will throw errors
  lib/ufe/UsdAttribute.cpp
  lib/ufe/UsdAttribute.h
Labels: ufe-usd, workflows
