Repository Autodesk/maya-usd, pull requests merged in 2021-09, with the labels that each got.

#1668 MAYA-113002 - Create USD and Maya-USD plugin artifacts built with Pyt…
  CMakeLists.txt
  cmake/python.cmake
Labels: build

#1670 MAYA-113309 MayaUSD : Python bindings for prim translators
  lib/mayaUsd/fileio/primWriter.cpp
  lib/mayaUsd/fileio/primWriter.h
  lib/mayaUsd/fileio/registryHelper.cpp
  lib/mayaUsd/fileio/registryHelper.h
  lib/mayaUsd/python/CMakeLists.txt
  lib/mayaUsd/python/module.cpp
  lib/mayaUsd/python/wrapExportChaser.cpp
  lib/mayaUsd/python/wrapImportChaser.cpp
  lib/mayaUsd/python/wrapOpenMaya.cpp
  lib/mayaUsd/python/wrapPrimReader.cpp
  lib/mayaUsd/python/wrapPrimWriter.cpp
  test/lib/mayaUsd/fileio/CMakeLists.txt
  test/lib/mayaUsd/fileio/testExportChaser.py
  test/lib/mayaUsd/fileio/testImportChaser.py
  test/lib/mayaUsd/fileio/testPrimReader.py
  test/lib/mayaUsd/fileio/testPrimReader.usda
  test/lib/mayaUsd/fileio/testPrimWriter.py
  test/lib/mayaUsd/fileio/testShaderReader.py
  test/lib/mayaUsd/fileio/testShaderWriter.py
Labels: ready-for-merge

#1677 MAYA-112663 - I'd like to select by point instancers, instances and prototypes
  plugin/adsk/scripts/mayaUSDRegisterStrings.mel
  plugin/adsk/scripts/mayaUsdMenu.mel
Labels: adsk, ready-for-merge

#1682 Fixing lighting issues with UsdPreviewSurface
  lib/mayaUsd/render/vp2ShaderFragments/UsdPreviewSurfaceLightAPI1.xml
  lib/mayaUsd/render/vp2ShaderFragments/usdPreviewSurfaceCombiner.xml
  lib/mayaUsd/render/vp2ShaderFragments/usdPreviewSurfaceLightingAPI1.xml
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateUSDPreviewSurface/baseline/F0_is_base_V1.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateUSDPreviewSurface/baseline/F0_is_base_V2.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateUSDPreviewSurface/baseline/testMetallicResponseLightAPI1.png
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateUSDPreviewSurface.py
  test/testSamples/UsdPreviewSurface/F0_is_base.usda
Labels: vp2renderdelegate, ready-for-merge, materials

#1683 Verify that the DAG path of the returned proxy shape object matches
  lib/mayaUsd/ufe/UsdStageMap.cpp
  lib/mayaUsd/ufe/Utils.cpp
Labels: ready-for-merge

#1684 MAYA-109415 Fix warning on blendShape export
  lib/usd/translators/meshWriter.cpp
Labels: import-export, ready-for-merge

#1675 MAYA-113559 prevent crash when accessing a stale attribute from Python
  lib/mayaUsd/ufe/UsdAttribute.cpp
Labels: ready-for-merge

#1692 Properly use fallback color in vp2RenderDelegate
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  lib/mayaUsd/render/vp2RenderDelegate/material.h
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateUSDPreviewSurface/baseline/TestFallbackColor.png
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateUSDPreviewSurface.py
  test/testSamples/UsdPreviewSurface/TestFallbackColor.usda
Labels: vp2renderdelegate, ready-for-merge

#1695 Made filteredTypeIds const in export job arguments
  lib/mayaUsd/commands/baseExportCommand.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/writeJobContext.cpp
  plugin/adsk/plugin/exportTranslator.cpp
  plugin/pxr/maya/lib/usdMaya/exportTranslator.cpp
Labels: import-export, ready-for-merge

#1686 Ignored setting playback range if no time code found from USD
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/Import.cpp
  plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/fileio/import_playback_range.cpp
  plugin/al/plugin/AL_USDMayaTestPlugin/CMakeLists.txt
Labels: al

#1696 Fix MaterialX code generation
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  lib/mayaUsd/ufe/Utils.cpp
Labels: vp2renderdelegate, build, ready-for-merge

#1699 Boudrey/maya 113469/register
  lib/mayaUsd/python/wrapAdaptor.cpp
  lib/mayaUsd/python/wrapOpenMaya.cpp
  test/lib/mayaUsd/fileio/testShaderWriter.py
  test/lib/usd/translators/testUsdMayaAdaptor.py
Labels: import-export, ready-for-merge

#1709 MAYA-113821 MayaUSD : Python bindings un-registration of registered t…
  lib/mayaUsd/fileio/chaser/exportChaserRegistry.cpp
  lib/mayaUsd/fileio/chaser/exportChaserRegistry.h
  lib/mayaUsd/fileio/chaser/importChaserRegistry.cpp
  lib/mayaUsd/fileio/chaser/importChaserRegistry.h
  lib/mayaUsd/fileio/primReaderRegistry.cpp
  lib/mayaUsd/fileio/primReaderRegistry.h
  lib/mayaUsd/fileio/primWriterRegistry.cpp
  lib/mayaUsd/fileio/primWriterRegistry.h
  lib/mayaUsd/fileio/registryHelper.cpp
  lib/mayaUsd/fileio/registryHelper.h
  lib/mayaUsd/fileio/shaderReaderRegistry.cpp
  lib/mayaUsd/fileio/shaderReaderRegistry.h
  lib/mayaUsd/fileio/shaderWriterRegistry.cpp
  lib/mayaUsd/fileio/shaderWriterRegistry.h
  lib/mayaUsd/fileio/utils/adaptor.cpp
  lib/mayaUsd/fileio/utils/adaptor.h
  lib/mayaUsd/python/wrapAdaptor.cpp
  lib/mayaUsd/python/wrapExportChaser.cpp
  lib/mayaUsd/python/wrapImportChaser.cpp
  lib/mayaUsd/python/wrapPrimReader.cpp
  lib/mayaUsd/python/wrapPrimWriter.cpp
Labels: ready-for-merge

#1710 Add duplicate check during translator context deserialise based on prim path match
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorContext.cpp
Labels: al

#1711 Bail on proxyDrawOverride user select early if snapping is active
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp
Labels: al

#1698 Fix python 3.9 AL TransactionManager crash
  plugin/al/lib/AL_USDMaya/AL/usdmaya/Global.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/Global.h
  plugin/al/usdtransaction/AL/usd/transaction/TransactionManager.cpp
  plugin/al/usdtransaction/AL/usd/transaction/TransactionManager.h
  plugin/al/usdtransaction/AL/usd/transaction/tests/testTransaction.py
  plugin/al/usdtransaction/AL/usd/transaction/tests/testTransactionManager.py
  plugin/al/usdtransaction/AL/usd/transaction/wrapTransactionManager.cpp
Labels: ready-for-merge

#1716 Boudrey/maya 113815/centos8
  cmake/googletest.cmake
  cmake/googletest_download.txt.in
  cmake/googletest_src.txt.in
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
Labels: ready-for-merge

#1715 MAYA-112768 - Channel box for USD prims
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/Global.cpp
  lib/mayaUsd/ufe/UsdUIUfeObserver.cpp
  lib/mayaUsd/ufe/UsdUIUfeObserver.h
  plugin/adsk/scripts/mayaUsd_pluginUICreation.mel
  test/lib/ufe/testAttribute.py
Labels: adsk, ufe-usd, ready-for-merge

#1678 Add tests for sets command and for isolate select in Vp2RenderDelegate.
  test/lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateIsolateSelectTest/baseline/capsuleAndCube.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateIsolateSelectTest/baseline/capsuleAndCubeAndCone.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateIsolateSelectTest/baseline/cube.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateIsolateSelectTest/baseline/cylinder.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateIsolateSelectTest/baseline/cylinderAfterCapsuleRemove.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateIsolateSelectTest/baseline/cylinderAndCapsule.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateIsolateSelectTest/baseline/isolateSelectOff.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateIsolateSelectTest/baseline/redoCapsuleRemove.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateIsolateSelectTest/baseline/reparentedCube.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateIsolateSelectTest/baseline/reparentedCubeBack.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateIsolateSelectTest/baseline/reparentedProxyShape.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateIsolateSelectTest/baseline/undoCapsuleAdd.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateIsolateSelectTest/baseline/undoCapsuleRemove.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateIsolateSelectTest/baseline/unselected.png
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateIsolateSelect.py
  test/lib/ufe/CMakeLists.txt
  test/lib/ufe/testSetsCmd.py
  test/testSamples/setsCmd/5prims.usda
Labels: vp2renderdelegate, unit test, ready-for-merge

#1722 MAYA-113464 MayaUSD : Python bindings for chasers
  test/lib/mayaUsd/fileio/testExportChaser.py
  test/lib/mayaUsd/fileio/testPrimWriter.py
Labels: ready-for-merge

#1724 Removed AL custom profiling code and added maya profiling
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  plugin/al/docs/developer.md
  plugin/al/lib/AL_USDMaya/AL/usdmaya/CodeTimings.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/CodeTimings.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/SelectabilityDB.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/StageCache.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapePostLoadProcess.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/Import.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorBase.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorContext.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Engine.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/LayerManager.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeSelection.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Transform.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/proxy/LockManager.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/proxy/PrimFilter.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/proxy/ProxyShapeMetaData.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/proxy/ProxyShapeVariantFallbacks.cpp
  plugin/al/lib/AL_USDMaya/CMakeLists.txt
  plugin/al/translators/Camera.cpp
  plugin/al/translators/MayaReference.cpp
  plugin/al/translators/Mesh.cpp
  plugin/al/translators/NurbsCurve.cpp
  plugin/al/usdmayautils/AL/usdmaya/utils/AnimationTranslator.cpp
Labels: al

#1723 Fix compilation issue for schema, header and UFE linking
  lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.cpp
  lib/usd/pxrUsdPreviewSurface/CMakeLists.txt
  lib/usd/schemas/CMakeLists.txt
  plugin/pxr/maya/lib/usdMaya/CMakeLists.txt
Labels: build

#1728 Fill in missing export translator implementation
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/wrapTranslatorBase.cpp
Labels: al, ready-for-merge

#1726 Fix excluded prim paths
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/proxy/ProxyShapeMetaData.cpp
Labels: al, ready-for-merge

#1727 Avoid opening duplicated usd stages on Maya file load
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
Labels: al, ready-for-merge
