Repository Autodesk/maya-usd, pull requests merged in 2021-10, with the labels that each got.

#1729 Fix translator context on nested proxy shapes
  plugin/al/lib/AL_USDMaya/AL/usdmaya/Global.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapePostLoadProcess.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorBase.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorBase.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
Labels: al, ready-for-merge

#1771 Added intersection test command for ProxyDrawOverride
  plugin/al/lib/AL_USDMaya/AL/usdmaya/PluginRegister.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapeCommands.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapeCommands.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp
Labels: al

#1797 Fix testAttribute random failure
  test/lib/ufe/testAttribute.py
Labels: unit test, ready-for-merge

#1791 Fixed tagged excluded prims to update correctly when changed
  plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapeCommands.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/proxy/ProxyShapeMetaData.cpp
Labels: al, ready-for-merge
