Repository Autodesk/maya-usd, pull requests merged in 2022-04, with the labels that each got.

#2247 Updating changelog for v0.17.0.
  doc/CHANGELOG.md
Labels: documentation

#2249 Update version to v0.18.0
  cmake/mayausd_version.info
Labels: build, ready-for-merge

#2219 [al] Fixed dead loop issue when deleting node
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeSelection.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Scope.cpp
Labels: al, ready-for-merge

#2198 MAYA-114716 add layer editor menu item
  plugin/adsk/scripts/mayaUsdMenu.mel
Labels: adsk, ready-for-merge

#2195 MAYA-108102 Add unit test for select -addFirst
  test/lib/ufe/testSelection.py
  test/testUtils/mayaUtils.py
Labels: unit test, ready-for-merge

#2207 MAYA-121534 Expose colorCorrect node to Mtlx
  lib/mayaUsd/render/MaterialXGenOgsXml/CMakeLists.txt
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/lookdevKit.mtlx
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/lookdevKit_ng.mtlx
  lib/usd/translators/shading/CMakeLists.txt
  lib/usd/translators/shading/mtlxBaseReader.cpp
  lib/usd/translators/shading/mtlxSymmetricShaderWriter.cpp
  lib/usd/translators/shading/mtlxSymmetricShaderWriter.h
  lib/usd/translators/shading/shadingTokens.cpp
  lib/usd/translators/shading/shadingTokens.h
  test/lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/MayaSurfaces_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/MtlxUVStreamTest_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/mtlxNodesShowcase_Import_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/mtlxNodesShowcase_Maya_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/mtlxNodesShowcase_USD_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/place2dTextureShowcase_Import_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/place2dTextureShowcase_Maya_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/place2dTextureShowcase_USD_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateMaterialX.py
  test/testSamples/MaterialX/mtlxNodesShowcase.ma
Labels: vp2renderdelegate, ready-for-merge

#2203 Added stage export option to disable authoring of distance unit
  lib/mayaUsd/commands/Readme.md
  lib/mayaUsd/commands/baseExportCommand.cpp
  lib/mayaUsd/commands/baseExportCommand.h
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/jobs/writeJob.cpp
  lib/mayaUsd/python/wrapPrimWriter.cpp
Labels: import-export, ready-for-merge

#2216 [al] Reduce floating point comparison precision to avoid making edit layer dirty
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.cpp
  plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_TransformMatrix.cpp
Labels: al, ready-for-merge

#2217 [al] Fixed uninitialized variable that caused NaN xform values after importing
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.cpp
  plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_Transform.cpp
  plugin/al/plugin/AL_USDMayaTestPlugin/test_data/animated_camera.usda
Labels: al, ready-for-merge

#2204 MAYA-114678 [Github #1739] USDExport: using "parentScope" and "export…
  lib/mayaUsd/fileio/writeJobContext.cpp
  test/lib/usd/translators/CMakeLists.txt
  test/lib/usd/translators/testUsdExportRootsAndParentScope.py
Labels: import-export, ready-for-merge

#2226 MAYA-114603 persist USD payload state
  lib/mayaUsd/listeners/notice.cpp
  lib/mayaUsd/nodes/CMakeLists.txt
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/nodes/proxyShapeLoadRules.cpp
  lib/mayaUsd/nodes/proxyShapeLoadRules.h
  lib/mayaUsd/nodes/proxyShapePlugin.cpp
  lib/mayaUsd/utils/CMakeLists.txt
  lib/mayaUsd/utils/loadRules.h
  lib/mayaUsd/utils/loadRulesAttribute.cpp
  lib/mayaUsd/utils/loadRulesText.cpp
  test/lib/mayaUsd/utils/CMakeLists.txt
  test/lib/mayaUsd/utils/main.cpp
  test/lib/mayaUsd/utils/testLoadRules.cpp
Labels: enhancement, workflows, ready-for-merge

#2236 Fix MaterialX not working with AMD material lib
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
Labels: vp2renderdelegate, ready-for-merge

#2238 MAYA-122124 avoid errors in marking menu
  lib/mayaUsd/ufe/Utils.cpp
Labels: ufe-usd, ready-for-merge

#2259 MAYA-108102 test depends on Maya version after 2023.
  test/lib/ufe/testSelection.py
Labels: requires maya, ufe, ready-for-merge

#2223 MAYA-121806 Flat shading using V3 lighting API
  cmake/modules/FindMaya.cmake
  lib/mayaUsd/CMakeLists.txt
  lib/mayaUsd/render/MaterialXGenOgsXml/CMakeLists.txt
  lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/SurfaceNodeMaya.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/OgsXmlGenerator.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/OgsXmlGenerator.h
  lib/mayaUsd/render/MaterialXGenOgsXml/README.md
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_lighting_maya_v3.glsl
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  lib/mayaUsd/render/vp2RenderDelegate/render_delegate.cpp
  lib/mayaUsd/render/vp2ShaderFragments/CMakeLists.txt
  lib/mayaUsd/render/vp2ShaderFragments/UsdPreviewSurfaceLightAPI3.xml
  lib/mayaUsd/render/vp2ShaderFragments/shaderFragments.cpp
  lib/mayaUsd/render/vp2ShaderFragments/usdPreviewSurfaceLightingAPI3.xml
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/MayaSurfaces_flat_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateUSDPreviewSurface/baseline/testMetallicResponseLightAPI3_flat.png
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateMaterialX.py
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateUSDPreviewSurface.py
Labels: vp2renderdelegate, ready-for-merge

#2251 [al] Mark outTime attribute dirty to force updating Maya bbox; fix incorrect time code for bbox
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
Labels: al, ready-for-merge

#2201 MAYA122097 Make the word 'tip'bold
  lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.mel
  lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.mel
Labels: adsk, ready-for-merge

#2252 [al] Add validation on custom transform node before accessing
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
Labels: al, ready-for-merge

#2253 Use USDLuxTokens for spot light
  lib/usd/hdMaya/adapters/spotLightAdapter.cpp
Labels: mtoh, ready-for-merge

#2260 MAYA-114603 use correct way to query attribute
  lib/mayaUsd/utils/loadRulesAttribute.cpp
Labels: workflows, ready-for-merge

#2243 Feldstj/dev usd shader node def
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/Global.cpp
  lib/mayaUsd/ufe/UsdAttributes.cpp
  lib/mayaUsd/ufe/UsdPointInstanceOrientationModifier.cpp
  lib/mayaUsd/ufe/UsdShaderNodeDef.cpp
  lib/mayaUsd/ufe/UsdShaderNodeDef.h
  lib/mayaUsd/ufe/UsdShaderNodeDefHandler.cpp
  lib/mayaUsd/ufe/UsdShaderNodeDefHandler.h
  lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
  lib/mayaUsd/ufe/Utils.cpp
  lib/mayaUsd/ufe/Utils.h
  test/lib/ufe/CMakeLists.txt
  test/lib/ufe/testShaderNodeDef.py
Labels: ufe-usd, ready-for-merge

#2261 Adds optionVars for controlling specular lighting options
  lib/mayaUsd/render/MaterialXGenOgsXml/CMakeLists.txt
  lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.h
  lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.h
  lib/mayaUsd/render/MaterialXGenOgsXml/OgsXmlGenerator.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_lighting_maya_none.glsl
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_lighting_maya_v3.glsl
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
Labels: vp2renderdelegate, ready-for-merge

#2282 LOOKDEVX-641: fix for latest Maya PR
  cmake/test.cmake
  lib/mayaUsd/ufe/UsdShaderNodeDef.cpp
  test/lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
  test/lib/usd/translators/CMakeLists.txt
Labels: unit test, build, ready-for-merge

#2286 Build Updates:
  .gitignore
  cmake/compiler_config.cmake
  cmake/googletest_download.txt.in
  cmake/googletest_src.txt.in
Labels: build, ready-for-merge

#2242 Fix for MAYA-122381 Target Layer moves and stays on Session Layer whe…
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/jobs/readJob.cpp
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  test/lib/mayaUsd/fileio/testEditAsMaya.py
Labels: ready-for-merge

#2280 MAYA-122250 UFE 3 build as Universal Binary 2 (x86_64 + arm64)
  CMakeLists.txt
  cmake/compiler_config.cmake
  plugin/al/plugin/AL_USDMayaTestPlugin/py/testTranslators.py
  plugin/al/tutorials/endToEndMaya/tutorial_scripts/add_set_to_s00.py
  plugin/al/tutorials/endToEndMaya/tutorial_scripts/prep_anim_shot_s00_01.py
Labels: ready-for-merge

#2291 Set the default light intensity the new way. Also force it to be set
  test/testUtils/imageUtils.py
Labels: ready-for-merge, regression

#2268 MAYA-122640 fix crash with deactivate and console
  lib/mayaUsd/ufe/UsdUIInfoHandler.cpp
  lib/mayaUsd/ufe/UsdUIInfoHandler.h
Labels: ufe-usd, ready-for-merge

#2245 MAYA-122369 fix missing edit after merge
  lib/usd/utils/MergePrims.cpp
  test/lib/mayaUsd/fileio/testMergeToUsd.py
  test/testUtils/usdUtils.py
Labels: adsk, ready-for-merge

#2290 MAYA-121532 push/pull: usdeditAsMaya set should be a locked node
  lib/mayaUsd/fileio/primUpdaterManager.cpp
Labels: import-export, ready-for-merge

#2296 MAYA-122706 [GitHub #2267] MaterialX doesn't display in the Viewport …
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_lighting_maya_v1.glsl
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_lighting_maya_v2.glsl
Labels: ready-for-merge

#2229 MAYA-121938 prevent recursive edit as Maya
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  test/lib/mayaUsd/fileio/testEditAsMaya.py
Labels: ready-for-merge

#2284 Refactored and simplified AL_USDMaya primvar interpolation type detection
  plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/test_DiffPrimVar.cpp
  plugin/al/usdmayautils/AL/usdmaya/utils/DiffPrimVar.cpp
  plugin/al/usdmayautils/AL/usdmaya/utils/DiffPrimVar.h
Labels: al, ready-for-merge

#2222 Enable proxyAccessor in AL_USDMaya
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
  plugin/al/plugin/AL_USDMayaTestPlugin/py/testProxyAccessor.py
Labels: al, ready-for-merge

#2224 Enable readAnimatedValues attribute on Camera translator import
  plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_CameraTranslator.cpp
  plugin/al/translators/Camera.cpp
Labels: al, ready-for-merge

#2279 MAYA-121599 - Active Selection Highlighting color doesn't work in Maya 2022 with USD
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
Labels: vp2renderdelegate, ready-for-merge

#2288 Fix build for USD versions past 21.11
  lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
  lib/mayaUsd/render/vp2RenderDelegate/points.cpp
Labels: build, ready-for-merge, regression

#2270 MAYA-114992 The true bindPose for a skin cluster comes from it's bindPreMatrix
  lib/usd/translators/jointWriter.cpp
  test/lib/usd/translators/testUsdExportBindTransform.py
  test/lib/usd/translators/testUsdExportSkeleton.py
Labels: import-export, ready-for-merge

#2294 Removed proxy shape pre/post selection events notification
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
Labels: al, ready-for-merge

#2300 Minor UI fixes
  lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.mel
  lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
  lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.mel
  lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
  lib/mayaUsd/resources/scripts/mayaUsdMergeToUSDOptions.py
  lib/mayaUsd/resources/scripts/mayaUsdOptions.py
Labels: workflows, ready-for-merge

#2287 Add contextual menu to bind materials
  lib/mayaUsd/ufe/UsdContextOps.cpp
  lib/mayaUsd/ufe/UsdShaderNodeDef.cpp
  test/lib/ufe/testContextOps.py
Labels: ready-for-merge, outliner, materials

#2275 MAYA-122641 It is not safe to call setParameter from a worker thread because it
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
  lib/mayaUsd/render/vp2RenderDelegate/render_delegate.cpp
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateBasisCurvesTest/baseline/basisCurves_selected_complexity0.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateBasisCurvesTest/baseline/basisCurves_selected_complexity1.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateBasisCurvesTest/baseline/basisCurves_selected_complexity2.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateBasisCurvesTest/baseline/basisCurves_selected_complexity3.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateBasisCurvesTest/baseline/basisCurves_unselected_complexity0.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateBasisCurvesTest/baseline/basisCurves_unselected_complexity1.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateBasisCurvesTest/baseline/basisCurves_unselected_complexity2.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateBasisCurvesTest/baseline/basisCurves_unselected_complexity3.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateBasisCurvesTest/baseline/nurbsCircleExport_selected_complexity0.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateBasisCurvesTest/baseline/nurbsCircleExport_selected_complexity1.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateBasisCurvesTest/baseline/nurbsCircleExport_selected_complexity2.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateBasisCurvesTest/baseline/nurbsCircleExport_selected_complexity3.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateBasisCurvesTest/baseline/nurbsCircleExport_unselected_complexity0.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateBasisCurvesTest/baseline/nurbsCircleExport_unselected_complexity1.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateBasisCurvesTest/baseline/nurbsCircleExport_unselected_complexity2.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateBasisCurvesTest/baseline/nurbsCircleExport_unselected_complexity3.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegatePointsTest/baseline/points_selected.png
Labels: vp2renderdelegate, ready-for-merge

#2278 MAYA-122656 remove assertion with incorrect expression.
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
Labels: vp2renderdelegate, ready-for-merge

#2298 MAYA-122123 make Define In options enabled
  lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.mel
  lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
  lib/mayaUsd/utils/editRouter.cpp
Labels: workflows, ready-for-merge

#2235 MAYA-122131 Maya Ref Auto-Edit Handling
  lib/usd/translators/mayaReferenceUpdater.cpp
  test/lib/mayaUsd/fileio/testAddMayaReference.py
Labels: workflows, ready-for-merge

#2265 MAYA-122218 showing dactivated children
  lib/mayaUsd/ufe/ProxyShapeHierarchy.cpp
  lib/mayaUsd/ufe/ProxyShapeHierarchy.h
  lib/mayaUsd/ufe/PulledObjectHierarchy.cpp
  lib/mayaUsd/ufe/PulledObjectHierarchy.h
  lib/mayaUsd/ufe/UsdHierarchy.cpp
  lib/mayaUsd/ufe/UsdHierarchy.h
  test/lib/ufe/testChildFilter.py
  test/lib/ufe/testContextOps.py
Labels: ready-for-merge

#2266 MAYA-122528 - MayaUSD should support UFE lights
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/Global.cpp
  lib/mayaUsd/ufe/UsdLight.cpp
  lib/mayaUsd/ufe/UsdLight.h
  lib/mayaUsd/ufe/UsdLightHandler.cpp
  lib/mayaUsd/ufe/UsdLightHandler.h
  test/lib/ufe/CMakeLists.txt
  test/lib/ufe/testLight.py
  test/testSamples/light/SimpleLight.usda
Labels: ufe-usd, ready-for-merge

#2305 MAYA-114501 added a user proc in USDMenuProc
  plugin/adsk/scripts/USDMenuProc.mel
Labels: adsk, ready-for-merge

#2309 MAYA-122128 NURBS defaut to off when caching
  lib/mayaUsd/resources/scripts/mayaUsdOptions.py
Labels: adsk, ready-for-merge

#2311 MAYA-122361 enforce cache file format
  lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.mel
  lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
  lib/mayaUsd/utils/editRouter.cpp
Labels: adsk, ready-for-merge

#2317 Can no longer pass ALL_INSTANCES into GetScenePrimPath.
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
Labels: vp2renderdelegate, ready-for-merge

#2319 Implement pivot accessors for wrapped matrix ops.
  lib/mayaUsd/ufe/UsdTransform3dSetObjectMatrix.cpp
  lib/mayaUsd/ufe/UsdTransform3dSetObjectMatrix.h
  test/lib/ufe/testRotatePivot.py
Labels: ufe-usd, ready-for-merge
