Repository Autodesk/maya-usd, pull requests merged in 2022-09, with the labels that each got.

#2570 MAYA-124909 - USD needs to support untextured mode like Maya does.
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mesh.h
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateDrawModes.py
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateMaterialX.py
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegatePerInstanceInheritedData.py
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateTextureLoading.py
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateUSDPreviewSurface.py
Labels: vp2renderdelegate, ready-for-merge

#2578 LOOKDEVX-571 | Initial implementation of AETemplate control creators.
  lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
Labels: ufe-usd, ready-for-merge

#2523 MAYA-108733 fix removing multiple layers at the same time
  lib/mayaUsd/commands/layerEditorCommand.cpp
  test/lib/testMayaUsdLayerEditorCommands.py
Labels: workflows, ready-for-merge

#2579 Fix MaterialX compilation on M1 Macs
  lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
Labels: vp2renderdelegate, ready-for-merge

#2582 LOOKDEVX-826 | Remove erroneous TF_VERIFY.
  lib/mayaUsd/ufe/UsdUINodeGraphNode.cpp
Labels: ufe-usd, ready-for-merge

#2581 Change how the active 3D view is retrieved in the test
  test/lib/mayaUsd/render/pxrUsdMayaGL/testProxyShapeLiveSurface.py
Labels: unit test, ready-for-merge

#2583 MAYA-124106 preserve timeline during edit-as-Maya
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/jobs/readJob.cpp
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/python/wrapPrimReader.cpp
  test/lib/mayaUsd/fileio/testEditAsMaya.py
Labels: import-export, ready-for-merge

#2584 MAYA-125142 add the python support for DagToUsdMap
  lib/mayaUsd/python/wrapExportChaser.cpp
  test/lib/usd/translators/testUsdImportExportSiteSpecificConfig.py
Labels: core, ready-for-merge

#2588 LOOKDEVX-571 | Adds support for converting strings with options into
  lib/mayaUsd/ufe/UsdAttribute.cpp
  lib/mayaUsd/ufe/UsdAttribute.h
  lib/mayaUsd/ufe/UsdAttributes.cpp
  lib/mayaUsd/ufe/UsdShaderAttributeDef.h
  lib/mayaUsd/ufe/Utils.cpp
  test/lib/ufe/testAttribute.py
  test/lib/ufe/testShaderNodeDef.py
Labels: ufe-usd, ready-for-merge

#2600 MAYA-124971 Do not change suffix if renamed to the same name
  lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp
  test/lib/ufe/testRename.py
Labels: core, ufe-usd, ready-for-merge

#2530 MAYA121636 handle scope for read-only transform
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/Global.cpp
  lib/mayaUsd/ufe/UsdTransform3dBase.cpp
  lib/mayaUsd/ufe/UsdTransform3dBase.h
  lib/mayaUsd/ufe/UsdTransform3dRead.cpp
  lib/mayaUsd/ufe/UsdTransform3dRead.h
  lib/mayaUsd/ufe/UsdTransform3dReadImpl.cpp
  lib/mayaUsd/ufe/UsdTransform3dReadImpl.h
  test/lib/ufe/testParentCmd.py
Labels: ufe-usd, ready-for-merge

#2595 Add support for Generic Shader Attributes
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/UsdAttribute.cpp
  lib/mayaUsd/ufe/UsdAttribute.h
  lib/mayaUsd/ufe/UsdAttributeHolder.cpp
  lib/mayaUsd/ufe/UsdAttributeHolder.h
  lib/mayaUsd/ufe/UsdAttributes.cpp
  lib/mayaUsd/ufe/UsdAttributes.h
  lib/mayaUsd/ufe/UsdShaderAttributeDef.h
  lib/mayaUsd/ufe/UsdShaderAttributeHolder.cpp
  lib/mayaUsd/ufe/UsdShaderAttributeHolder.h
  lib/mayaUsd/ufe/UsdShaderNodeDefHandler.cpp
  lib/mayaUsd/ufe/UsdShaderNodeDefHandler.h
  lib/mayaUsd/ufe/UsdUndoAttributesCommands.h
  lib/mayaUsd/ufe/Utils.cpp
  lib/mayaUsd/ufe/Utils.h
  test/lib/ufe/testConnections.py
  test/lib/ufe/testShaderNodeDef.py
Labels: ufe-usd, ready-for-merge

#2599 MAYA-123181 - As a user, I'd like my prims to be in untextured mode when in a Display Layer
  lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
  lib/mayaUsd/render/vp2RenderDelegate/basisCurves.h
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  lib/mayaUsd/render/vp2RenderDelegate/material.h
  lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mesh.h
  lib/mayaUsd/render/vp2RenderDelegate/points.cpp
  lib/mayaUsd/render/vp2RenderDelegate/points.h
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
  lib/mayaUsd/render/vp2RenderDelegate/tokens.h
Labels: vp2renderdelegate, ready-for-merge

#2604 MAYA-124973 handle trailing # in rename
  lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp
  test/lib/ufe/testRename.py
Labels: ufe-usd, ready-for-merge

#2596 Add missing includes
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/python/wrapXformStack.cpp
Labels: build, ready-for-merge

#2610 MAYA-125054 - Fix namespace renaming
  lib/usd/ui/layerEditor/mayaSessionState.cpp
  lib/usd/ui/layerEditor/mayaSessionState.h
Labels: bug, ready-for-merge

#2611 MAYA-125149 - When "Enable Overrides" is unchecked for a Display Layer USD Data still uses Bounding Box
  lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
  lib/mayaUsd/render/vp2RenderDelegate/points.cpp
  lib/mayaUsd/ufe/UsdAttributes.cpp
Labels: vp2renderdelegate, ready-for-merge

#2615 MAYA-124951: Duplicate as USD Data timeline options don't show what is currently applied
  lib/mayaUsd/resources/scripts/mayaUsdMergeToUSDOptions.py
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
Labels: adsk, ready-for-merge

#2613 Use Adapter to author MeshLightAPI for RfM's PxrMeshLight
  lib/mayaUsd/fileio/primWriterRegistry.cpp
  lib/mayaUsd/fileio/primWriterRegistry.h
  lib/mayaUsd/fileio/translators/translatorRfMLight.cpp
  lib/mayaUsd/fileio/translators/translatorRfMLight.h
  lib/mayaUsd/fileio/translators/translatorRfMLight_deprecated.cpp
  lib/mayaUsd/fileio/translators/translatorUtil.cpp
  lib/mayaUsd/fileio/translators/translatorUtil.h
  lib/mayaUsd/fileio/writeJobContext.cpp
  lib/usd/translators/CMakeLists.txt
  lib/usd/translators/lightRfMWriter.cpp
  lib/usd/translators/lightRfMWriter_PxrMeshLight.cpp
  lib/usd/translators/plugInfo.json
  test/lib/usd/translators/UsdExportRfMLightTest/RfMLightsTest.ma
  test/lib/usd/translators/testUsdExportRfMLight.py
  test/lib/usd/translators/testUsdImportRfMLight.py
Labels: import-export, ready-for-merge

#2616 Update build.md with Ufe version information.
  doc/build.md
Labels: documentation, ready-for-merge

#2612 MAYA-122927 prevent crash when discarding deactivated maya ref.
  lib/usd/translators/mayaReferenceUpdater.cpp
  test/lib/mayaUsd/fileio/testAddMayaReference.py
  test/lib/mayaUsd/fileio/testDiscardEdits.py
Labels: workflows, ready-for-merge

#2618 MAYA-123182 - As a user, I'd like my prims' wireframes to have a specific color and opacity when in a Display Layer
  lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
  lib/mayaUsd/render/vp2RenderDelegate/points.cpp
Labels: vp2renderdelegate, ready-for-merge

#2617 Show correct render backend name
  lib/mayaUsd/render/mayaToHydra/utils.cpp
Labels: mtoh, ready-for-merge

#2620 Use Pixar's namespace directive macro
  lib/mayaUsd/utils/utilDictionary.cpp
  lib/mayaUsd/utils/utilDictionary.h
Labels: build, ready-for-merge

#2598 Broken AL_USDMaya and AL_USDTransaction builds (AL)
  plugin/al/schemas/AL/usd/schemas/maya/tests/CMakeLists.txt
  plugin/al/usdtransaction/AL/usd/transaction/tests/CMakeLists.txt
Labels: build, ready-for-merge

#2626 MAYA-125364 - MayaUsd: Maya master blessing failing (Linux only)
  cmake/googletest.cmake
  cmake/googletest_download.txt.in
  cmake/googletest_src.txt.in
Labels: build, ready-for-merge

#2630 MAYA-121636 fix fixlevel check of parent test
  test/lib/ufe/testParentCmd.py
Labels: build, ready-for-merge

#2576 Hide orphaned pulled nodes on ancestor structure change.
  cmake/modules/FindUFE.cmake
  lib/mayaUsd/fileio/CMakeLists.txt
  lib/mayaUsd/fileio/orphanedNodesManager.cpp
  lib/mayaUsd/fileio/orphanedNodesManager.h
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/fileio/primUpdaterManager.h
  test/lib/mayaUsd/fileio/CMakeLists.txt
  test/lib/mayaUsd/fileio/testHideOrphanedNodes.py
  test/testSamples/hideOrphanedNodes/A.usda
  test/testSamples/hideOrphanedNodes/A_geom.usda
  test/testSamples/hideOrphanedNodes/A_payload.usda
  test/testSamples/hideOrphanedNodes/B.usda
  test/testSamples/hideOrphanedNodes/hideOrphanedNodes.usda
Labels: workflows, ready-for-merge

#2624 LOOKDEVX-761 | Defaults materials scope name to mtl and allows setting
  plugin/adsk/scripts/mayaUSDRegisterStrings.mel
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
  test/lib/CMakeLists.txt
  test/lib/testMayaUsdInteractiveMaterialsScopeName.py
Labels: adsk, ready-for-merge

#2629 MAYA-125364 - MayaUsd: Maya master blessing failing (Linux only)
  lib/mayaUsd/utils/hash.h
Labels: build

#2632 Fix for building with latest Maya PR and USD v21.8
  lib/mayaUsd/CMakeLists.txt
Labels: build, ready-for-merge

#2631 Disable edit as Maya for materials.
  lib/usd/translators/plugInfo.json
  lib/usd/translators/shading/CMakeLists.txt
  lib/usd/translators/shading/materialUpdater.cpp
  lib/usd/translators/shading/materialUpdater.h
  test/lib/mayaUsd/fileio/testEditAsMaya.py
Labels: ready-for-merge, materials

#2633 Fixes for building with gcc 11 (still using old ABI).
  cmake/googletest.cmake
  cmake/googletest_download.txt.in
  cmake/googletest_src.txt.in
  cmake/utils.cmake
  plugin/al/plugin/AL_USDMayaTestPlugin/AL/maya/test_EventHandler.cpp
Labels: build, ready-for-merge
