Repository Autodesk/maya-usd, pull requests merged in 2022-03, with the labels that each got.

#2145 MAYA-121882 Share the cached HdVP2TextureInfo between all materials so that isSRGB
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  lib/mayaUsd/render/vp2RenderDelegate/material.h
Labels: vp2renderdelegate, ready-for-merge

#2149 MAYA-121626 Automatically set the animation option
  lib/mayaUsd/commands/PullPushCommands.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/python/wrapPrimUpdaterManager.cpp
  lib/mayaUsd/python/wrapUtil.cpp
  lib/mayaUsd/resources/scripts/cacheToUsd.py
  lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
  lib/mayaUsd/resources/scripts/mayaUsdMergeToUSDOptions.py
  lib/mayaUsd/resources/scripts/mayaUsdOptions.py
  lib/mayaUsd/utils/util.cpp
  plugin/adsk/plugin/exportTranslator.cpp
  plugin/adsk/scripts/mayaUsdMenu.mel
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
  plugin/pxr/maya/lib/usdMaya/exportTranslator.cpp
  test/lib/mayaUsd/fileio/CMakeLists.txt
  test/lib/mayaUsd/fileio/testCustomRig.py
  test/lib/mayaUsd/fileio/testMayaUsdOptions.py
Labels: enhancement, pxr, adsk, core, ready-for-merge

#2151 MAYA-121937 - Renaming 2 prims w/illegal chars will crash Maya
  lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.py
  lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp
  test/lib/ufe/testRename.py
Labels: ufe-usd, ready-for-merge

#2156 MAYA-121781 support duplicate to USD non-root
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  test/lib/mayaUsd/fileio/testDuplicateAs.py
Labels: enhancement, ready-for-merge

#2161 MAYA-121808 Add curve filtering option in UI
  lib/mayaUsd/resources/scripts/cacheToUsd.py
  plugin/adsk/scripts/mayaUSDRegisterStrings.mel
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
  test/lib/usd/translators/testUsdExportNurbsCurve.py
Labels: import-export, ready-for-merge

#2165 MAYA-121534 - Export of texture and placement
  lib/mayaUsd/fileio/shading/shadingModeUseRegistry.cpp
  lib/mayaUsd/fileio/utils/shadingUtil.cpp
  lib/mayaUsd/fileio/utils/shadingUtil.h
  lib/mayaUsd/python/wrapPrimWriter.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/CMakeLists.txt
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/maya_surfaces.mtlx
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/maya_utilities.mtlx
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/usd_utilities.mtlx
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/usd_utilities_genglsl_impl.mtlx
  lib/usd/translators/shading/CMakeLists.txt
  lib/usd/translators/shading/mtlxBaseWriter.cpp
  lib/usd/translators/shading/mtlxBaseWriter.h
  lib/usd/translators/shading/mtlxFileTextureWriter.cpp
  lib/usd/translators/shading/mtlxImageReader.cpp
  lib/usd/translators/shading/mtlxPlace2dTextureWriter.cpp
  lib/usd/translators/shading/shadingTokens.h
  test/lib/mayaUsd/fileio/testShaderWriter.py
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/place2dTextureShowcase_Maya_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/place2dTextureShowcase_USD_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateMaterialX.py
  test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
  test/lib/usd/translators/testUsdExportMaterialX.py
  test/lib/usd/translators/testUsdExportMultiMaterial.py
  test/testSamples/MaterialX/MayaSurfaces.usda
  test/testSamples/MaterialX/MtlxUVStreamTest.usda
  test/testSamples/MaterialX/place2dTextureShowcase.ma
  test/testSamples/MaterialX/textures/Brazilian_rosewood_pxr128.png
  test/testSamples/MaterialX/textures/Mono.png
  test/testSamples/MaterialX/textures/MonoA.png
  test/testSamples/MaterialX/textures/RGB.png
  test/testSamples/MaterialX/textures/RGBA.png
  test/testSamples/MaterialX/textures/grid.png
  test/testSamples/MaterialX/textures/normalSpiral.png
  test/testSamples/MaterialX/textures/normalSpiralA.png
Labels: import-export, ready-for-merge, materials

#2158 MAYA-107839 [GitHub 800] USD: exporting the attached maya file using …
  lib/mayaUsd/fileio/writeJobContext.cpp
Labels: core, ready-for-merge

#2164 MAYA-121886 Merge-to USD options help
  lib/mayaUsd/resources/scripts/mayaUsdMergeToUSDOptions.py
Labels: requires maya, adsk, ready-for-merge

#2167 MAYA-120659 We created cmake variables which tell us if the API is present,
  lib/mayaUsd/CMakeLists.txt
Labels: build, ready-for-merge

#2166 MAYA-122014 support duplicate to Maya to non root
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/ufe/Utils.cpp
  lib/mayaUsd/ufe/Utils.h
  test/lib/mayaUsd/fileio/testDuplicateAs.py
Labels: enhancement, adsk, ready-for-merge

#2171 MAYA-110239 remove load / unload payload from AE
  plugin/adsk/scripts/AEmayaUsdProxyShapeBaseTemplate.mel
  plugin/adsk/scripts/mayaUSDRegisterStrings.mel
Labels: ready-for-merge

#2170 MAYA-121534 Import code for place2dTexture
  lib/mayaUsd/fileio/shaderReader.cpp
  lib/mayaUsd/fileio/shaderReader.h
  lib/mayaUsd/fileio/shaderReaderRegistry.cpp
  lib/mayaUsd/fileio/shading/shadingModePxrRis.cpp
  lib/mayaUsd/fileio/shading/shadingModeUseRegistry.cpp
  lib/usd/pxrUsdPreviewSurface/usdPreviewSurfaceReader.cpp
  lib/usd/translators/shading/CMakeLists.txt
  lib/usd/translators/shading/mtlxBaseReader.cpp
  lib/usd/translators/shading/mtlxBaseReader.h
  lib/usd/translators/shading/mtlxBaseWriter.cpp
  lib/usd/translators/shading/mtlxConverterReader.cpp
  lib/usd/translators/shading/mtlxFileTextureReader.cpp
  lib/usd/translators/shading/mtlxImageReader.cpp
  lib/usd/translators/shading/usdUVTextureReader.cpp
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/place2dTextureShowcase_Import_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/place2dTextureShowcase_Maya_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/place2dTextureShowcase_USD_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateMaterialX.py
  test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
  test/testSamples/MaterialX/place2dTextureShowcase.ma
Labels: import-export, ready-for-merge, materials

#2172 MAYA-121808 Fix the curve export tooltip
  plugin/adsk/scripts/mayaUSDRegisterStrings.mel
Labels: import-export

#2174 MAYA-121258 remove plugin menus
  plugin/adsk/scripts/mayaUsdMenu.mel
Labels: ready-for-merge

#2178 MAYA-121534 MaterialX image improvements
  lib/mayaUsd/fileio/utils/shadingUtil.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/CMakeLists.txt
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/maya_surfaces.mtlx
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_srgb_texture_to_aces_2065_1_color3.glsl
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_srgb_texture_to_aces_2065_1_color4.glsl
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_srgb_texture_to_acescg_color3.glsl
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_srgb_texture_to_acescg_color4.glsl
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_srgb_texture_to_lin_dci_p3_d65_color3.glsl
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_srgb_texture_to_lin_dci_p3_d65_color4.glsl
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_srgb_texture_to_linrec2020_color3.glsl
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx_srgb_texture_to_linrec2020_color4.glsl
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/usd_utilities.mtlx
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/usd_utilities_genglsl_impl.mtlx
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  lib/usd/translators/shading/mtlxFileTextureWriter.cpp
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/MayaSurfaces_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/MtlxUVStreamTest_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/place2dTextureShowcase_USD_render.png
Labels: vp2renderdelegate, ready-for-merge, materials

#2183 MAYA-122122 void crash when editing as maya
  lib/usd/ui/layerEditor/mayaSessionState.cpp
  lib/usd/ui/layerEditor/mayaSessionState.h
Labels: ready-for-merge

#2175 Locked attributes on Maya reference prim transform stand-in.
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/fileio/translators/translatorMayaReference.cpp
  lib/mayaUsd/fileio/translators/translatorUtil.cpp
  lib/mayaUsd/fileio/translators/translatorUtil.h
  lib/mayaUsd/python/CMakeLists.txt
  lib/mayaUsd/python/module.cpp
  lib/mayaUsd/python/wrapTranslatorUtil.cpp
  lib/mayaUsd/undo/OpUndoItems.h
  lib/mayaUsd/utils/editRouter.cpp
  lib/usd/translators/mayaReferenceReader.cpp
  lib/usd/translators/mayaReferenceUpdater.cpp
  lib/usd/translators/mayaReferenceUpdater.h
  test/lib/mayaUsd/fileio/testCacheToUsd.py
  test/lib/mayaUsd/fileio/testCustomRig.py
Labels: core

#2187 Add check in context ops to avoid Add Maya Reference on Maya referenc…
  lib/mayaUsd/ufe/UsdContextOps.cpp
Labels: workflows, outliner

#2186 MAYA-121877 cancel edit on maya ref under an xform
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/resources/scripts/mayaUsdUtils.py
Labels: core, workflows

#2157 Add glBindVertexArray to UsdMayaGLBatchRenderer::_TestIntersection.
  lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.cpp
Labels: ready-for-merge

#2220 Revert "MAYA-115146 As a user, I'd like my Maya Reference node to be named th…"
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/jobs/readJob.cpp
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/fileio/translators/translatorMayaReference.cpp
  lib/mayaUsd/fileio/translators/translatorMayaReference.h
  lib/mayaUsd/ufe/Utils.cpp
  plugin/al/translators/tests/testMayaRefStageA.usda
  plugin/al/translators/tests/testMayaRefStageB.usda
  plugin/al/translators/tests/testTranslators.py
  test/lib/CMakeLists.txt
Labels: ready-for-merge

#2227 Fix preflight test failures
  lib/usd/hdMaya/adapters/materialNetworkConverter.cpp
  test/lib/mayaUsd/render/mayaToHydra/MtohBasicRenderTest/cube_selected.png
  test/lib/mayaUsd/render/mayaToHydra/MtohBasicRenderTest/cube_unselected.png
  test/lib/mayaUsd/render/mayaToHydra/MtohBasicRenderTest/lambertDefaultMaterial/cube_selected.png
  test/lib/mayaUsd/render/mayaToHydra/MtohBasicRenderTest/lambertDefaultMaterial/cube_unselected.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_1.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_12.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_123.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_1234.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_123456.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_1235.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_3.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/instances_35.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_0.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_1.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_12.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_123.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_1234.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_123456.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_1235.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_3.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_35.png
  test/lib/mayaUsd/render/mayaToHydra/MtohVisibilityTest/cube_unselected.png
  test/lib/mayaUsd/render/mayaToHydra/MtohVisibilityTest/lambertDefaultMaterial/cube_unselected.png
  test/lib/mayaUsd/render/mayaToHydra/testMtohBasicRender.py
  test/lib/mayaUsd/render/mayaToHydra/testMtohDagChanges.py
  test/lib/mayaUsd/render/mayaToHydra/testMtohVisibility.py
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegatePerInstanceInheritedDataTest/baseline/basisCurveInstance_selected.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegatePerInstanceInheritedDataTest/baseline/basisCurveInstance_unselected.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegatePerInstanceInheritedDataTest/baseline/defaultMaterialBillboards_default.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegatePerInstanceInheritedDataTest/baseline/defaultMaterialBillboards_defaultSelected.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegatePerInstanceInheritedDataTest/baseline/lambertDefaultMaterial/basisCurveInstance_selected.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegatePerInstanceInheritedDataTest/baseline/lambertDefaultMaterial/basisCurveInstance_unselected.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegatePerInstanceInheritedDataTest/baseline/lambertDefaultMaterial/defaultMaterialBillboards_default.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegatePerInstanceInheritedDataTest/baseline/lambertDefaultMaterial/defaultMaterialBillboards_defaultSelected.png
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegatePerInstanceInheritedData.py
  test/testUtils/mtohUtils.py
Labels: ready-for-merge

#2230 MAYA-122502 When instance colors is nullptr don't get the length.
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
Labels: vp2renderdelegate, ready-for-merge
