Repository Autodesk/maya-usd, pull requests merged in 2022-02, with the labels that each got.

#2048 Rename "gulark" to "gulrak"
  CMakeLists.txt
  cmake/gulrak.cmake
  doc/CHANGELOG.md
Labels: build

#2050 Write Sparsely when exporting mesh orientation
  lib/mayaUsd/fileio/utils/meshWriteUtils.cpp
Labels: import-export

#2038 MAYA-121408 Trigger the populate selection when a new instancer is added
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegatePerInstanceInheritedDataTest/baseline/perInstanceInheritedData_ball_03_and_04_guide.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegatePerInstanceInheritedDataTest/baseline/perInstanceInheritedData_ball_03_guide.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegatePerInstanceInheritedDataTest/baseline/perInstanceInheritedData_ball_04_guide.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegatePerInstanceInheritedDataTest/baseline/perInstanceInheritedData_default_after_guide.png
Labels: vp2renderdelegate, ready-for-merge

#2054 Cache to USD dialog for Maya reference prim.
  lib/mayaUsd/fileio/fallbackPrimUpdater.cpp
  lib/mayaUsd/fileio/fallbackPrimUpdater.h
  lib/mayaUsd/fileio/primUpdater.cpp
  lib/mayaUsd/fileio/primUpdater.h
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/fileio/primUpdaterRegistry.cpp
  lib/mayaUsd/fileio/primUpdaterRegistry.h
  lib/mayaUsd/python/wrapPrimUpdater.cpp
  lib/mayaUsd/python/wrapUtil.cpp
  lib/mayaUsd/resources/icons/CMakeLists.txt
  lib/mayaUsd/resources/icons/cache_to_USD_100.png
  lib/mayaUsd/resources/icons/cache_to_USD_150.png
  lib/mayaUsd/resources/icons/cache_to_USD_200.png
  lib/mayaUsd/resources/scripts/CMakeLists.txt
  lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.mel
  lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.py
  lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.mel
  lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
  lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.mel
  lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
  lib/mayaUsd/resources/scripts/mayaUsdMayaReferenceUtils.py
  lib/mayaUsd/resources/scripts/mayaUsdMergeToUsd.py
  lib/mayaUsd/ufe/ProxyShapeHierarchy.cpp
  lib/mayaUsd/ufe/UsdPathMappingHandler.cpp
  lib/mayaUsd/utils/editRouter.cpp
  lib/mayaUsd/utils/editRouter.h
  lib/usd/translators/mayaReferenceUpdater.cpp
  lib/usd/translators/mayaReferenceUpdater.h
  plugin/adsk/scripts/AETemplateHelpers.py
  plugin/adsk/scripts/USDMenuProc.mel
  plugin/adsk/scripts/mayaUSDRegisterStrings.mel
  plugin/adsk/scripts/mayaUsdMenu.mel
  plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
  plugin/adsk/scripts/mayaUsd_layerEditorFileDialogs.mel
  plugin/adsk/scripts/mayaUsd_pluginUICreation.mel
  test/lib/mayaUsd/fileio/testAddMayaReference.py
  test/lib/mayaUsd/fileio/testCustomRig.py
  test/lib/mayaUsd/fileio/testPrimUpdater.py
Labels: ready-for-merge

#2053 MAYA-114898 fix merge UI option defaults.
  plugin/adsk/scripts/mayaUsdMenu.mel
Labels: ready-for-merge

#2056 MAYA-121099: Env vars for push/pull and mayaRef features
  lib/mayaUsd/ufe/UsdContextOps.cpp
  plugin/adsk/scripts/USDMenuProc.mel
Labels: enhancement

#1936 Medley of normals and a few other fixes
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Transform.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/Transform.h
  plugin/al/lib/AL_USDMaya/CMakeLists.txt
  plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/fileio/export_misc.cpp
  plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/test_DiffPrimVar.cpp
  plugin/al/plugin/AL_USDMayaTestPlugin/CMakeLists.txt
  plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_MeshTranslator.cpp
  plugin/al/schemas/AL/usd/schemas/maya/CMakeLists.txt
  plugin/al/schemas/AL/usd/schemas/mayatest/CMakeLists.txt
  plugin/al/translators/CommonTranslatorOptions.cpp
  plugin/al/translators/CommonTranslatorOptions.h
  plugin/al/translators/Mesh.cpp
  plugin/al/usdmayautils/AL/usdmaya/utils/DiffPrimVar.cpp
  plugin/al/usdmayautils/AL/usdmaya/utils/MeshUtils.cpp
  plugin/al/usdmayautils/AL/usdmaya/utils/MeshUtils.h
  plugin/al/usdtransaction/CMakeLists.txt
Labels: al

#2057 Add auto edit testing coverage to custom rig codeless schema test
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  test/lib/mayaUsd/fileio/testCustomRig.py
Labels: workflows, unit test

#2059 MAYA106075 - Introducing color cache to improve performance
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
Labels: ready-for-merge

#2062 MaterialX v1.38.3 and MayaUSD 0.16.0 updates
  doc/MaterialX.md
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
Labels: vp2renderdelegate

#2061 MAYA-114268 - Schema adaptor documentation
  lib/mayaUsd/fileio/doc/Managing_export_options_via_JobContext_in_Python.md
  lib/mayaUsd/fileio/doc/SchemaAPI_Import_Export_in_Python.md
  test/lib/mayaUsd/fileio/testSchemaApiAdaptor.py
Labels: documentation, import-export

#2064 Improve documentation discoverability
  README.md
  README_DOC.md
  doc/MaterialX.md
Labels: documentation

#2065 [al] Use quaternion form to compare rotation angles
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/BasicTransformationMatrix.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.h
  plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_TransformMatrix.cpp
Labels: al

#2068 Fix edit router parent test.
  lib/mayaUsd/python/wrapEditRouter.cpp
  lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
  lib/mayaUsd/ufe/Global.cpp
  lib/mayaUsd/ufe/UsdTransform3dUndoableCommands.cpp
  lib/mayaUsd/utils/editRouter.cpp
  lib/mayaUsd/utils/editRouter.h
  test/lib/ufe/testParentCmd.py
Labels: unit test, ready-for-merge

#2071 Revert "Skip updating MRenderItem's that we're not going to draw anyway."
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
Labels: vp2renderdelegate, ready-for-merge

#2078 Empty ignore files shouldn't match file in the repository
  .github/run-clang-format.py
Labels: build

#2075 [al] Removed tracking selectability and lock metadata
  plugin/al/lib/AL_USDMaya/AL/usdmaya/PluginRegister.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/SelectabilityDB.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/SelectabilityDB.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapeCommands.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeSelection.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/proxy/LockManager.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/proxy/LockManager.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/proxy/ProxyShapeMetaData.cpp
  plugin/al/lib/AL_USDMaya/CMakeLists.txt
  plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ProxyShapeSelectabilityDB.cpp
  plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_lockPrims.cpp
  plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/test_SelectabilityDB.cpp
  plugin/al/plugin/AL_USDMayaTestPlugin/CMakeLists.txt
Labels: al, ready-for-merge

#2081 Initial cache to USD test.
  lib/mayaUsd/resources/scripts/CMakeLists.txt
  lib/mayaUsd/resources/scripts/cacheToUsd.py
  lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
  test/lib/mayaUsd/fileio/CMakeLists.txt
  test/lib/mayaUsd/fileio/testAddMayaReference.py
  test/lib/mayaUsd/fileio/testCacheToUsd.py
  test/testUtils/mayaUtils.py
  test/testUtils/ufeUtils.py
Labels: unit test, ready-for-merge

#1895 Switch delete command behavior to delete prims
  cmake/modules/FindMaya.cmake
  lib/mayaUsd/CMakeLists.txt
  lib/mayaUsd/fileio/jobs/readJob.cpp
  lib/mayaUsd/ufe/StagesSubject.cpp
  lib/mayaUsd/ufe/UsdSceneItemOps.cpp
  lib/mayaUsd/ufe/UsdUndoDeleteCommand.cpp
  lib/mayaUsd/ufe/private/Utils.cpp
  lib/mayaUsd/ufe/private/Utils.h
  test/lib/mayaUsd/undo/testUsdUndoManager.py
  test/lib/ufe/CMakeLists.txt
  test/lib/ufe/testDeleteCmd.py
  test/lib/ufe/testDuplicateCmd.py
  test/lib/ufe/testLegacyDeleteCmd.py
  test/lib/ufe/testUIInfoHandler.py
Labels: ufe-usd, ready-for-merge

#2090 MAYA-121436 - No icon for Maya Reference in USD on Linux
  lib/mayaUsd/resources/icons/CMakeLists.txt
  lib/mayaUsd/resources/icons/out_USD_MayaReference_100.png
  lib/mayaUsd/resources/icons/out_USD_MayaReference_150.png
  lib/mayaUsd/resources/icons/out_USD_MayaReference_200.png
  lib/mayaUsd/ufe/UsdUIInfoHandler.cpp
Labels: bug

#2092 MAYA-115079: USD: MayaUsd test failures with USD built with AssetResolver 2
  lib/mayaUsd/fileio/translators/translatorMayaReference.cpp
  test/lib/mayaUsd/fileio/CMakeLists.txt
  test/lib/mayaUsd/fileio/testAddMayaReference.py
  test/lib/mayaUsd/fileio/testSchemaApiAdaptor.py
  test/lib/usd/translators/CMakeLists.txt
  test/lib/usd/translators/testUsdExportSchemaApi.py
Labels: pxr, core, unit test, ready-for-merge

#2060 MAYA-121514 fix leaking node due to undo items being left behind.
  lib/mayaUsd/listeners/notice.cpp
  lib/mayaUsd/listeners/notice.h
  lib/mayaUsd/undo/OpUndoItemList.cpp
  plugin/adsk/plugin/plugin.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/Global.cpp
  plugin/pxr/maya/plugin/pxrUsd/plugin.cpp
Labels: ready-for-merge

#2096 Remove/replace all UFE_PREVIEW_VERSION_NUM now that latest MayaPR has UFE v3
  cmake/modules/FindUFE.cmake
  lib/mayaUsd/ufe/ProxyShapeHierarchy.cpp
  lib/mayaUsd/ufe/ProxyShapeHierarchy.h
  lib/mayaUsd/ufe/UsdAttribute.cpp
  lib/mayaUsd/ufe/UsdAttribute.h
  lib/mayaUsd/ufe/UsdHierarchy.cpp
  lib/mayaUsd/ufe/UsdHierarchy.h
  lib/mayaUsd/ufe/UsdUndoCreateGroupCommand.cpp
  lib/mayaUsd/ufe/UsdUndoCreateGroupCommand.h
  test/lib/mayaUsd/fileio/CMakeLists.txt
  test/lib/mayaUsd/fileio/testDiscardEdits.py
  test/lib/mayaUsd/fileio/testEditAsMaya.py
  test/lib/mayaUsd/fileio/testMergeToUsd.py
  test/lib/ufe/testAttribute.py
  test/lib/ufe/testCamera.py
  test/lib/ufe/testComboCmd.py
  test/lib/ufe/testGroupCmd.py
  test/lib/ufe/testMoveCmd.py
  test/lib/ufe/testObject3d.py
  test/lib/ufe/testParentCmd.py
  test/lib/ufe/testRotatePivot.py
  test/lib/ufe/testSelection.py
  test/lib/ufe/testSelectionByArray.py
  test/lib/ufe/testUngroupCmd.py
  test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
  test/testUtils/mayaUtils.py
Labels: ufe, unit test, build, ready-for-merge

#2094 Fixed recursive calls to bound Python translators under Python 3
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/wrapTranslatorBase.cpp
  plugin/al/plugin/AL_USDMayaTestPlugin/py/testTranslators.py
Labels: al

#2100 Removed redundant code in proxy shape transform validation
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
Labels: al

#1980 Improved texture loading by running file reading asynchronously and only for active render purpose
  lib/mayaUsd/base/tokens.h
  lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  lib/mayaUsd/render/vp2RenderDelegate/material.h
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
  lib/mayaUsd/render/vp2RenderDelegate/render_delegate.cpp
  lib/mayaUsd/render/vp2RenderDelegate/render_delegate.h
  test/lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateTextureLoadingTest/baseline/TextureLoading_Proxy_Async.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateTextureLoadingTest/baseline/TextureLoading_Proxy_Sync.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateTextureLoadingTest/baseline/TextureLoading_Render_Async.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateTextureLoadingTest/baseline/TextureLoading_Render_Sync.png
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateTextureLoading.py
  test/testSamples/multipleMaterialsAssignment/MultipleMaterialsAssignment.usda
  test/testSamples/multipleMaterialsAssignment/blue.png
  test/testSamples/multipleMaterialsAssignment/proxy_blue.png
  test/testSamples/multipleMaterialsAssignment/proxy_green.png
  test/testSamples/multipleMaterialsAssignment/proxy_red.png
  test/testSamples/multipleMaterialsAssignment/render_blue.png
  test/testSamples/multipleMaterialsAssignment/render_green.png
  test/testSamples/multipleMaterialsAssignment/render_red.png
Labels: vp2renderdelegate, ready-for-merge

#2097 Pr/fix import of usd lux light prims
  lib/usd/translators/scopeReader.cpp
  test/lib/usd/translators/UsdImportLightTest/LightsTest.usda
  test/lib/usd/translators/UsdImportLightTest/LightsTest_2011.usda
  test/lib/usd/translators/UsdImportLightTest/LightsTest_2102.usda
  test/lib/usd/translators/UsdImportRfMLightTest/RfMLightsTest.usda
  test/lib/usd/translators/testUsdImportLight.py
  test/lib/usd/translators/testUsdImportRfMLight.py
Labels: import-export

#2104 MAYA-121600 - Refresh issue with deactivation of USD Prims
  lib/mayaUsd/ufe/StagesSubject.cpp
Labels: bug, ufe-usd, ready-for-merge

#2107 Varying display colour bug
  plugin/al/plugin/AL_USDMayaTestPlugin/py/testCommands.py
  plugin/al/plugin/AL_USDMayaTestPlugin/test_data/cube_displayColor.usda
  plugin/al/usdmayautils/AL/usdmaya/utils/MeshUtils.cpp
Labels: al

#2105 MAYA-114977 Updated documentation + unit test
  lib/mayaUsd/commands/Readme.md
  plugin/pxr/doc/README.md
  test/lib/usd/plugin/CMakeLists.txt
  test/lib/usd/plugin/plugInfoSiteSpecificConfig.json
  test/lib/usd/translators/CMakeLists.txt
  test/lib/usd/translators/testUsdImportExportSiteSpecificConfig.py
Labels: import-export, ready-for-merge

#2079 MAYA-121513 add undo support to add Maya reference
  lib/mayaUsd/fileio/primUpdater.cpp
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/fileio/translators/translatorMayaReference.cpp
  lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.py
  lib/mayaUsd/ufe/UsdContextOps.cpp
Labels: ready-for-merge

#2109 mayaUsdDuplicate selects duplicated object.
  lib/mayaUsd/commands/PullPushCommands.cpp
  lib/mayaUsd/undo/OpUndoItems.cpp
  lib/mayaUsd/undo/OpUndoItems.h
  test/lib/mayaUsd/fileio/testDuplicateAs.py
Labels: ready-for-merge

#2110 MAYA-121303 Setting the instance colors or transforms into Maya is expensive.
  lib/mayaUsd/render/vp2RenderDelegate/draw_item.h
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateSelection.py
Labels: vp2renderdelegate, ready-for-merge

#2125 Proper selection for edit as Maya, merge to USD, and discard Maya edits.
  lib/mayaUsd/commands/PullPushCommands.cpp
  lib/mayaUsd/commands/PullPushCommands.h
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/python/wrapPrimUpdaterManager.cpp
  lib/mayaUsd/undo/OpUndoItems.cpp
  lib/mayaUsd/undo/OpUndoItems.h
  test/lib/mayaUsd/fileio/testDiscardEdits.py
  test/lib/mayaUsd/fileio/testEditAsMaya.py
  test/lib/mayaUsd/fileio/testMergeToUsd.py
Labels: ready-for-merge

#2126 USD 22.03 integration: API change for MaterialX
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
Labels: vp2renderdelegate, ready-for-merge

#2131 MAYA-121813 change add Maya reference edit state default
  lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.mel
Labels: ready-for-merge

#2123 MAYA-121545 persist cache-to-USD options
  lib/mayaUsd/resources/scripts/cacheToUsd.py
  lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
  lib/mayaUsd/resources/scripts/mayaUsdOptions.py
  test/lib/mayaUsd/fileio/testCacheToUsd.py
Labels: ready-for-merge

#2122 MAYA-121625: cache to USD: take out 'Parent Scope' from options
  lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
  plugin/adsk/scripts/mayaUSDRegisterStrings.mel
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
Labels: workflows, ready-for-merge

#2106 Added export option to disable the model kinds processor
  lib/mayaUsd/commands/Readme.md
  lib/mayaUsd/commands/baseExportCommand.cpp
  lib/mayaUsd/commands/baseExportCommand.h
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/jobs/modelKindProcessor.cpp
Labels: workflows, ready-for-merge

#2132 MAYA-121814 change label to cancel maya ref edit
  lib/mayaUsd/resources/scripts/CMakeLists.txt
  lib/mayaUsd/resources/scripts/mayaUsdMergeToUsd.py
  lib/mayaUsd/resources/scripts/mayaUsdUtils.py
  plugin/adsk/scripts/mayaUSDRegisterStrings.mel
  plugin/adsk/scripts/mayaUsdMenu.mel
Labels: adsk, ready-for-merge

#2134 MAYA-120659 Get the display style of all viewports rather than just the current
  cmake/modules/FindMaya.cmake
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
Labels: vp2renderdelegate, ready-for-merge

#2129 MAYA-121357 Use the class specific namespace so we don't have to check Maya's version
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
Labels: vp2renderdelegate, ready-for-merge

#2138 MAYA-121287 Warn the user that mtoh is experimental.
  lib/mayaUsd/render/mayaToHydra/plugin.cpp
  lib/mayaUsd/render/mayaToHydra/utils.cpp
Labels: mtoh, ready-for-merge

#2141 MAYA-114593 preserve load state of prims
  lib/mayaUsd/ufe/UsdUndoDuplicateCommand.cpp
  lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp
  lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp
  lib/mayaUsd/utils/CMakeLists.txt
  lib/mayaUsd/utils/loadRules.cpp
  lib/mayaUsd/utils/loadRules.h
  test/lib/ufe/testGroupCmd.py
  test/lib/ufe/testRename.py
Labels: ready-for-merge

#2136 :bug: change _GetLocalTransformForDagPoseMember check from maya api version to diffrence_type iterator trait support, since 2019's MArrayIteratorTemplate.h has missing iterator traits.
  cmake/modules/FindMaya.cmake
  lib/usd/translators/jointWriter.cpp
Labels: build, ready-for-merge

#2146 Use MDagPath in lock undo item.
  lib/mayaUsd/undo/OpUndoItems.cpp
  lib/mayaUsd/undo/OpUndoItems.h
Labels: core, ready-for-merge

#2148 [al] Fixed incorrect export flag for translator in test plugin
  plugin/al/plugin/AL_USDMayaTestPlugin/py/testTranslators.py
Labels: al, ready-for-merge

#2143 MAYA-113944 If USD reports that the topology is dirty compare the
  lib/mayaUsd/render/vp2RenderDelegate/draw_item.h
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mesh.h
Labels: vp2renderdelegate, ready-for-merge

#2144 MAYA-121837: Maya Reference: Clean up 'Cache to USD' UI options
  lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
  lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
Labels: workflows, ready-for-merge

#2147 [al] Fixed a bug where bbox did not recalculate if prims visibilities changed
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
Labels: al, ready-for-merge
