Repository Autodesk/maya-usd, pull requests merged in 2022-05, with the labels that each got.

#2318 [al] Added support for importing animated bool and int type attributes
  plugin/al/usdmayautils/AL/usdmaya/utils/DgNodeHelper.cpp
  plugin/al/usdmayautils/AL/usdmaya/utils/DgNodeHelper.h
Labels: al, ready-for-merge

#2283 Added mesh export options to preserve and remap UV set names
  lib/mayaUsd/commands/Readme.md
  lib/mayaUsd/commands/baseExportCommand.cpp
  lib/mayaUsd/commands/baseExportCommand.h
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/utils/meshWriteUtils.cpp
  lib/mayaUsd/fileio/utils/meshWriteUtils.h
  lib/mayaUsd/python/wrapPrimWriter.cpp
  lib/usd/translators/meshWriter.cpp
  test/lib/usd/translators/UsdExportUVSetsFloatTest/UsdExportUVSetsTest_Float.ma
  test/lib/usd/translators/UsdExportUVSetsTest/UsdExportUVSetsTest.ma
  test/lib/usd/translators/testUsdExportUVSets.py
Labels: import-export, ready-for-merge

#2343 Updating changelog for v0.18.0
  doc/CHANGELOG.md
Labels: documentation, ready-for-merge

#2346 Update version to v0.19.0
  cmake/mayausd_version.info
Labels: build

#2250 [al] Add support for default rgba values and color threshold for exporting
  plugin/al/mayautils/AL/maya/utils/PluginTranslatorOptions.cpp
  plugin/al/mayautils/AL/maya/utils/PluginTranslatorOptions.h
  plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/test_DiffPrimVar.cpp
  plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_MeshTranslator.cpp
  plugin/al/translators/CommonTranslatorOptions.cpp
  plugin/al/translators/CommonTranslatorOptions.h
  plugin/al/translators/Mesh.cpp
  plugin/al/usdmayautils/AL/usdmaya/utils/DiffPrimVar.cpp
  plugin/al/usdmayautils/AL/usdmaya/utils/DiffPrimVar.h
  plugin/al/usdmayautils/AL/usdmaya/utils/MeshUtils.cpp
  plugin/al/usdmayautils/AL/usdmaya/utils/MeshUtils.h
Labels: al, ready-for-merge

#2316 MAYA-122362 cache-to-USD file type persistence
  lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
  lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.mel
  lib/mayaUsd/resources/scripts/mayaUsdUtils.py
  plugin/adsk/scripts/AETemplateHelpers.py
  plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
  plugin/adsk/scripts/mayaUsd_layerEditorFileDialogs.mel
Labels: good first issue, adsk, ready-for-merge

#2322 MAYA-122693 Use getMemberPaths for material export when it is available.
  cmake/modules/FindMaya.cmake
  lib/mayaUsd/CMakeLists.txt
  lib/mayaUsd/fileio/shading/shadingModeExporter.cpp
  lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp
Labels: requires maya, ready-for-merge, materials

#2328 MAYA-123100 - Suppress UFE-proxy lights in Maya Scene Delegate to avoid lights duplication
  lib/usd/hdMaya/delegates/sceneDelegate.cpp
Labels: mtoh, ready-for-merge

#2336 Avoid auto-edit check on invalid prim.
  lib/mayaUsd/fileio/primUpdaterManager.cpp
Labels: core, ready-for-merge

#2315 Ufe 0.4.8: Add classifications and metadata to def
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/UsdShaderAttributeDef.cpp
  lib/mayaUsd/ufe/UsdShaderAttributeDef.h
  lib/mayaUsd/ufe/UsdShaderNodeDef.cpp
  lib/mayaUsd/ufe/UsdShaderNodeDef.h
  lib/mayaUsd/ufe/UsdShaderNodeDefHandler.cpp
  lib/mayaUsd/ufe/UsdUndoCreateFromNodeDefCommand.cpp
  lib/mayaUsd/ufe/UsdUndoCreateFromNodeDefCommand.h
  test/lib/ufe/testContextOps.py
  test/lib/ufe/testShaderNodeDef.py
Labels: ufe, ready-for-merge

#2326 Updated NURBS curve export for widths and knots attributes
  lib/usd/translators/nurbsCurveWriter.cpp
  test/lib/usd/translators/testUsdExportNurbsCurve.py
Labels: import-export, ready-for-merge

#2331 MAYA-122541 fix hydra crash with skydome
  lib/mayaUsd/render/mayaToHydra/plugin.cpp
  lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
  lib/mayaUsd/ufe/Utils.cpp
Labels: bug, adsk, mtoh, ready-for-merge, crash

#2347 MAYA-122923 - Cache to USD dialog: empty space below options
  lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
Labels: adsk, ready-for-merge

#2348 MAYA-122928 - merge to USD dialog window height - cannot scroll down
  lib/mayaUsd/resources/scripts/mayaUsdMergeToUSDOptions.py
Labels: bug, ready-for-merge

#2308 Add namespace support to USD import file translators.
  plugin/adsk/plugin/importTranslator.h
  plugin/pxr/maya/lib/usdMaya/importTranslator.h
  test/lib/mayaUsd/fileio/CMakeLists.txt
  test/lib/mayaUsd/fileio/testImportWithNamespace.py
  test/lib/mayaUsd/fileio/testPrimReader.py
  test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
  test/lib/usd/translators/testUsdExportUVSetMappings.py
  test/lib/usd/translators/testUsdImportCustomConverter.template.py
  test/lib/usd/translators/testUsdImportDisplacement.py
  test/lib/usd/translators/testUsdImportMaterialX.py
  test/lib/usd/translators/testUsdImportPreviewSurface.py
  test/lib/usd/translators/testUsdImportUVSetMappings.py
Labels: pxr, adsk, ready-for-merge

#2337 MAYA-121681 allow creating prim in stronger layer
  lib/mayaUsd/ufe/UsdUndoAddNewPrimCommand.cpp
  lib/mayaUsd/ufe/private/Utils.cpp
  lib/mayaUsd/ufe/private/Utils.h
  test/lib/ufe/testGroupCmd.py
Labels: ufe-usd, ready-for-merge

#2314 Add SdfAssetPath support to renderGlobals
  lib/mayaUsd/render/mayaToHydra/renderGlobals.cpp
Labels: mtoh, ready-for-merge

#2334 MAYA-123013 obey file-format choice in layer editor
  lib/mayaUsd/nodes/layerManager.cpp
  lib/mayaUsd/utils/utilSerialization.cpp
  lib/mayaUsd/utils/utilSerialization.h
  lib/usd/translators/mayaReferenceUpdater.cpp
  lib/usd/ui/layerEditor/layerTreeItem.cpp
  lib/usd/ui/layerEditor/pathChecker.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/LayerCommands.cpp
Labels: core, ready-for-merge

#2327 Replace UsdGeomImageable primvar methods
  lib/mayaUsd/fileio/translators/translatorMaterial.cpp
  lib/mayaUsd/fileio/translators/translatorMesh.cpp
  lib/mayaUsd/fileio/utils/meshReadUtils.cpp
  lib/mayaUsd/fileio/utils/meshWriteUtils.cpp
  lib/mayaUsd/fileio/utils/writeUtil.cpp
  lib/usd/translators/meshWriter.cpp
  lib/usd/translators/nurbsSurfaceWriter.cpp
  plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_MeshTranslator.cpp
  plugin/al/usdmayautils/AL/usdmaya/utils/DiffPrimVar.cpp
  plugin/al/usdmayautils/AL/usdmaya/utils/MeshUtils.cpp
  plugin/al/usdmayautils/AL/usdmaya/utils/NurbsCurveUtils.cpp
  plugin/pxr/maya/plugin/pxrUsd/testenv/testPxrUsdAlembicChaser.py
  test/lib/usd/translators/testUsdExportColorSets.py
  test/lib/usd/translators/testUsdExportPref.py
  test/lib/usd/translators/testUsdExportUVSets.py
  test/lib/usd/translators/testUsdExportUserTaggedAttributes.py
Labels: build, ready-for-merge

#2324 Fixed up shading mode export options and display colour fallback behaviour
  lib/mayaUsd/commands/Readme.md
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
Labels: core, ready-for-merge

#2355 [al] Fixed issue that resync prim would cause irrelevant translators being removed
  plugin/al/lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapeCommands.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorContext.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorContext.h
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.h
  plugin/al/plugin/AL_USDMayaTestPlugin/py/testTranslators.py
  plugin/al/plugin/AL_USDMayaTestPlugin/test_data/resync_root.usda
  plugin/al/plugin/AL_USDMayaTestPlugin/test_data/resync_sublayer.usda
Labels: al, ready-for-merge

#2354 [al] Fixed incorrect computing local transformation matrix when exporting to USD
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/TransformTranslator.cpp
  plugin/al/plugin/AL_USDMayaTestPlugin/test_translators_TransformTranslator.cpp
Labels: al, ready-for-merge

#2349 MAYA-122888 - Lights outliner icon is not getting picked up
  cmake/test.cmake
  lib/mayaUsd/resources/icons/CMakeLists.txt
  lib/mayaUsd/resources/icons/out_USD_UsdLuxBoundableLightBase_100.png
  lib/mayaUsd/resources/icons/out_USD_UsdLuxBoundableLightBase_150.png
  lib/mayaUsd/resources/icons/out_USD_UsdLuxBoundableLightBase_200.png
  lib/mayaUsd/resources/icons/out_USD_UsdLuxNonboundableLightBase_100.png
  lib/mayaUsd/resources/icons/out_USD_UsdLuxNonboundableLightBase_150.png
  lib/mayaUsd/resources/icons/out_USD_UsdLuxNonboundableLightBase_200.png
  test/lib/ufe/CMakeLists.txt
  test/lib/ufe/testUIIcons.py
Labels: bug, ready-for-merge

#2358 MAYA-123016 catch exceptions during notifications
  lib/mayaUsd/ufe/StagesSubject.cpp
Labels: ready-for-merge

#2359 MAYA-122146 - Selecting a camera and framing it with "f" shows the origin instead of the camera
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/ufe/UsdLight.h
  lib/mayaUsd/ufe/UsdObject3d.cpp
  lib/mayaUsd/utils/util.cpp
  lib/mayaUsd/utils/util.h
Labels: ufe-usd, ready-for-merge

#2368 MAYA-123262 - Applied schemas in are broken in the AE template with U…
  lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
Labels: schema

#2363 MAYA-123332 allow topological modifications
  lib/mayaUsd/fileio/primUpdaterManager.cpp
Labels: core, ready-for-merge

#2364 LOOKDEVX-670 Improved USD type support
  lib/mayaUsd/ufe/UsdAttribute.cpp
  lib/mayaUsd/ufe/UsdAttribute.h
  lib/mayaUsd/ufe/UsdAttributes.cpp
  lib/mayaUsd/ufe/UsdShaderAttributeDef.cpp
  lib/mayaUsd/ufe/Utils.cpp
  test/lib/ufe/testAttribute.py
  test/lib/ufe/testShaderNodeDef.py
  test/testSamples/MaterialX/MtlxValueTypes.usda
  test/testUtils/testUtils.py
Labels: ufe, ufe-usd, ready-for-merge

#2369 MAYA-122048: Turn on MayaRef for users
  lib/mayaUsd/ufe/UsdContextOps.cpp
Labels: ufe-usd, ready-for-merge

#2361 Use UsdGeomPrimvarAPI in UVExport Tests
  test/lib/usd/translators/testUsdExportUVSets.py
Labels: unit test, ready-for-merge

#2277 MAYA-122628 The geomBindTransform should not be added to the mesh's transform.
  lib/mayaUsd/fileio/translators/translatorSkel.cpp
Labels: import-export, ready-for-merge

#2371 MAYA-123016 stage clear now resets the outliner
  lib/mayaUsd/utils/stageCache.cpp
Labels: core, ready-for-merge

#2374 MAYA-123419 add execution validation during pull/push
  lib/mayaUsd/commands/PullPushCommands.cpp
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/undo/OpUndoItems.cpp
  lib/mayaUsd/undo/OpUndoItems.h
Labels: core, ready-for-merge

#2350 T bailp/maya 115146/maya ref naming 2
  lib/mayaUsd/fileio/translators/translatorMayaReference.cpp
  lib/mayaUsd/fileio/translators/translatorMayaReference.h
  lib/mayaUsd/ufe/Utils.cpp
  plugin/al/translators/tests/testMayaRefStageA.usda
  plugin/al/translators/tests/testMayaRefStageB.usda
  plugin/al/translators/tests/testTranslators.py
  test/lib/CMakeLists.txt
Labels: core, ready-for-merge

#2384 Don't author the loadRules attribute for Pxr reference assemblies
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/nodes/proxyShapeBase.h
  plugin/pxr/maya/lib/usdMaya/proxyShape.cpp
Labels: pxr, core, ready-for-merge

#2388 Fix issues between two versions of standard_surface
  lib/mayaUsd/ufe/UsdShaderNodeDefHandler.cpp
Labels: ufe-usd, ready-for-merge

#2386 Boudrey/maya 123462/pullset remove
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/fileio/primUpdaterManager.h
Labels: core, ready-for-merge
