Repository Autodesk/maya-usd, pull requests merged in 2023-07, with the labels that each got.

#3192 LOOKDEVX-1605 - Fix inactive sourceColorSpace in UsdUVTexture
  lib/mayaUsd/render/MaterialXGenOgsXml/GlslOcioNodeImpl.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/GlslOcioNodeImpl.h
  lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.h
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  lib/usd/translators/shading/usdFileTextureWriter.cpp
  test/lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/OCIO_Explicit.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/OCIO_Integration.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/OCIO_Integration_enabled.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/OCIO_Integration_p3_d65.png
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateMaterialX.py
  test/testSamples/MaterialX/studio-config-v1.0.0_aces-v1.3_ocio-v2.0.ocio
Labels: vp2renderdelegate, ready-for-merge

#3187 EMSUSD-40 prevent editing instance proxy.
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  test/lib/mayaUsd/fileio/testEditAsMaya.py
Labels: adsk, ready-for-merge

#3193 MAYA-109 move custom image control code
  lib/mayaUsd/resources/ae/CMakeLists.txt
  lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
  lib/mayaUsd/resources/ae/usdschemabase/custom_image_control.py
Labels: adsk, ready-for-merge

#3194 LOOKDEVX-1592 - Clean up references, targets, and connections on delete
  lib/mayaUsd/ufe/UsdUndoDeleteCommand.cpp
  lib/usdUfe/utils/usdUtils.cpp
  lib/usdUfe/utils/usdUtils.h
  test/lib/ufe/testDeleteCmd.py
  test/testSamples/tree/treeMat.usda
Labels: ufe-usd, workflows, ready-for-merge

#3195 EMSUSD-249 Refactors relative path dialog options to be more clear
  plugin/adsk/scripts/mayaUSDRegisterStrings.py
  plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
Labels: adsk

#3203 merge v0.3.0 changes to release
  CMakeLists.txt
  build.py
  cmake/mayahydra_version.info
  cmake/modules/FindUSD.cmake
  cmake/test.cmake
  doc/build.md
  doc/codingGuidelines.md
  lib/mayaHydra/doc/mayaHydraBuild.md
  lib/mayaHydra/hydraExtensions/CMakeLists.txt
  lib/mayaHydra/hydraExtensions/adapters/meshAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/renderItemAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/renderItemAdapter.h
  lib/mayaHydra/hydraExtensions/delegates/delegateCtx.cpp
  lib/mayaHydra/hydraExtensions/delegates/sceneDelegate.cpp
  lib/mayaHydra/hydraExtensions/delegates/sceneDelegate.h
  lib/mayaHydra/hydraExtensions/sceneIndex/registration.cpp
  lib/mayaHydra/hydraExtensions/sceneIndex/registration.h
  lib/mayaHydra/hydraExtensions/utils.cpp
  lib/mayaHydra/hydraExtensions/utils.h
  lib/mayaHydra/plugin/renderOverride.h
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/main.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testDummy.cpp
  test/lib/mayaUsd/render/mayaToHydra/testMeshes.py
  test/lib/mayaUsd/render/mayaToHydra/testMtohBasicRender.py
  test/lib/mayaUsd/render/mayaToHydra/testMtohDagChanges.py
  test/lib/mayaUsd/render/mayaToHydra/testNamespaces.py
  test/lib/mayaUsd/render/mayaToHydra/testStageAddPrim.py
  test/lib/mayaUsd/render/mayaToHydra/testVisibility.py
  test/testUtils/fixturesUtils.py
  test/testUtils/imageUtils.py
  test/testUtils/mtohUtils.py
Labels: mayaHydra

#3196 EMSUSD-251 - Release all refs held by session state on reset
  lib/usd/ui/layerEditor/mayaLayerEditorWindow.cpp
Labels: bug, ready-for-merge

#3207 Proxy shape listener nodes should not be persisted
  lib/mayaUsd/nodes/proxyShapeListenerBase.cpp
Labels: proxy, ready-for-merge

#3164 Maya-128422 Override PrimReader
  lib/mayaUsd/fileio/jobs/readJob.cpp
  lib/mayaUsd/fileio/primReader.cpp
  lib/mayaUsd/fileio/primReader.h
  lib/mayaUsd/fileio/primReaderRegistry.cpp
  lib/mayaUsd/fileio/primReaderRegistry.h
  lib/mayaUsd/fileio/primUpdater.cpp
  lib/mayaUsd/fileio/shaderReader.cpp
  lib/mayaUsd/fileio/shaderReader.h
  lib/mayaUsd/fileio/shaderReaderRegistry.cpp
  lib/mayaUsd/fileio/shaderReaderRegistry.h
  lib/mayaUsd/fileio/shading/symmetricShaderReader.cpp
  lib/mayaUsd/python/wrapPrimReader.cpp
  lib/usd/translators/shading/mtlxSymmetricShaderReader.cpp
  lib/usd/translators/shading/usdBlinnReader.cpp
  plugin/pxr/maya/lib/usdMaya/readJob_ImportWithProxies.cpp
  test/lib/mayaUsd/fileio/testShaderReader.py
Labels: adsk, import-export, ready-for-merge

#3198 EMSUSD-190 fix for lights after edit-as-Maya
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/ufe/ProxyShapeHierarchy.cpp
Labels: workflows, ready-for-merge

#3210 Reduce the reference warning
  lib/usdUfe/ufe/UsdUndoAddRefOrPayloadCommand.cpp
Labels: workflows, ready-for-merge

#3214 Referenced shader attributes issue
  lib/mayaUsd/utils/util.cpp
  test/lib/usd/translators/CMakeLists.txt
  test/lib/usd/translators/testUsdExport8BitNormalMap.py
Labels: import-export, ready-for-merge

#3211 Use the updated HW Token in MaterialX 1.38.7
  lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
Labels: build, ready-for-merge

#3215 EMSUSD-189 fix undo of the stage creation command
  lib/mayaUsd/ufe/UsdUndoCreateStageWithNewLayerCommand.cpp
  lib/mayaUsd/ufe/UsdUndoCreateStageWithNewLayerCommand.h
  test/lib/testMayaUsdCreateStageCommands.py
Labels: ufe-usd, ready-for-merge

#3202 EMSUSD-248 fix lost notification listeners
  lib/mayaUsd/ufe/MayaStagesSubject.cpp
  lib/mayaUsd/ufe/MayaStagesSubject.h
  lib/usd/ui/layerEditor/mayaLayerEditorWindow.cpp
Labels: bug, adsk, ready-for-merge

#3220 Use Pixar's directive for namespacing
  lib/usdUfe/ufe/UsdUndoAddRefOrPayloadCommand.cpp
Labels: build, ready-for-merge

#3221 EMS-262 fix link betwwen documents
  doc/EditRouting.md
Labels: documentation, ready-for-merge

#3213 EMSUSD-253 build the layer manager model contents when created
  lib/usd/ui/layerEditor/layerTreeModel.cpp
Labels: bug, adsk, ready-for-merge

#3223 EMSUSD-92 - Ability to exclude primvars with specific Namespace
  lib/mayaUsd/commands/baseImportCommand.cpp
  lib/mayaUsd/commands/baseImportCommand.h
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/primReaderArgs.cpp
  lib/mayaUsd/fileio/primReaderArgs.h
  lib/mayaUsd/fileio/utils/meshReadUtils.cpp
  lib/mayaUsd/fileio/utils/meshReadUtils.h
  lib/mayaUsd/python/wrapPrimReader.cpp
  lib/usd/translators/meshReader.cpp
  test/lib/usd/translators/UsdImportColorSetsTest/UsdImportColorSetsTest.usda
  test/lib/usd/translators/testUsdImportColorSets.py
Labels: import-export, ready-for-merge

#3230 Include pxr header
  lib/mayaUsd/base/api.h
Labels: build, ready-for-merge

#3231 EMSUSD-261 fix root layer attribute in AE
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  plugin/adsk/scripts/AEmayaUsdProxyShapeBaseTemplate.mel
Labels: bug, adsk, ready-for-merge

#3222 EMSUSD-255 Fixes an issue in Layer Editor where Save All icon was not functioning properly.
  lib/usd/ui/layerEditor/saveLayersDialog.cpp
  lib/usd/ui/layerEditor/saveLayersDialog.h
Labels: bug, adsk, ready-for-merge

#3232 LOOKDEVX-1547 - Allow introspecting UsdAttribute UFE class
  lib/mayaUsd/ufe/UsdAttribute.h
  lib/mayaUsd/ufe/UsdShaderAttributeHolder.cpp
  test/lib/ufe/testAttribute.py
Labels: ufe-usd, ready-for-merge

#3235 Return Prim Readers that are loaded in Find
  lib/mayaUsd/fileio/primReaderRegistry.cpp
Labels: workflows, ready-for-merge

#3227 EMSUSD-189 detect invalid use of undo item
  CMakeLists.txt
  lib/mayaUsd/CMakeLists.txt
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/nodes/layerManager.cpp
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/python/wrapOpUndoItem.cpp
  lib/mayaUsd/python/wrapReadUtil.cpp
  lib/mayaUsd/undo/CMakeLists.txt
  lib/mayaUsd/undo/OpUndoItemList.h
  lib/mayaUsd/undo/OpUndoItemMuting.cpp
  lib/mayaUsd/undo/OpUndoItemMuting.h
  lib/mayaUsd/undo/OpUndoItemRecorder.h
  lib/mayaUsd/undo/OpUndoItemValidator.cpp
  lib/mayaUsd/undo/OpUndoItemValidator.h
  lib/mayaUsd/undo/OpUndoItems.cpp
  lib/mayaUsd/undo/OpUndoItems.h
  test/lib/mayaUsd/fileio/testCustomRig.py
  test/lib/mayaUsd/fileio/testDiscardEdits.py
  test/lib/mayaUsd/fileio/testHideOrphanedNodes.py
  test/lib/mayaUsd/undo/CMakeLists.txt
  test/lib/mayaUsd/undo/testOpUndoItem.py
  test/lib/mayaUsd/undo/testOpUndoItemList.py
  test/lib/ufe/testContextOps.py
Labels: enhancement, adsk, ready-for-merge

#3241 LOOKDEVX-1688 - Fix extra Arnold refresh when moving nodes
  lib/mayaUsd/listeners/stageNoticeListener.cpp
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/nodes/proxyShapeBase.h
  test/lib/ufe/testContextOps.py
Labels: arnold, ready-for-merge

#2957 [al]Updating AL USDMaya's NurbsCurve static import export to use USD's curve spec
  plugin/al/translators/NurbsCurve.cpp
  plugin/al/translators/tests/testTranslators.py
  plugin/al/usdmayautils/AL/usdmaya/utils/NurbsCurveUtils.cpp
Labels: al, ready-for-merge

#3233 EMSUSD-77 - Newly created USD Lights can't cast shadows
  lib/mayaUsd/ufe/UsdLight.cpp
Labels: ufe-usd, ready-for-merge

#3189 EMSUSD-101 Override primWriter
  lib/mayaUsd/fileio/primWriter.h
  lib/mayaUsd/fileio/primWriterRegistry.cpp
  lib/mayaUsd/fileio/primWriterRegistry.h
  lib/mayaUsd/fileio/shaderWriter.h
  lib/mayaUsd/fileio/shaderWriterRegistry.cpp
  lib/mayaUsd/fileio/shaderWriterRegistry.h
  lib/mayaUsd/fileio/shading/symmetricShaderWriter.cpp
  lib/mayaUsd/fileio/utils/adaptor.cpp
  lib/mayaUsd/fileio/writeJobContext.cpp
  lib/mayaUsd/fileio/writeJobContext.h
  lib/mayaUsd/python/wrapPrimWriter.cpp
  lib/usd/pxrUsdPreviewSurface/usdPreviewSurfaceWriter.cpp
  lib/usd/translators/shading/mtlxBaseWriter.cpp
  lib/usd/translators/shading/mtlxSymmetricShaderWriter.cpp
  lib/usd/translators/shading/usdDisplacementShaderWriter.cpp
  lib/usd/translators/shading/usdFileTextureWriter.cpp
  lib/usd/translators/shading/usdMaterialWriter.cpp
  test/lib/mayaUsd/fileio/testPrimWriter.py
  test/lib/mayaUsd/fileio/testShaderWriter.py
Labels: adsk, import-export, ready-for-merge

#3212 Use new HdFlattenedDataSourceProvider
  lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
Labels: adsk, ready-for-merge

#3248 MAYA-128473 - Move UFE to its own Project - Part 10
  lib/mayaUsd/commands/layerEditorCommand.cpp
  lib/mayaUsd/python/CMakeLists.txt
  lib/mayaUsd/python/module.cpp
  lib/mayaUsd/python/wrapCommands.cpp
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/Global.cpp
  lib/mayaUsd/ufe/MayaStagesSubject.cpp
  lib/mayaUsd/ufe/MayaStagesSubject.h
  lib/mayaUsd/ufe/MayaUsdContextOps.cpp
  lib/mayaUsd/ufe/MayaUsdContextOps.h
  lib/mayaUsd/ufe/MayaUsdContextOpsHandler.cpp
  lib/mayaUsd/ufe/MayaUsdContextOpsHandler.h
  lib/mayaUsd/ufe/ProxyShapeContextOpsHandler.cpp
  lib/mayaUsd/ufe/Utils.cpp
  lib/mayaUsd/ufe/Utils.h
  lib/mayaUsd/utils/CMakeLists.txt
  lib/mayaUsd/utils/loadRules.h
  lib/mayaUsd/utils/loadRulesAttribute.cpp
  lib/usd/translators/mayaReferenceUpdater.cpp
  lib/usdUfe/python/wrapCommands.cpp
  lib/usdUfe/ufe/CMakeLists.txt
  lib/usdUfe/ufe/Global.cpp
  lib/usdUfe/ufe/Global.h
  lib/usdUfe/ufe/SetVariantSelectionCommand.cpp
  lib/usdUfe/ufe/SetVariantSelectionCommand.h
  lib/usdUfe/ufe/StagesSubject.cpp
  lib/usdUfe/ufe/StagesSubject.h
  lib/usdUfe/ufe/UsdContextOps.cpp
  lib/usdUfe/ufe/UsdContextOps.h
  lib/usdUfe/ufe/UsdContextOpsHandler.cpp
  lib/usdUfe/ufe/UsdContextOpsHandler.h
  lib/usdUfe/ufe/UsdUndoPayloadCommand.cpp
  lib/usdUfe/ufe/UsdUndoPayloadCommand.h
  lib/usdUfe/ufe/Utils.cpp
  lib/usdUfe/ufe/Utils.h
  lib/usdUfe/utils/CMakeLists.txt
  lib/usdUfe/utils/loadRules.h
  lib/usdUfe/utils/loadRulesText.cpp
  test/lib/mayaUsd/utils/testLoadRules.cpp
  test/lib/ufe/testPayloadCommands.py
Labels: ufe, ready-for-merge

#3247 Add excludePrimvarNamespace flag to readme
  lib/mayaUsd/commands/Readme.md
Labels: documentation, ready-for-merge

#3236 EMSUSD-256 allow Maya ref to be relative to the layer.
  lib/mayaUsd/resources/scripts/mayaUsdAddMayaReference.mel
  lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.mel
  lib/mayaUsd/ufe/MayaUsdContextOps.cpp
  plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
Labels: enhancement, adsk, ready-for-merge

#3249 EMSUSD-278 - Embed import options in subheadings
  plugin/adsk/scripts/mayaUSDRegisterStrings.mel
  plugin/adsk/scripts/mayaUsdTranslatorImport.mel
Labels: adsk, ready-for-merge
