Repository Autodesk/maya-usd, pull requests merged in 2023-05, with the labels that each got.

#3050 Fix USD 23.02 build by adding mutex include
  lib/mayaUsd/listeners/stageNoticeListener.cpp
Labels: build, ready-for-merge

#3044 Fix broken UDIMs in VP2 and add unit test
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/ShadedPyramid_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/grid_with_udims_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateNoMaterialXTest/baseline/ShadedPyramid_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateNoMaterialXTest/baseline/grid_with_udims_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateMaterialX.py
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateNoMaterialX.py
  test/testSamples/MaterialX/grid_with_udims.usda
  test/testSamples/MaterialX/textures/diffuse.1001.jpg
  test/testSamples/MaterialX/textures/diffuse.1002.jpg
  test/testSamples/MaterialX/textures/diffuse.1003.jpg
  test/testSamples/MaterialX/textures/diffuse.1004.jpg
  test/testSamples/MaterialX/textures/diffuse.1005.jpg
  test/testSamples/MaterialX/textures/diffuse.1006.jpg
  test/testSamples/MaterialX/textures/diffuse.1010.jpg
  test/testSamples/MaterialX/textures/diffuse.1022.jpg
Labels: vp2renderdelegate, ready-for-merge

#3049 MAYA-129067 correct layer order in batch save dialog
  lib/mayaUsd/utils/utilSerialization.cpp
Labels: enhancement, adsk, ready-for-merge

#3057 MAYA-129155 fix shiboken crash
  plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
Labels: ready-for-merge

#3052 MAYA-128363 pin stage in layer editor
  lib/mayaUsd/base/tokens.h
  lib/usd/ui/layerEditor/layerEditorWidget.cpp
  lib/usd/ui/layerEditor/qtUtils.cpp
  lib/usd/ui/layerEditor/qtUtils.h
  lib/usd/ui/layerEditor/resources.qrc
  lib/usd/ui/layerEditor/resources/pin_off_100.png
  lib/usd/ui/layerEditor/resources/pin_off_150.png
  lib/usd/ui/layerEditor/resources/pin_off_200.png
  lib/usd/ui/layerEditor/resources/pin_off_hover_100.png
  lib/usd/ui/layerEditor/resources/pin_off_hover_150.png
  lib/usd/ui/layerEditor/resources/pin_off_hover_200.png
  lib/usd/ui/layerEditor/resources/pin_on_100.png
  lib/usd/ui/layerEditor/resources/pin_on_150.png
  lib/usd/ui/layerEditor/resources/pin_on_200.png
  lib/usd/ui/layerEditor/resources/pin_on_hover_100.png
  lib/usd/ui/layerEditor/resources/pin_on_hover_150.png
  lib/usd/ui/layerEditor/resources/pin_on_hover_200.png
  lib/usd/ui/layerEditor/stageSelectorWidget.cpp
  lib/usd/ui/layerEditor/stageSelectorWidget.h
  lib/usd/ui/layerEditor/stringResources.h
Labels: enhancement, adsk, ready-for-merge

#3042 MAYA-128783 - Material api: hasMaterial implementation
  lib/mayaUsd/ufe/UsdMaterial.cpp
  lib/mayaUsd/ufe/UsdMaterial.h
  test/lib/ufe/testMaterial.py
Labels: ready-for-merge, materials

#3065 MAYA-129169 improve the behavior of duplication vs payload
  lib/usd/utils/util.cpp
  lib/usd/utils/util.h
  test/lib/ufe/testDuplicateCmd.py
  test/testSamples/payload/FlowerPot.geom.usd
  test/testSamples/payload/FlowerPot.usda
  test/testSamples/payload/FlowerPot_payload.usda
Labels: workflows, ready-for-merge

#3064 Update FindUSD.cmake for USD version patch
  cmake/modules/FindUSD.cmake
Labels: build, ready-for-merge

#3063 v0.2.0 mayaHydra changes (#421)
  CMakeLists.txt
  cmake/mayahydra_version.info
  cmake/modules/FindMaya.cmake
  doc/codingGuidelines.md
  lib/mayaHydra/CMakeLists.txt
  lib/mayaHydra/README.md
  lib/mayaHydra/doc/mayaHydraBuild.md
  lib/mayaHydra/doc/mayaHydraSelection.md
  lib/mayaHydra/hydraExtensions/CMakeLists.txt
  lib/mayaHydra/hydraExtensions/adapters/renderItemAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/renderItemAdapter.h
  lib/mayaHydra/hydraExtensions/delegates/delegate.h
  lib/mayaHydra/hydraExtensions/delegates/delegateCtx.cpp
  lib/mayaHydra/hydraExtensions/delegates/delegateCtx.h
  lib/mayaHydra/hydraExtensions/delegates/sceneDelegate.cpp
  lib/mayaHydra/hydraExtensions/delegates/sceneDelegate.h
  lib/mayaHydra/hydraExtensions/mayaHydra.h.src
  lib/mayaHydra/hydraExtensions/sceneIndex/registration.cpp
  lib/mayaHydra/hydraExtensions/sceneIndex/registration.h
  lib/mayaHydra/hydraExtensions/utils.cpp
  lib/mayaHydra/hydraExtensions/utils.h
  lib/mayaHydra/plugin/CMakeLists.txt
  lib/mayaHydra/plugin/renderOverride.cpp
  lib/mayaHydra/plugin/renderOverride.h
  lib/mayaHydra/ufeExtensions/CMakeLists.txt
  lib/mayaHydra/ufeExtensions/Global.cpp
  lib/mayaHydra/ufeExtensions/Global.h
  lib/mayaHydra/ufeExtensions/api.h
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/MtohVisibilityTest/cube_unselected.png
  test/lib/mayaUsd/render/mayaToHydra/MtohVisibilityTest/nothing.png
  test/lib/mayaUsd/render/mayaToHydra/VisibilityTest/cube_unselected.png
  test/lib/mayaUsd/render/mayaToHydra/VisibilityTest/lambertDefaultMaterial/cube_unselected.png
  test/lib/mayaUsd/render/mayaToHydra/VisibilityTest/nothing.png
  test/lib/mayaUsd/render/mayaToHydra/testMeshes.py
  test/lib/mayaUsd/render/mayaToHydra/testVisibility.py
  test/testUtils/mayaUtils.py
  test/testUtils/mtohUtils.py
  test/testUtils/testUtils.py
Labels: ready-for-merge, mayaHydra

#3074 clang-format on repo after preflight system broken
  lib/usd/utils/util.cpp
  lib/usd/utils/util.h
Labels: build, ready-for-merge

#3069 MAYA-129047 allow editing prims directly under the stage
  lib/mayaUsd/nodes/proxyAccessor.cpp
  lib/mayaUsd/nodes/proxyAccessor.h
  lib/mayaUsd/nodes/proxyAccessor.py
Labels: bug, adsk, proxy, ready-for-merge

#3068 Feldstj/lookdevx 861/ufe master enums
  cmake/modules/FindUFE.cmake
  lib/mayaUsd/resources/ae/CMakeLists.txt
  lib/mayaUsd/resources/ae/__init__.py
  lib/mayaUsd/resources/ae/usdschemabase/__init__.py
  lib/mayaUsd/resources/ae/usdschemabase/custom_enum_control.py
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/UsdAttributes.cpp
  lib/mayaUsd/ufe/UsdAttributes.h
  lib/mayaUsd/ufe/UsdShaderAttributeDef.h
  test/lib/ufe/CMakeLists.txt
  test/lib/ufe/testAttribute.py
  test/testSamples/MaterialX/int_enum.usda
Labels: ufe-usd, ready-for-merge

#3073 MAYA-129186 clearer layer file names
  lib/mayaUsd/nodes/proxyAccessor.cpp
  lib/mayaUsd/utils/utilFileSystem.cpp
  lib/mayaUsd/utils/utilFileSystem.h
  lib/mayaUsd/utils/utilSerialization.cpp
  lib/mayaUsd/utils/utilSerialization.h
  lib/usd/ui/layerEditor/saveLayersDialog.cpp
  test/lib/mayaUsd/utils/CMakeLists.txt
  test/lib/mayaUsd/utils/testUtilsFileSystem.cpp
Labels: adsk, ready-for-merge

#3080 MAYA-129332 fix batch saving of layers
  lib/mayaUsd/utils/utilSerialization.cpp
  lib/usd/ui/layerEditor/saveLayersDialog.cpp
Labels: bug, adsk, ready-for-merge, regression

#3046 Use Hd_VertexAdjacency API directly
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
  lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.cpp
Labels: vp2renderdelegate, ready-for-merge

#3055 USD 23.5 compatibility: Fix USD version check
  lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
Labels: build, ready-for-merge

#3056 MAYA-129061 - Refactor material commands.
  lib/mayaUsd/ufe/UsdShaderNodeDef.cpp
  lib/mayaUsd/ufe/UsdUndoAddNewPrimCommand.cpp
  lib/mayaUsd/ufe/UsdUndoAddNewPrimCommand.h
  lib/mayaUsd/ufe/UsdUndoMaterialCommands.cpp
  lib/mayaUsd/ufe/UsdUndoMaterialCommands.h
Labels: ufe-usd, ready-for-merge

#3071 MAYA-128594 - Imported displayOpacity are not interpreted correctly
  lib/usd/translators/meshWriter.cpp
Labels: import-export, ready-for-merge

#3083 MAYA-129132 - As a user, I'd like my relative USD root file to appear as relative before my scene file is saved
  lib/usd/ui/layerEditor/saveLayersDialog.cpp
Labels: enhancement, ready-for-merge

#3085 MAYA-129295 prevent primInfo errors
  lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
Labels: bug, vp2renderdelegate, ready-for-merge

#3089 Update include paths for Hd files that have moved
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
Labels: build, ready-for-merge

#3090 Fix out-of-date UsdSkel assets
  test/lib/usd/translators/UsdImportSkeleton/skelCube.usda
Labels: unit test, ready-for-merge

#3092 MAYA-129309 save and restore selected stage
  lib/mayaUsd/nodes/layerManager.cpp
  lib/mayaUsd/nodes/layerManager.h
  lib/usd/ui/layerEditor/mayaSessionState.cpp
  lib/usd/ui/layerEditor/mayaSessionState.h
  lib/usd/ui/layerEditor/stageSelectorWidget.cpp
Labels: adsk, ready-for-merge

#3093 MAYA-128939 remove error message on deleting a stage
  lib/mayaUsd/ufe/UsdStageMap.cpp
Labels: ufe-usd, ready-for-merge

#3095 MAYA-126736 remove duplicate for Maya Ref
  lib/mayaUsd/ufe/UsdContextOps.cpp
  plugin/adsk/scripts/USDMenuProc.mel
Labels: adsk, ready-for-merge

#3100 Add missing ARCHIVE DESTINATION
  lib/usd/utils/CMakeLists.txt
Labels: build, ready-for-merge

#3099 MAYA-129420 - Fix a bug where `UsdUINodeGraphNode::hasPosOrSize()` returned the wrong value.
  lib/mayaUsd/ufe/UsdUINodeGraphNode.cpp
Labels: bug, ufe-usd, ready-for-merge

#3103 Update EditRouting.md
  doc/EditRouting.md
Labels: documentation, ready-for-merge

#3104 MAYA-129141 - As a user, I'd like to set my anonymous layers as relative in Bulk Save's 'Save As' dialog
  lib/mayaUsd/utils/utilFileSystem.cpp
  lib/mayaUsd/utils/utilFileSystem.h
  lib/mayaUsd/utils/utilSerialization.cpp
  lib/mayaUsd/utils/utilSerialization.h
  lib/usd/ui/layerEditor/saveLayersDialog.cpp
  lib/usd/ui/layerEditor/saveLayersDialog.h
  plugin/adsk/scripts/mayaUsd_layerEditorFileDialogs.mel
Labels: enhancement, ready-for-merge

#3098 Use new UsdPrimDefintionAPI with latest USD
  lib/mayaUsd/fileio/schemaApiAdaptor.cpp
  lib/mayaUsd/fileio/schemaApiAdaptor.h
  lib/mayaUsd/fileio/utils/adaptor.cpp
  lib/mayaUsd/fileio/utils/adaptor.h
  lib/mayaUsd/fileio/utils/writeUtil.cpp
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/python/wrapAdaptor.cpp
  lib/mayaUsd/ufe/UsdAttributeHolder.cpp
  lib/mayaUsd/ufe/Utils.cpp
  plugin/al/plugin/AL_USDMayaTestPlugin/AL/usdmaya/fileio/export_misc.cpp
  test/lib/usd/translators/testUsdMayaAdaptor.py
Labels: ufe-usd, ready-for-merge

#3105 Update create_asset.py
  plugin/al/tutorials/endToEndMaya/scripts/create_asset.py
Labels: al, ready-for-merge

#3106 Update create_shot.py
  plugin/al/tutorials/endToEndMaya/scripts/create_shot.py
Labels: bug, ready-for-merge

#3110 MAYA-128599 fixing pivot command
  doc/USD Transforms Stack.md
  doc/USD Transforms Stack.pdf
  lib/mayaUsd/fileio/utils/xformStack.cpp
  lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
  lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.h
  lib/usd/ui/layerEditor/mayaSessionState.cpp
  test/lib/mayaUsd/fileio/utils/testXformStack.py
  test/lib/ufe/CMakeLists.txt
  test/lib/ufe/testCenterPivot.py
  test/lib/ufe/testComboCmd.py
  test/lib/ufe/testTransform3dChainOfResponsibility.py
  test/testSamples/instancer_pivot/pivot.usda
Labels: bug, adsk, ready-for-merge

#3118 MAYA-129268: Update Readme.md
  lib/mayaUsd/commands/Readme.md
Labels: documentation, ready-for-merge

#3121 LOOKDEVX-1428 - Adding missing export symbol to UsdAttributesHandler
  lib/mayaUsd/ufe/UsdAttributesHandler.h
Labels: ufe-usd, ready-for-merge

#3124 MAYA-000000 quick fix for conversion of rotations
  lib/mayaUsd/ufe/RotationUtils.h
Labels: ufe-usd, ready-for-merge

#3127 Fix tests to write output in testing temp dir (not source tree).
  plugin/al/plugin/AL_USDMayaTestPlugin/py/testProxyShape.py
  test/lib/usd/translators/testUsdImportEulerFilter.py
Labels: unit test, ready-for-merge

#3045 MAYA-129059 - Add command to create stages.
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/UsdUndoCreateStageWithNewLayerCommand.cpp
  lib/mayaUsd/ufe/UsdUndoCreateStageWithNewLayerCommand.h
  lib/mayaUsd/ufe/wrapUtils.cpp
  plugin/adsk/scripts/mayaUsd_createStageWithNewLayer.py
  test/lib/ufe/testPythonWrappers.py
Labels: adsk, ufe-usd, ready-for-merge

#3120 HYDRA-178 : Fix geom instances being at the wrong place when using ma…
  lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
  lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.h
Labels: core, ready-for-merge

#3130 MAYA-129309 fixing saving the pinned stage
  lib/mayaUsd/nodes/layerManager.cpp
  lib/usd/ui/layerEditor/mayaLayerEditorWindow.cpp
  lib/usd/ui/layerEditor/mayaSessionState.cpp
  lib/usd/ui/layerEditor/mayaSessionState.h
Labels: bug, adsk, ready-for-merge

#3129 Deprecate use of TF_REFPTR_CONST_VOLATILE_GET
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/wrapTranslatorBase.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/fileio/translators/wrapTranslatorContext.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/wrapLayerManager.cpp
  plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/wrapProxyShape.cpp
Labels: build, ready-for-merge
