Repository Autodesk/maya-usd, pull requests merged in 2023-11, with the labels that each got.

#3424 EMSUSD-732 - USD Export Options are always set to "on"
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
Labels: import-export, ready-for-merge

#3427 EMSUSD-254 disable the default prim auto-filling.
  lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
  lib/mayaUsd/resources/scripts/mayaUsdMayaReferenceUtils.py
Labels: adsk, workflows, ready-for-merge

#3421 EMSUSD-550 - Disable Material section when Mesh type is excluded from export
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
Labels: import-export, ready-for-merge

#3434 LOOKDEVX-2163 - Fix GLSL error with unlit surfaces
  lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
Labels: vp2renderdelegate, ready-for-merge

#3428 EMSUSD-490 Fixes Redo Visibility Visual Update in Outliner
  lib/usdUfe/ufe/StagesSubject.cpp
  test/lib/ufe/testObject3d.py
Labels: ufe-usd, ready-for-merge

#3432 EMSUSD-749 fix how stages are updated when saved
  lib/mayaUsd/commands/abstractLayerEditorWindow.h
  lib/mayaUsd/nodes/layerManager.cpp
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/utils/utilSerialization.cpp
  lib/usd/ui/layerEditor/mayaLayerEditorWindow.cpp
  lib/usd/ui/layerEditor/mayaLayerEditorWindow.h
  lib/usd/ui/layerEditor/mayaSessionState.cpp
  lib/usd/ui/layerEditor/mayaSessionState.h
  test/lib/mayaUsd/nodes/testProxyShapeBase.py
Labels: bug, core, ready-for-merge

#3442 EMSUSD-762 update help token and URL
  lib/mayaUsd/resources/helpTable/helpTableMayaUSD
  lib/mayaUsd/resources/scripts/mayaUsdMayaReferenceUtils.py
Labels: adsk, ready-for-merge

#3441 EMS-764 properly reset the select prim dialog.
  lib/usd/ui/importDialog/USDImportDialog.cpp
  lib/usd/ui/importDialog/USDImportDialogCmd.cpp
Labels: import-export, ready-for-merge

#3448 Update version to v0.27.0
  cmake/mayausd_version.info
Labels: build

#3447 EMSUSD-675 - Support for USD v23.11
  cmake/compiler_config.cmake
Labels: build, ready-for-merge

#3443 EMSUSD-614 - Fixes Edit As Maya Options Convert Instances Not Retaining From Session to Session
  plugin/adsk/scripts/USDMenuProc.mel
  plugin/adsk/scripts/mayaUsdTranslatorImport.mel
Labels: workflows, ready-for-merge

#3445 LOOKDEVX-2124 - MaterialX Topo Handler
  lib/mayaUsd/render/MaterialXGenOgsXml/CMakeLists.txt
  lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.h
  lib/mayaUsd/render/MaterialXGenOgsXml/OgsXmlGenerator.h
  lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.h
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  test/lib/mayaUsd/utils/CMakeLists.txt
  test/lib/mayaUsd/utils/materialx_test_data/Channel1_topo.mtlx
  test/lib/mayaUsd/utils/materialx_test_data/Channel4_topo.mtlx
  test/lib/mayaUsd/utils/materialx_test_data/Interface2_topo.mtlx
  test/lib/mayaUsd/utils/materialx_test_data/MultiOut6_topo.mtlx
  test/lib/mayaUsd/utils/materialx_test_data/topology_tests.mtlx
  test/lib/mayaUsd/utils/test_ShaderGenUtils.cpp
Labels: vp2renderdelegate, ready-for-merge

#3449 EMSUSD-604 fix crash when duplicating a proxy shape
  lib/mayaUsd/nodes/layerManager.h
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/nodes/proxyShapeBase.h
  test/lib/ufe/CMakeLists.txt
  test/lib/ufe/testDuplicateProxyShape.py
Labels: core, ready-for-merge

#3455 Add missing include
  lib/mayaUsd/fileio/primReaderRegistry.h
Labels: build, ready-for-merge

#3453 Update helpTableMayaUSD
  lib/mayaUsd/resources/helpTable/helpTableMayaUSD
Labels: documentation, ready-for-merge

#3459 EMSUSD-675 - Build USD v23.11 with Python 3.11/OSD 3.6 and update ecg-maya-usd
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateMaterialX.py
Labels: build, ready-for-merge

#3462 LOOKDEVX-2125 - Get watch list of traversed nodes
  lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.h
  test/lib/mayaUsd/utils/materialx_test_data/topology_tests.mtlx
  test/lib/mayaUsd/utils/test_ShaderGenUtils.cpp
Labels: vp2renderdelegate, ready-for-merge

#3385 Determine how to read UsdLux prims with an envvar
  lib/usd/translators/CMakeLists.txt
  lib/usd/translators/lightReader.cpp
  lib/usd/translators/lightRfMReader.cpp
  test/lib/usd/translators/UsdImportRfMLightTest/RfMLightsTest.usda
  test/lib/usd/translators/testUsdImportRfMLight.py
Labels: import-export, ready-for-merge

#3477 Merge v0.26.0 to dev
  doc/CHANGELOG.md
Labels: documentation

#3463 EMS-789 apply restrictions for activation and instanceable
  lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
  lib/usdUfe/ufe/UsdUndoToggleActiveCommand.cpp
  lib/usdUfe/ufe/UsdUndoToggleInstanceableCommand.cpp
  test/lib/ufe/testContextOps.py
Labels: ufe-usd, ready-for-merge

#3474 EMSUSD-603 - Errors when trying to cache a rig with merge transforms ON and namespaces OFF
  lib/mayaUsd/fileio/writeJobContext.cpp
  lib/mayaUsd/utils/util.cpp
  lib/mayaUsd/utils/util.h
  test/lib/mayaUsd/fileio/testCacheToUsd.py
Labels: import-export, ready-for-merge

#3484 EMSUSD-796 Send subtree invalidate on undo mark instanceable.
  lib/usdUfe/ufe/StagesSubject.cpp
Labels: ufe-usd, ready-for-merge
