Repository Autodesk/maya-usd, pull requests merged in 2023-04, with the labels that each got.

#2990 Updated Sub layer dialog to display the correct relative path when enabled.
  lib/mayaUsd/python/wrapUtil.cpp
  lib/mayaUsd/utils/utilFileSystem.cpp
  lib/mayaUsd/utils/utilFileSystem.h
  lib/usd/ui/layerEditor/CMakeLists.txt
  lib/usd/ui/layerEditor/saveLayersDialog.cpp
  plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
  plugin/adsk/scripts/mayaUsd_layerEditorFileDialogs.mel
Labels: bug, adsk, ready-for-merge

#2998 Updating docs with Maya 2024.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/build-issue-report.md
  README_DOC.md
  doc/build.md
Labels: documentation, ready-for-merge

#3004 MAYA-128199 fix error on save
  lib/mayaUsd/nodes/layerManager.cpp
  lib/mayaUsd/utils/util.cpp
  lib/mayaUsd/utils/util.h
  lib/mayaUsd/utils/utilSerialization.cpp
  lib/mayaUsd/utils/utilSerialization.h
  lib/usd/ui/layerEditor/layerTreeItem.cpp
Labels: adsk, ready-for-merge

#3006 HYDRA-300: Update proxyShapeSceneIndexPlugin.cpp
  lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
Labels: build, ready-for-merge

#2997 MAYA128513 edit routing of composite commands
  doc/EditRouting.md
  lib/mayaUsd/python/wrapEditRouter.cpp
  lib/mayaUsd/ufe/UsdAttributeHolder.cpp
  lib/mayaUsd/ufe/UsdObject3d.cpp
  lib/mayaUsd/ufe/UsdUndoDuplicateCommand.cpp
  lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp
  lib/mayaUsd/ufe/UsdUndoVisibleCommand.cpp
  lib/mayaUsd/ufe/UsdUndoVisibleCommand.h
  lib/mayaUsd/utils/CMakeLists.txt
  lib/mayaUsd/utils/editRouter.cpp
  lib/mayaUsd/utils/editRouter.h
  lib/mayaUsd/utils/editRouterContext.cpp
  lib/mayaUsd/utils/editRouterContext.h
  test/lib/ufe/testEditRouting.py
Labels: enhancement, adsk, ready-for-merge

#3014 MAYA-128490 docs on turning off edit routing
  doc/EditRouting.md
Labels: documentation

#3009 LOOKDEVX-1112 - Fix UINodeGraphNode test
  test/lib/ufe/testUINodeGraphNode.py
Labels: unit test, ready-for-merge

#3013 Update EditRouting.md
  doc/EditRouting.md
Labels: documentation, ready-for-merge

#3008 MAYA-128779 - Improvements for surface shader querying and handling
  lib/mayaUsd/ufe/UsdShaderNodeDef.cpp
  lib/mayaUsd/ufe/UsdShaderNodeDef.h
  lib/mayaUsd/ufe/UsdUndoMaterialCommands.cpp
  lib/mayaUsd/utils/util.cpp
  lib/mayaUsd/utils/util.h
  plugin/adsk/plugin/adskMaterialCommands.cpp
  plugin/adsk/plugin/adskMaterialCommands.h
  test/lib/ufe/testAttribute.py
  test/lib/ufe/testShaderNodeDef.py
Labels: ufe-usd, ready-for-merge, materials

#3026 MAYA-128934 - Bug fix: Prevent right click-material assignment for physics-related nodes
  plugin/adsk/plugin/adskMaterialCommands.cpp
Labels: adsk, ready-for-merge

#2971 Check skin cluster weights
  lib/mayaUsd/fileio/utils/jointWriteUtils.cpp
  test/lib/usd/translators/CMakeLists.txt
  test/lib/usd/translators/testUsdExportSkin.py
Labels: core, ready-for-merge

#3025 MAYA-128070 - Update for USD v23.02
  cmake/test.cmake
Labels: unit test, ready-for-merge

#3022 MAYA-128504 - As a user, I'd like to load my USD root file as relative before I save my scene file
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/nodes/proxyShapeBase.h
  lib/mayaUsd/utils/utilSerialization.cpp
  lib/usd/ui/layerEditor/mayaSessionState.cpp
  plugin/adsk/scripts/AETemplateHelpers.py
  plugin/adsk/scripts/mayaUSDRegisterStrings.py
  plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
  plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
Labels: adsk, ready-for-merge

#3020 Remove/replace all UFE_PREVIEW_VERSION_NUM
  cmake/modules/FindUFE.cmake
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/Global.cpp
  lib/mayaUsd/ufe/MayaUIInfoHandler.cpp
  lib/mayaUsd/ufe/ProxyShapeHierarchy.cpp
  lib/mayaUsd/ufe/ProxyShapeHierarchy.h
  lib/mayaUsd/ufe/ProxyShapeSceneSegmentHandler.cpp
  lib/mayaUsd/ufe/ProxyShapeSceneSegmentHandler.h
  lib/mayaUsd/ufe/PulledObjectHierarchy.cpp
  lib/mayaUsd/ufe/PulledObjectHierarchy.h
  lib/mayaUsd/ufe/StagesSubject.cpp
  lib/mayaUsd/ufe/UfeVersionCompat.h
  lib/mayaUsd/ufe/UsdAttribute.cpp
  lib/mayaUsd/ufe/UsdAttribute.h
  lib/mayaUsd/ufe/UsdAttributes.cpp
  lib/mayaUsd/ufe/UsdAttributes.h
  lib/mayaUsd/ufe/UsdCameraHandler.cpp
  lib/mayaUsd/ufe/UsdCameraHandler.h
  lib/mayaUsd/ufe/UsdConnectionHandler.cpp
  lib/mayaUsd/ufe/UsdConnectionHandler.h
  lib/mayaUsd/ufe/UsdContextOps.cpp
  lib/mayaUsd/ufe/UsdHierarchy.cpp
  lib/mayaUsd/ufe/UsdHierarchy.h
  lib/mayaUsd/ufe/UsdSceneItemOps.cpp
  lib/mayaUsd/ufe/UsdSceneItemOps.h
  lib/mayaUsd/ufe/UsdShaderNodeDef.cpp
  lib/mayaUsd/ufe/UsdShaderNodeDef.h
  lib/mayaUsd/ufe/UsdUIUfeObserver.cpp
  lib/mayaUsd/ufe/UsdUndoAddNewPrimCommand.cpp
  lib/mayaUsd/ufe/UsdUndoAddNewPrimCommand.h
  lib/mayaUsd/ufe/UsdUndoAttributesCommands.cpp
  lib/mayaUsd/ufe/UsdUndoAttributesCommands.h
  lib/mayaUsd/ufe/UsdUndoDeleteCommand.cpp
  lib/mayaUsd/ufe/UsdUndoDuplicateCommand.cpp
  lib/mayaUsd/ufe/UsdUndoDuplicateCommand.h
  lib/mayaUsd/ufe/UsdUndoInsertChildCommand.cpp
  lib/mayaUsd/ufe/UsdUndoInsertChildCommand.h
  lib/mayaUsd/ufe/UsdUndoMaterialCommands.cpp
  lib/mayaUsd/ufe/UsdUndoMaterialCommands.h
  lib/mayaUsd/ufe/UsdUndoRenameCommand.cpp
  lib/mayaUsd/ufe/UsdUndoRenameCommand.h
  lib/mayaUsd/ufe/Utils.cpp
  plugin/adsk/plugin/adskMaterialCommands.cpp
  plugin/adsk/plugin/adskMaterialCommands.h
  test/lib/mayaUsd/fileio/testEditAsMaya.py
  test/lib/ufe/CMakeLists.txt
  test/lib/ufe/testAttribute.py
  test/lib/ufe/testAttributes.py
  test/lib/ufe/testCamera.py
  test/lib/ufe/testComboCmd.py
  test/lib/ufe/testConnections.py
  test/lib/ufe/testContextOps.py
  test/lib/ufe/testDeleteCmd.py
  test/lib/ufe/testDuplicateCmd.py
  test/lib/ufe/testRename.py
  test/lib/ufe/testSceneSegment.py
  test/lib/ufe/testShaderNodeDef.py
  test/lib/ufe/testUIInfoHandler.py
  test/testUtils/mayaUtils.py
Labels: adsk, ufe, ready-for-merge

#3031 MAYA-128598 fix crash when deleting a stage
  lib/usd/ui/layerEditor/layerTreeItem.cpp
Labels: adsk, ready-for-merge, crash

#3034 MAYA-128764 fix AE refresh
  lib/mayaUsd/ufe/Global.cpp
  lib/mayaUsd/ufe/StagesSubject.cpp
  lib/mayaUsd/ufe/UsdAttribute.cpp
  lib/mayaUsd/ufe/UsdAttributeHolder.cpp
  lib/mayaUsd/ufe/private/UfeNotifGuard.h
  test/lib/ufe/testAttribute.py
Labels: enhancement, adsk, ready-for-merge

#3035 Fixes a stage leak from USD caches
  lib/mayaUsd/utils/stageCache.cpp
  test/lib/testMayaUsdCacheId.py
Labels: proxy, ready-for-merge

#3015 Smart signaling must emit MNodeMessages
  lib/mayaUsd/listeners/stageNoticeListener.cpp
  lib/mayaUsd/listeners/stageNoticeListener.h
  lib/mayaUsd/nodes/CMakeLists.txt
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/nodes/proxyShapeBase.h
  lib/mayaUsd/nodes/proxyShapeListenerBase.cpp
  lib/mayaUsd/nodes/proxyShapeListenerBase.h
  lib/mayaUsd/nodes/proxyShapePlugin.cpp
  lib/mayaUsd/nodes/proxyShapeUpdateManager.cpp
  lib/mayaUsd/nodes/proxyShapeUpdateManager.h
  lib/mayaUsd/ufe/UsdAttribute.cpp
  plugin/adsk/plugin/CMakeLists.txt
  plugin/adsk/plugin/ProxyShapeListener.cpp
  plugin/adsk/plugin/ProxyShapeListener.h
  plugin/adsk/plugin/plugin.cpp
  test/lib/ufe/testContextOps.py
  test/lib/ufe/testUINodeGraphNode.py
  test/testUtils/mayaUtils.py
Labels: proxy, ready-for-merge

#3037 Added save / restore to preserve object selection after Undoing Remove SubLayer
  lib/mayaUsd/commands/layerEditorCommand.cpp
Labels: bug, adsk, ready-for-merge

#3043 MAYA-128942 - testVP2RenderDelegateDrawModes fails with USD v23.02
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  lib/mayaUsd/render/vp2RenderDelegate/material.h
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
  lib/mayaUsd/render/vp2ShaderFragments/NwFaceCameraIfNAN.xml
  lib/mayaUsd/render/vp2ShaderFragments/UsdPreviewSurfaceLightAPI1.xml
  lib/mayaUsd/render/vp2ShaderFragments/UsdPreviewSurfaceLightAPI2.xml
  lib/mayaUsd/render/vp2ShaderFragments/UsdPreviewSurfaceLightAPI3.xml
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateDrawModesTest/baseline/post-22_11-DrawModes_box_all_negative.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateDrawModesTest/baseline/post-22_11-DrawModes_box_all_positive.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateDrawModesTest/baseline/post-22_11-DrawModes_cross_all_negative.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateDrawModesTest/baseline/post-22_11-DrawModes_cross_all_positive.png
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateDrawModes.py
Labels: vp2renderdelegate, ready-for-merge
