Repository Autodesk/maya-usd, pull requests merged in 2023-06, with the labels that each got.

#3131 MAYA-128511 fix export roots behaviour
  lib/mayaUsd/commands/baseExportCommand.cpp
Labels: import-export, ready-for-merge

#3132 MAYA-129071 add UFE selection notification tests
  test/lib/ufe/CMakeLists.txt
  test/lib/ufe/testSelectionNotification.py
Labels: bug, adsk, ufe, ready-for-merge

#3136 MAYA-000000 Usd UFE include case fix for Linux and OSX
  lib/mayaUsd/ufe/UsdCodeWrapperHandler.cpp
Labels: build, ready-for-merge

#3134 Update FindUFE.cmake for Ufe v4.2
  cmake/modules/FindUFE.cmake
Labels: build, ready-for-merge

#3135 MAYA-128503 - Improve roundtripping of GeomSubsets
  lib/mayaUsd/commands/Readme.md
  lib/mayaUsd/fileio/jobs/meshDataReadJob.cpp
  lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp
  lib/mayaUsd/fileio/shading/shadingModeExporterContext.h
  lib/mayaUsd/fileio/translators/translatorMaterial.cpp
  lib/mayaUsd/fileio/utils/meshReadUtils.cpp
  lib/mayaUsd/fileio/utils/meshReadUtils.h
  lib/mayaUsd/fileio/utils/meshWriteUtils.cpp
  lib/mayaUsd/fileio/utils/roundTripUtil.cpp
  lib/mayaUsd/fileio/utils/roundTripUtil.h
  test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
Labels: import-export, ready-for-merge, materials

#3144 HYDRA-318 Fix for prims not being added to empty USD Stage
  lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
Labels: ready-for-merge, mayaHydra

#3138 MAYA-129682 - Move `isMaterialsScope()` into Utils.
  lib/mayaUsd/ufe/UsdUndoMaterialCommands.cpp
  lib/mayaUsd/ufe/Utils.cpp
  lib/mayaUsd/ufe/Utils.h
Labels: ready-for-merge, materials

#3152 Use new HdMaterialBindings Schema and API
  lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
Labels: build, ready-for-merge

#2954 Add metersPerUnit scaling
  lib/mayaUsd/commands/Readme.md
  lib/mayaUsd/commands/baseExportCommand.cpp
  lib/mayaUsd/commands/baseExportCommand.h
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/jobs/writeJob.cpp
  lib/mayaUsd/fileio/transformWriter.cpp
  lib/mayaUsd/fileio/transformWriter.h
  lib/mayaUsd/fileio/utils/meshWriteUtils.cpp
  lib/mayaUsd/fileio/utils/meshWriteUtils.h
  lib/mayaUsd/utils/util.cpp
  lib/mayaUsd/utils/util.h
  lib/usd/translators/meshWriter.cpp
  test/lib/usd/translators/testUsdExportLayerAttributes.py
Labels: import-export

#3123 MAYA-114043 Frame both USD and Maya data when edited as Maya
  lib/mayaUsd/fileio/orphanedNodesManager.cpp
  lib/mayaUsd/fileio/orphanedNodesManager.h
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/fileio/primUpdaterManager.h
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/ufe/UsdObject3d.cpp
  lib/mayaUsd/ufe/Utils.cpp
  lib/mayaUsd/ufe/Utils.h
  lib/mayaUsd/utils/CMakeLists.txt
  lib/mayaUsd/utils/trieVisitor.h
  lib/usdUfe/ufe/Utils.cpp
  lib/usdUfe/ufe/Utils.h
  test/lib/mayaUsd/fileio/CMakeLists.txt
  test/lib/mayaUsd/fileio/testEditAsMayaBBox.py
  test/testSamples/twoMeshSpheres/two_mesh_spheres.usda
Labels: enhancement, adsk, ready-for-merge

#3154 MAYA-127770 missing discard edits
  lib/mayaUsd/fileio/orphanedNodesManager.cpp
Labels: bug, adsk, ready-for-merge

#3157 MAYA-126887 fix context menu when in a set
  plugin/adsk/scripts/mayaUsdMenu.mel
Labels: bug, adsk, ready-for-merge

#3161 MAYA-128473 - Move UFE to its own Project - Part 9
  CMakeLists.txt
  cmake/modules/FindUSD.cmake
  lib/CMakeLists.txt
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
  lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/Global.cpp
  lib/mayaUsd/ufe/MayaStagesSubject.cpp
  lib/mayaUsd/ufe/MayaStagesSubject.h
  lib/mayaUsd/ufe/ProxyShapeCameraHandler.cpp
  lib/mayaUsd/ufe/UsdAttribute.cpp
  lib/mayaUsd/ufe/UsdConnections.cpp
  lib/mayaUsd/ufe/UsdMaterial.cpp
  lib/mayaUsd/ufe/Utils.cpp
  lib/mayaUsd/ufe/Utils.h
  lib/mayaUsd/ufe/wrapUtils.cpp
  lib/mayaUsd/utils/util.h
  lib/usdUfe/python/wrapUtils.cpp
  lib/usdUfe/ufe/CMakeLists.txt
  lib/usdUfe/ufe/Global.cpp
  lib/usdUfe/ufe/Global.h
  lib/usdUfe/ufe/StagesSubject.cpp
  lib/usdUfe/ufe/StagesSubject.h
  lib/usdUfe/ufe/UsdCamera.cpp
  lib/usdUfe/ufe/UsdCamera.h
  lib/usdUfe/ufe/UsdCameraHandler.cpp
  lib/usdUfe/ufe/UsdCameraHandler.h
  lib/usdUfe/ufe/Utils.cpp
  lib/usdUfe/ufe/Utils.h
  lib/usdUfe/utils/Utils.h
Labels: ufe-usd, ready-for-merge

#3159 MAYA-128925 merge default values
  lib/mayaUsd/commands/Readme.md
  lib/mayaUsd/commands/baseExportCommand.cpp
  lib/mayaUsd/commands/baseExportCommand.h
  lib/mayaUsd/fileio/CMakeLists.txt
  lib/mayaUsd/fileio/flexibleSparseValueWriter.cpp
  lib/mayaUsd/fileio/flexibleSparseValueWriter.h
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/primWriter.cpp
  lib/mayaUsd/fileio/primWriter.h
  lib/mayaUsd/fileio/transformWriter.cpp
  lib/mayaUsd/fileio/transformWriter.h
  lib/mayaUsd/fileio/translators/translatorLight.cpp
  lib/mayaUsd/fileio/translators/translatorLight.h
  lib/mayaUsd/fileio/utils/adaptor.cpp
  lib/mayaUsd/fileio/utils/adaptor.h
  lib/mayaUsd/fileio/utils/jointWriteUtils.cpp
  lib/mayaUsd/fileio/utils/jointWriteUtils.h
  lib/mayaUsd/fileio/utils/meshWriteUtils.cpp
  lib/mayaUsd/fileio/utils/meshWriteUtils.h
  lib/mayaUsd/fileio/utils/writeUtil.cpp
  lib/mayaUsd/fileio/utils/writeUtil.h
  lib/mayaUsd/python/wrapPrimWriter.cpp
  lib/mayaUsd/python/wrapSchemaApiAdaptor.cpp
  lib/mayaUsd/python/wrapSparseValueWriter.h
  lib/mayaUsd/resources/scripts/mayaUsdMergeToUSDOptions.py
  lib/usd/translators/particleWriter.cpp
  plugin/pxr/doc/README.md
  test/lib/mayaUsd/fileio/CMakeLists.txt
  test/lib/mayaUsd/fileio/testEditAsMayaDefaultValue.py
  test/lib/usd/plugin/bulletAdaptor.cpp
  test/testSamples/pointLight/pointLight.usda
Labels: workflows, ready-for-merge

#3158 Add options to UsdExport in new test
  test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
Labels: unit test, ready-for-merge

#3150 MAYA-129521 MacOS: Updates Maya USD to use MacOS Frameworks for Qt 6 instead of using loose libraries
  cmake/utils.cmake
  lib/usd/ui/CMakeLists.txt
Labels: build, ready-for-merge

#3160 Add documentation for import chaser
  lib/mayaUsd/commands/Readme.md
Labels: documentation, ready-for-merge

#3173 EMSUSD-85 - As a user, I'd like my 'Merge as USD' edits to be specified as overs when authoring to a stronger layer
  lib/usd/utils/MergePrims.cpp
  test/lib/mayaUsd/fileio/testMergeToUsd.py
Labels: workflows, ready-for-merge

#3174 Fix call to c_str on an MString object
  lib/mayaUsd/render/mayaToHydra/renderOverride.cpp
Labels: build, ready-for-merge

#3180 Update version to v0.25.0
  cmake/mayausd_version.info
Labels: build

#3170 MAYA-102168 clear payloads
  lib/mayaUsd/resources/scripts/CMakeLists.txt
  lib/mayaUsd/resources/scripts/mayaUsdClearRefsOrPayloadsOptions.mel
  lib/mayaUsd/resources/scripts/mayaUsdClearRefsOrPayloadsOptions.py
  lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
  lib/mayaUsd/resources/scripts/mayaUsdOptions.py
  lib/mayaUsd/ufe/UsdContextOps.cpp
  plugin/adsk/scripts/mayaUsd_pluginUICreation.mel
Labels: enhancement, adsk, ready-for-merge

#3162 Add new camera parameters to the pxr gl renderer
  lib/mayaUsd/render/pxrUsdMayaGL/sceneDelegate.cpp
Labels: legacy rendering, ready-for-merge

#3183 EMSUSD-109 allow textures to be relative
  lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
  lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
  plugin/adsk/scripts/CMakeLists.txt
  plugin/adsk/scripts/mayaUSDRegisterStrings.py
  plugin/adsk/scripts/mayaUsdMenu.mel
  plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
  plugin/adsk/scripts/mayaUsd_imageFileDialogs.mel
Labels: enhancement, adsk, ready-for-merge

#3081 MAYA-127095 remove usage of macros leading to fatal exits
  doc/codingGuidelines.md
  lib/mayaUsd/fileio/orphanedNodesManager.cpp
  lib/mayaUsd/fileio/primUpdater.cpp
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/ufe/UsdConnections.cpp
  lib/mayaUsd/ufe/UsdContextOps.cpp
  lib/mayaUsd/ufe/UsdContextOps.h
  lib/mayaUsd/ufe/UsdLight.h
  lib/mayaUsd/ufe/UsdPathMappingHandler.cpp
  lib/mayaUsd/ufe/UsdRotatePivotTranslateUndoableCommand.h
  lib/mayaUsd/ufe/UsdSceneItemOps.h
  lib/mayaUsd/ufe/UsdShaderAttributeDef.cpp
  lib/mayaUsd/ufe/UsdShaderAttributeHolder.cpp
  lib/mayaUsd/ufe/UsdShaderNodeDef.cpp
  lib/mayaUsd/ufe/UsdStageMap.cpp
  lib/mayaUsd/ufe/UsdTransform3d.cpp
  lib/mayaUsd/ufe/UsdTransform3d.h
  lib/mayaUsd/ufe/UsdTransform3dCommonAPI.cpp
  lib/mayaUsd/ufe/UsdTransform3dFallbackMayaXformStack.cpp
  lib/mayaUsd/ufe/UsdTransform3dMatrixOp.cpp
  lib/mayaUsd/ufe/UsdTransform3dMayaXformStack.cpp
  lib/mayaUsd/ufe/UsdTransform3dReadImpl.cpp
  lib/mayaUsd/ufe/Utils.cpp
  lib/mayaUsd/ufe/XformOpUtils.cpp
  lib/usdUfe/ufe/UsdCamera.h
  lib/usdUfe/ufe/UsdHierarchy.h
  lib/usdUfe/ufe/private/Utils.cpp
  lib/usdUfe/undo/UsdUndoStateDelegate.cpp
Labels: enhancement, ready-for-merge, crash

#3185 EMSUSD-104 UI fixes
  lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
  lib/mayaUsd/resources/scripts/mayaUsdMayaReferenceUtils.py
  lib/mayaUsd/ufe/UsdContextOps.cpp
  lib/usd/ui/layerEditor/saveLayersDialog.cpp
  lib/usd/ui/layerEditor/stringResources.h
Labels: adsk, ready-for-merge
