Repository Autodesk/maya-usd, pull requests merged in 2023-09, with the labels that each got.

#3302 EMS-552 fix default prepend/append when no prefs are saved
  lib/mayaUsd/resources/scripts/mayaUsdUtils.py
Labels: adsk, ready-for-merge

#3306 EMSUSD-596 - AE: broken templates on older maya versions
  lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
Labels: adsk, ready-for-merge

#3305 EMSUSD-311 fix load sub-layer file preview.
  lib/mayaUsd/utils/utilFileSystem.cpp
  lib/usd/ui/layerEditor/loadLayersDialog.cpp
  plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
  plugin/adsk/scripts/mayaUsd_layerEditorFileDialogs.mel
Labels: adsk, ready-for-merge

#3307 LOOKDEVX-1847 - Fix broken normal maps
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/DemoQuads_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateMaterialX.py
  test/testSamples/MaterialX/DemoQuads.usda
  test/testSamples/MaterialX/textures/mesh_wire_norm.png
Labels: vp2renderdelegate, ready-for-merge

#3310 EMSUSD-59 make error messages more clear
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
Labels: enhancement, adsk, ready-for-merge

#3315 EMSUSD-80 avoid creating an extra transform when in a prototype
  lib/mayaUsd/fileio/translators/translatorMesh.cpp
  lib/usd/translators/meshReader.cpp
  test/lib/usd/translators/testUsdImportInstances.py
Labels: enhancement, adsk, ready-for-merge

#3309 EMSUSD-533 - Incremental naming doesn't take zero into consideration
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/ufe/Global.cpp
  lib/mayaUsd/ufe/UsdAttributes.cpp
  lib/mayaUsd/ufe/Utils.cpp
  lib/mayaUsd/ufe/Utils.h
  lib/usdUfe/python/wrapUtils.cpp
  lib/usdUfe/ufe/Global.cpp
  lib/usdUfe/ufe/Global.h
  lib/usdUfe/ufe/Utils.cpp
  lib/usdUfe/ufe/Utils.h
  test/lib/ufe/testContextOps.py
  test/lib/ufe/testDuplicateCmd.py
  test/lib/ufe/testPythonWrappers.py
Labels: ufe-usd, ready-for-merge

#3322 EMSUSD-612 - Update topo node list
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  test/testSamples/MaterialX/ShadedPyramid.usda
Labels: vp2renderdelegate, ready-for-merge

#3317 Set purpose on test meshes
  test/testSamples/UsdSkel/HIK_Export.usda
  test/testSamples/UsdSkel/skinCluster.usda
Labels: unit test, ready-for-merge

#3320 EMSUSD-277 fix lost muted anonymous layers
  lib/mayaUsd/commands/layerEditorCommand.cpp
  lib/mayaUsd/utils/layerMuting.cpp
  lib/mayaUsd/utils/layerMuting.h
  test/lib/mayaUsd/fileio/testAddMayaReference.py
  test/testUtils/usdUtils.py
Labels: bug, core, ready-for-merge

#3324 EMSUSD-498 support ignoring variants when merging to USD
  lib/mayaUsd/commands/PullPushCommands.cpp
  lib/mayaUsd/fileio/primUpdater.cpp
  lib/mayaUsd/fileio/primUpdaterArgs.cpp
  lib/mayaUsd/fileio/primUpdaterArgs.h
  lib/usd/utils/MergePrims.cpp
  test/lib/mayaUsd/fileio/testMergeToUsd.py
  test/testSamples/multiVariants/no-variant-preview-component.usda
  test/testSamples/multiVariants/no-variant-render-component.usda
  test/testSamples/multiVariants/no-variant-root.usda
  test/testSamples/multiVariants/with-variants-preview-component.usda
  test/testSamples/multiVariants/with-variants-render-component.usda
  test/testSamples/multiVariants/with-variants-root.usda
Labels: workflows, ready-for-merge

#3318 Add versioning to tests that use UsdSkelPackedJointAnimation
  test/lib/mayaUsd/utils/testMaterialCommands.py
  test/lib/ufe/testUIIcons.py
Labels: unit test, ready-for-merge

#3325 HYDRA-496: Fix for crash on new scene with a USD Stage inside the Maya scene
  lib/mayaUsd/nodes/proxyShapeStageExtraData.cpp
  lib/mayaUsd/nodes/proxyShapeStageExtraData.h
  lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.cpp
  lib/mayaUsd/sceneIndex/proxyShapeSceneIndexPlugin.h
Labels: adsk, core, ready-for-merge

#3327 EMSUSD-305 Sets Add A Reference as default
  lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
  lib/mayaUsd/resources/scripts/mayaUsdUtils.py
Labels: bug, adsk, ready-for-merge

#3329 EMSUSD-594 material dup ten times
  lib/mayaUsd/ufe/UsdUndoDuplicateCommand.cpp
  lib/mayaUsd/ufe/UsdUndoDuplicateSelectionCommand.cpp
  test/lib/ufe/testDuplicateCmd.py
  test/testSamples/dup_material/dup_material.usda
  test/testSamples/dup_material/textures/diffuse.jpg
Labels: ufe-usd, ready-for-merge

#3333 EMSUSD-623 use project folder by default
  lib/mayaUsd/utils/utilFileSystem.cpp
  lib/usd/ui/layerEditor/loadLayersDialog.cpp
Labels: enhancement, adsk, ready-for-merge

#3298 EMSUSD-282 - MayaUsd: build with Qt directly from Maya devkit/runtime
  CMakeLists.txt
  build.py
  cmake/modules/FindMaya_Qt.cmake
  lib/mayaUsd/CMakeLists.txt
  lib/usd/CMakeLists.txt
  lib/usd/ui/CMakeLists.txt
  lib/usd/ui/importDialogDemo/CMakeLists.txt
  plugin/adsk/plugin/CMakeLists.txt
Labels: build, ready-for-merge

#3343 EMSUSD-287 - Setup preference section
  lib/mayaUsd/resources/ae/usdschemabase/custom_image_control.py
  lib/usd/ui/layerEditor/layerEditorWidget.cpp
  lib/usd/ui/layerEditor/saveLayersDialog.cpp
  lib/usd/ui/layerEditor/stringResources.h
  plugin/adsk/scripts/CMakeLists.txt
  plugin/adsk/scripts/mayaUSDRegisterStrings.mel
  plugin/adsk/scripts/mayaUSDRegisterStrings.py
  plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
  plugin/adsk/scripts/mayaUsd_pluginUICreation.mel
  plugin/adsk/scripts/mayaUsd_pluginUIDeletion.mel
  plugin/adsk/scripts/mayaUsd_preferenceTab.mel
  plugin/adsk/scripts/usdFileSaveOptions.mel
Labels: enhancement, workflows, ready-for-merge

#3345 EMSUSD-490 Fixes outerliner not refreshing when performing a UsdUndoVisibleCommand
  lib/usdUfe/ufe/StagesSubject.cpp
Labels: bug, adsk, ready-for-merge
