Repository Autodesk/maya-usd, pull requests merged in 2024-01, with the labels that each got.

#3540 Add explicit boost/optional include
  lib/mayaUsd/fileio/shaderReader.h
Labels: build, ready-for-merge

#3536 EMSUSD-181: Tooltips are not formatted correctly
  lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
  lib/mayaUsd/resources/ae/usdschemabase/attribute_custom_control.py
  lib/mayaUsd/resources/ae/usdschemabase/custom_enum_control.py
  lib/mayaUsd/resources/ae/usdschemabase/custom_image_control.py
Labels: adsk, ready-for-merge

#3521 Update usage of the Hydra API
  lib/mayaUsd/fileio/translators/translatorMaterial.cpp
Labels: build, ready-for-merge

#3523 EMSUSD-671 Remove the load payloads proxy shape attribute
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/python/CMakeLists.txt
  lib/mayaUsd/python/module.cpp
  lib/mayaUsd/python/wrapLoadRules.cpp
  lib/mayaUsd/utils/loadRules.h
  lib/mayaUsd/utils/loadRulesAttribute.cpp
  lib/usdUfe/utils/loadRules.h
  lib/usdUfe/utils/loadRulesText.cpp
  plugin/adsk/scripts/AETemplateHelpers.py
  plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
  test/lib/mayaUsd/nodes/testProxyShapeBase.py
Labels: adsk, ready-for-merge

#3537 EMSUSD-804 duplicate-to-USD support relationship targets
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/ufe/UsdUndoDuplicateCommand.cpp
  lib/mayaUsd/ufe/Utils.cpp
  lib/mayaUsd/ufe/Utils.h
  lib/mayaUsd/utils/traverseLayer.cpp
  lib/usdUfe/ufe/Utils.cpp
  lib/usdUfe/ufe/Utils.h
Labels: workflows, ready-for-merge

#3546 LOOKDEVX-2331 - Do not bail out after a failed validate call
  lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.cpp
Labels: vp2renderdelegate, ready-for-merge

#3545 Updated workflow for running preflight.
  .github/workflows/maya-usd-preflight-launcher.yml
  doc/CONTRIBUTING.md
Labels: build, ready-for-merge

#3549 EMSUSD-838 new layers collapsed
  lib/usd/ui/layerEditor/layerTreeView.cpp
Labels: adsk, ready-for-merge

#3544 EMSUSD-840 expand and collapse all layer items
  lib/usd/ui/layerEditor/layerTreeView.cpp
  lib/usd/ui/layerEditor/layerTreeView.h
Labels: enhancement, adsk, ready-for-merge

#3550 EMSUSD-934 - Fixes a bug with UsdAttributeEnumString that have token
  lib/mayaUsd/ufe/UsdAttribute.cpp
Labels: ufe-usd, ready-for-merge

#3556 Update CONTRIBUTING.md to point to coding guidelines
  doc/CONTRIBUTING.md
Labels: documentation, ready-for-merge

#3552 LOOKDEVX-2354 - Fix the transform nodes crash
  lib/mayaUsd/render/MaterialXGenOgsXml/CMakeLists.txt
  lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaTransformNormalNodeGlsl.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaTransformNormalNodeGlsl.h
  lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaTransformPointNodeGlsl.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaTransformPointNodeGlsl.h
  lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaTransformVectorNodeGlsl.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaTransformVectorNodeGlsl.h
Labels: vp2renderdelegate, ready-for-merge

#3559 LOOKDEVX-2352 Fix incorrect tangent fixup
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/DemoQuads_render.png
  test/testSamples/MaterialX/DemoQuads.usda
Labels: vp2renderdelegate, ready-for-merge

#3561 EMSUSD-956: Resource Identifier warning on first launch of MayaUSD
  plugin/adsk/scripts/mayaUSDRegisterStrings.mel
  plugin/adsk/scripts/mayaUsd_createStageFromFile.mel
Labels: adsk, ready-for-merge

#3553 EMSUSD-717: USD Prefs: "Use Display Color" preferences are maintained when user cancels change
  plugin/adsk/scripts/mayaUsd_preferenceTab.mel
Labels: adsk, ready-for-merge

#3558 EMSUSD-134 unit test for parent to selection
  test/lib/ufe/testParentCmd.py
Labels: unit test, ready-for-merge

#3564 LOOKDEVX-2403 - Allow creating custom types at NodeGraph boundaries
  lib/mayaUsd/ufe/UsdAttribute.cpp
  lib/mayaUsd/ufe/UsdAttribute.h
  lib/mayaUsd/ufe/UsdAttributeHolder.cpp
  lib/mayaUsd/ufe/UsdAttributes.cpp
  test/lib/ufe/testConnections.py
Labels: ufe-usd, ready-for-merge

#3563 EMSUSD-65 wait cursor during long VP2 updates
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
  lib/mayaUsd/ufe/Global.cpp
  lib/usdUfe/ufe/Utils.h
Labels: vp2renderdelegate, ready-for-merge

#3565 EMSUSD-964 - Layer Editor's "Revert to File" menu item is renamed to "Reload"
  lib/usd/ui/layerEditor/layerTreeItem.cpp
  plugin/adsk/scripts/mayaUSDRegisterStrings.mel
  plugin/adsk/scripts/mayaUsdMenu.mel
Labels: adsk, ready-for-merge

#3566 EMSUSD-804 fix copying node with Arnold material.
  lib/mayaUsd/fileio/primUpdaterManager.cpp
Labels: workflows, ready-for-merge

#3570 LOOKDEVX-2440 - Fix crash in topo handler
  lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.h
  test/lib/mayaUsd/utils/materialx_test_data/BrokenMaterial1_topo.mtlx
  test/lib/mayaUsd/utils/materialx_test_data/topology_tests.mtlx
  test/lib/mayaUsd/utils/test_ShaderGenUtils.cpp
Labels: vp2renderdelegate, ready-for-merge

#3571 Fix AE tooltip and status bar message
  lib/mayaUsd/resources/ae/usdschemabase/attribute_custom_control.py
Labels: adsk, ready-for-merge

#3573 EMSUSD-972 refactor duplication code
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/python/CMakeLists.txt
  lib/mayaUsd/python/module.cpp
  lib/mayaUsd/python/wrapCopyLayerPrims.cpp
  lib/mayaUsd/utils/CMakeLists.txt
  lib/mayaUsd/utils/copyLayerPrims.cpp
  lib/mayaUsd/utils/copyLayerPrims.h
  test/lib/mayaUsd/fileio/CMakeLists.txt
  test/lib/mayaUsd/fileio/testCopyLayerPrims.py
Labels: core, unit test, ready-for-merge

#3574 EMSUSD-972 add unit test for circular relationships
  lib/mayaUsd/utils/copyLayerPrims.cpp
  test/lib/mayaUsd/fileio/testCopyLayerPrims.py
Labels: workflows, unit test, ready-for-merge

#3576 MAYA-132438 fix slow scene load performance
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/nodes/proxyShapeBase.h
  lib/mayaUsd/ufe/UsdStageMap.cpp
Labels: core, ready-for-merge

#3572 EMSUSD-767 - Set the default prim on export
  lib/mayaUsd/commands/Readme.md
  lib/mayaUsd/commands/baseExportCommand.cpp
  lib/mayaUsd/commands/baseExportCommand.h
  lib/mayaUsd/fileio/functorPrimWriter.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/jobs/writeJob.cpp
  lib/mayaUsd/fileio/primWriterArgs.cpp
  lib/mayaUsd/fileio/primWriterArgs.h
  plugin/adsk/scripts/CMakeLists.txt
  plugin/adsk/scripts/mayaUSDRegisterStrings.mel
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
  plugin/adsk/scripts/mayaUsd_exportHelpers.py
  test/lib/usd/translators/CMakeLists.txt
  test/lib/usd/translators/testUsdExportDefaultPrim.py
Labels: adsk, import-export, ready-for-merge

#3579 EMSUSD-967 fix AE flashing when adding many attributes
  lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
Labels: bug, adsk, ready-for-merge

#3585 Update version to v0.28.0
  cmake/mayausd_version.info
Labels: build
