Repository Autodesk/maya-usd, pull requests merged in 2024-09, with the labels that each got.

#3897 EMSUSD-1477 unit test for multi export chasers with multi job contexts
  test/lib/mayaUsd/fileio/CMakeLists.txt
  test/lib/mayaUsd/fileio/testExportChaserJobContext.py
Labels: unit test, ready-for-merge

#3890 Updating callsites to use new NdrSdfTypeIndicator class
  lib/mayaUsd/fileio/translators/translatorUtil.cpp
  lib/mayaUsd/ufe/UsdUndoMaterialCommands.cpp
  lib/usd/hdMaya/adapters/materialNetworkConverter.cpp
  lib/usd/translators/shading/mtlxBaseWriter.cpp
  lib/usd/translators/shading/usdFileTextureWriter.cpp
  lib/usdUfe/ufe/UsdShaderAttributeDef.cpp
  lib/usdUfe/ufe/UsdShaderAttributeHolder.cpp
  lib/usdUfe/ufe/Utils.cpp
Labels: build, ready-for-merge

#3901 Update maya-usd-preflight-launcher.yml
  .github/workflows/maya-usd-preflight-launcher.yml
Labels: build, ready-for-merge

#3899 EMSUSD-1477 merge job context arguments with user arguments
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
Labels: workflows, ready-for-merge

#3903 LOOKDEVX-3335 - Update MaterialX node UInames
  lib/usdUfe/utils/Utils.cpp
Labels: ufe-usd, ready-for-merge

#3905 EMSUSD-1550 - Build USD v24.08 (with oneTBB) for Maya 2026
  lib/mayaUsd/render/vp2RenderDelegate/resourceRegistry.h
Labels: build, ready-for-merge

#3900 EMSUSD-1496 export stages as relative references
  lib/mayaUsd/nodes/layerManager.cpp
  lib/mayaUsd/utils/utilSerialization.cpp
  lib/mayaUsd/utils/utilSerialization.h
  lib/usd/translators/stageWriter.cpp
  lib/usd/ui/layerEditor/mayaSessionState.cpp
Labels: import-export, ready-for-merge

#3906 EMSUSD-1629 fix copying grouped meshes
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/ufe/Utils.cpp
  plugin/adsk/scripts/mayaUsdMenu.mel
  test/lib/mayaUsd/fileio/testDuplicateAs.py
Labels: workflows, ready-for-merge

#3908 EMSUSD-1550 - Build USD v24.08 (with oneTBB)
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateMaterialX.py
Labels: unit test, ready-for-merge

#3909 Trim down the UsdUfe linking to only what is needed.
  lib/usdUfe/CMakeLists.txt
Labels: build, ready-for-merge

#3896 EMSUSD-172 - Add more light shapes supports in the viewport
  cmake/modules/FindUFE.cmake
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/UsdLight.cpp
  lib/mayaUsd/ufe/UsdLight.h
  test/lib/ufe/CMakeLists.txt
  test/lib/ufe/testLight.py
  test/testSamples/light/SimpleLight.usda
Labels: ufe-usd, ready-for-merge

#3918 EMSUSD-986 - Revert edit as maya changes
  lib/mayaUsd/fileio/jobs/readJob.cpp
  lib/mayaUsd/fileio/jobs/readJob.h
  lib/mayaUsd/fileio/primReaderContext.cpp
  lib/mayaUsd/fileio/primReaderContext.h
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/fileio/translators/translatorXformable.cpp
  plugin/pxr/maya/lib/usdMaya/readJobWithSceneAssembly.cpp
  plugin/pxr/maya/lib/usdMaya/readJobWithSceneAssembly.h
Labels: workflows, ready-for-merge

#3916 Update version to v0.31.0
  cmake/mayausd_version.info
Labels: build, ready-for-merge

#3910 EMSUSD-1610 layer manager flicker
  lib/usd/ui/layerEditor/layerTreeModel.cpp
  lib/usd/ui/layerEditor/layerTreeView.cpp
  lib/usd/ui/layerEditor/layerTreeView.h
Labels: bug, ready-for-merge

#3911 EMSUSD-1510 save-layer button's name
  lib/usd/ui/layerEditor/layerEditorWidget.cpp
Labels: adsk, ready-for-merge

#3915 EMSUSD-1619 fix removal on multiple layers
  lib/usd/ui/layerEditor/layerTreeView.cpp
  lib/usd/ui/layerEditor/layerTreeView.h
  lib/usd/ui/layerEditor/mayaLayerEditorWindow.cpp
Labels: workflows, ready-for-merge

#3861 Fix reparenting/renaming of pulled objects USD ancestor
  lib/mayaUsd/fileio/orphanedNodesManager.cpp
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/fileio/utils/CMakeLists.txt
  lib/mayaUsd/fileio/utils/proxyAccessorUtil.cpp
  lib/mayaUsd/fileio/utils/proxyAccessorUtil.h
  lib/mayaUsd/nodes/proxyAccessor.py
  test/lib/mayaUsd/fileio/CMakeLists.txt
  test/lib/mayaUsd/fileio/testEditAsMaya.py
  test/lib/testMayaUsdProxyAccessor.py
Labels: workflows, ready-for-merge

#3872 MSVC 2022 compiler fixes + minor correction for older Hydra APIs
  lib/mayaUsd/render/pxrUsdMayaGL/proxyDrawOverride.cpp
  lib/usd/hdMaya/adapters/dagAdapter.cpp
  plugin/pxr/maya/lib/usdMaya/translatorModelAssembly.cpp
Labels: build, ready-for-merge

#3912 Fix Progress Bar warnings
  lib/mayaUsd/utils/progressBarScope.cpp
Labels: bug, ready-for-merge

#3902 LOOKDEVX-3222 - Expose hardcoded texture paths
  lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.h
  lib/mayaUsdAPI/render.cpp
  lib/mayaUsdAPI/render.h
Labels: ready-for-merge, materials

#3917 Update tests for USD versions > 24.08
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/InstancerDrawTest/baseline/InstancerTest_cards.png
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/InstancerDrawTest/baseline/InstancerTest_cards_legacyUsd.png
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/InstancerDrawTest/baseline/InstancerTest_cards_v1_legacyUsd.png
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/InstancerDrawTest/baseline/InstancerTest_frame50.png
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/InstancerDrawTest/baseline/InstancerTest_frame50_legacyUsd.png
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/InstancerDrawTest/baseline/InstancerTest_frame50_v1_legacyUsd.png
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/InstancerDrawTest/baseline/InstancerTest_instance2.png
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/InstancerDrawTest/baseline/InstancerTest_instance2_legacyUsd.png
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/InstancerDrawTest/baseline/InstancerTest_instance2_v1_legacyUsd.png
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/RefAssemblyDrawRepresentationsTest/baseline/RefAssemblyDrawRepresentationsTest_Cards.png
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/RefAssemblyDrawRepresentationsTest/baseline/RefAssemblyDrawRepresentationsTest_Cards_legacyUsd.png
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/RefAssemblyDrawRepresentationsTest/baseline/RefAssemblyDrawRepresentationsTest_Cards_v1_legacyUsd.png
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testPxrUsdMayaGLInstancerDraw.py
  plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testRefAssemblyDrawRepresentations.py
  test/lib/mayaUsd/render/mayaToHydra/MtohBasicRenderTest/lambertDefaultMaterial/cube_selected.png
  test/lib/mayaUsd/render/mayaToHydra/MtohBasicRenderTest/lambertDefaultMaterial/cube_selected_legacyUsd.png
  test/lib/mayaUsd/render/mayaToHydra/MtohBasicRenderTest/lambertDefaultMaterial/cube_unselected.png
  test/lib/mayaUsd/render/mayaToHydra/MtohBasicRenderTest/lambertDefaultMaterial/cube_unselected_legacyUsd.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_1.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_12.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_123.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_1234.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_123456.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_123456_legacyUsd.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_1234_legacyUsd.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_1235.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_1235_legacyUsd.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_123_legacyUsd.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_12_legacyUsd.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_1_legacyUsd.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_3.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_35.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_35_legacyUsd.png
  test/lib/mayaUsd/render/mayaToHydra/MtohDagChangesTest/lambertDefaultMaterial/instances_3_legacyUsd.png
  test/lib/mayaUsd/render/mayaToHydra/MtohVisibilityTest/lambertDefaultMaterial/cube_unselected.png
  test/lib/mayaUsd/render/mayaToHydra/MtohVisibilityTest/lambertDefaultMaterial/cube_unselected_legacyUsd.png
  test/lib/mayaUsd/render/mayaToHydra/testMtohBasicRender.py
  test/lib/mayaUsd/render/mayaToHydra/testMtohDagChanges.py
  test/lib/mayaUsd/render/mayaToHydra/testMtohVisibility.py
Labels: unit test, ready-for-merge

#3913 Use legacy DefaultPrim logic if using legacy material scopes
  lib/mayaUsd/fileio/jobs/writeJob.cpp
Labels: workflows, ready-for-merge

#3922 Copy a test file for use in overwrite testing
  test/lib/ufe/testReferenceCommands.py
  test/testSamples/twoSpheres/sphere_ext.usda
  test/testSamples/twoSpheres/spheres_ref.usda
Labels: unit test, ready-for-merge

#3920 EMSUSD-986 fix export of instances with transform on geometry
  lib/mayaUsd/fileio/translators/translatorMesh.cpp
  lib/mayaUsd/fileio/translators/translatorUtil.cpp
  lib/mayaUsd/fileio/translators/translatorUtil.h
  lib/usd/translators/meshReader.cpp
  test/lib/usd/translators/UsdImportInstancesTest/GeomWithTrf.usda
  test/lib/usd/translators/UsdImportInstancesTest/UsdImportInstancesTest_GeomWithTrf.usda
  test/lib/usd/translators/testUsdImportInstances.py
Labels: import-export, ready-for-merge

#3926 USD 24.11 adds explicit schemaIdentifier fields
  lib/usd/schemas/plugInfo.json.in
  test/lib/mayaUsd/fileio/UsdCustomRigSchema/plugInfo.json
Labels: schema, ready-for-merge

#3934 EMSUSD-1654 Fixed Test a typo in testLight's testUsdVolumeLights
  test/lib/ufe/testLight.py
Labels: unit test, ready-for-merge

#3925 EMSUSD-946 axis in import UI and command
  README_DOC.md
  lib/mayaUsd/commands/Readme.md
  lib/mayaUsd/commands/baseImportCommand.cpp
  lib/mayaUsd/commands/baseImportCommand.h
  lib/mayaUsd/fileio/doc/How-to-add-new-option.md
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/jobs/readJob.cpp
  lib/mayaUsd/fileio/jobs/readJob.h
  lib/mayaUsd/python/wrapPrimReader.cpp
  plugin/adsk/scripts/mayaUSDRegisterStrings.mel
  plugin/adsk/scripts/mayaUsdTranslatorImport.mel
  test/lib/usd/translators/CMakeLists.txt
  test/lib/usd/translators/UsdImportUpAxisTests/UpAxisY.usda
  test/lib/usd/translators/testUsdImportUpAxis.py
  test/lib/usd/translators/testUsdImportXforms.py
Labels: import-export, ready-for-merge

#3936 EMSUSD-1555 Duplicating a Physical Sky to USD using Arnold options is missing data
  lib/mayaUsd/fileio/chaser/exportChaser.cpp
  lib/mayaUsd/fileio/chaser/exportChaser.h
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/jobs/writeJob.cpp
  lib/mayaUsd/fileio/jobs/writeJob.h
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/python/wrapExportChaser.cpp
  lib/mayaUsd/python/wrapPrimWriter.cpp
  test/lib/mayaUsd/fileio/testExportChaserJobContext.py
Labels: adsk, workflows, ready-for-merge
