Repository Autodesk/maya-usd, pull requests merged in 2024-06, with the labels that each got.

#3794 EMSUSD-1266 don't depend on MayaUSD if not using it
  lib/mayaUsd/nodes/layerManager.cpp
  test/lib/mayaUsd/nodes/testLayerManagerSerialization.py
Labels: bug, adsk, ready-for-merge

#3800 Update googletest & gulrak (filesystem)
  cmake/googletest.cmake
  cmake/googletest_download.txt.in
  cmake/gulrak.cmake
  lib/mayaUsd/fileio/jobs/readJob.cpp
  lib/usd/translators/shading/mtlxFileTextureReader.cpp
  lib/usd/translators/shading/mtlxFileTextureWriter.cpp
  lib/usd/translators/shading/mtlxImageReader.cpp
Labels: build, ready-for-merge

#3802 Fix tests that are modifying source folder.
  test/lib/mayaUsd/nodes/testProxyShapeBase.py
  test/lib/usd/translators/testUsdExportTexture.py
Labels: unit test, ready-for-merge

#3801 EMSUSD-1196 material scope as default prim
  lib/mayaUsd/commands/Readme.md
  lib/mayaUsd/fileio/functorPrimWriter.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/writeJob.cpp
  lib/mayaUsd/fileio/primWriterArgs.cpp
  lib/mayaUsd/fileio/primWriterArgs.h
  lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
  plugin/adsk/scripts/mayaUsd_exportHelpers.py
  test/lib/usd/translators/testUsdExportDefaultPrim.py
Labels: import-export, ready-for-merge

#3804 Update build.md
  doc/build.md
Labels: documentation, ready-for-merge

#3812 EMSUSD-1355 - Hides ramp attributes in AE Template.
  lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
Labels: adsk, ready-for-merge

#3805 EMSUSD-1343 disable material in sync with meshes when duplicating
  lib/mayaUsd/resources/scripts/mayaUsdDuplicateAsUsdDataOptions.py
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
Labels: adsk, ready-for-merge

#3814 Update version to v0.30.0
  cmake/mayausd_version.info
Labels: build, ready-for-merge

#3813 EMSUSD-1358 fix blessing failure
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateUsdCamera.py
Labels: unit test, ready-for-merge

#3815 EMSUSD-1351 - MayaUsd: Code cleanup - Filenames according to coding standard
  lib/mayaUsd/fileio/translators/CMakeLists.txt
  lib/mayaUsd/fileio/translators/translatorRfMLightDeprecated.cpp
  lib/mayaUsd/fileio/translators/translatorXformableDecompose.cpp
  lib/mayaUsd/render/px_vp20/CMakeLists.txt
  lib/mayaUsd/render/px_vp20/utilsLegacy.cpp
  lib/mayaUsd/render/px_vp20/utilsLegacy.h
  lib/mayaUsd/render/pxrUsdMayaGL/batchRenderer.cpp
  lib/mayaUsd/render/pxrUsdMayaGL/proxyShapeUI.cpp
  lib/mayaUsd/render/pxrUsdMayaGL/shapeAdapter.cpp
  lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
  lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
  lib/mayaUsd/render/vp2RenderDelegate/drawItem.cpp
  lib/mayaUsd/render/vp2RenderDelegate/drawItem.h
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mesh.h
  lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.cpp
  lib/mayaUsd/render/vp2RenderDelegate/points.cpp
  lib/mayaUsd/render/vp2RenderDelegate/primvarInfo.h
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
  lib/mayaUsd/render/vp2RenderDelegate/renderDelegate.cpp
  lib/mayaUsd/render/vp2RenderDelegate/renderDelegate.h
  lib/mayaUsd/render/vp2RenderDelegate/renderParam.cpp
  lib/mayaUsd/render/vp2RenderDelegate/renderParam.h
  lib/mayaUsd/render/vp2RenderDelegate/renderPass.h
  lib/mayaUsd/render/vp2RenderDelegate/resourceRegistry.h
  lib/mayaUsd/render/vp2RenderDelegate/taskCommit.h
  lib/usd/translators/CMakeLists.txt
  lib/usd/translators/lightRfMWriter.cpp
  lib/usd/translators/lightRfMWriterPxrMeshLight.cpp
  lib/usd/translators/meshWriterBlendShapes.cpp
Labels: build, ready-for-merge

#3820 EMSUSD-1359 Export of Maya skeleton as USD comes in as a stage in the wrong place.
  lib/usd/translators/jointWriter.cpp
  test/lib/usd/translators/testUsdExportSkeleton.py
Labels: import-export, ready-for-merge, usdSkel

#3818 EMSUSD-1351 - MayaUsd: Code cleanup
  lib/mayaUsd/commands/baseListJobContextsCommand.cpp
  lib/mayaUsd/fileio/shading/shadingModeExporterContext.cpp
  lib/mayaUsd/fileio/translators/translatorMayaReference.cpp
  lib/mayaUsd/fileio/utils/meshWriteUtils.cpp
  lib/mayaUsd/nodes/proxyAccessor.cpp
  lib/mayaUsd/nodes/proxyShapePlugin.cpp
  lib/mayaUsd/render/vp2RenderDelegate/renderDelegate.cpp
  lib/mayaUsd/ufe/ProxyShapeHierarchy.cpp
  lib/mayaUsd/ufe/UsdTransform3dFallbackMayaXformStack.cpp
  lib/mayaUsd/utils/loadRulesAttribute.cpp
  lib/mayaUsd/utils/targetLayer.cpp
  lib/mayaUsd/utils/util.cpp
  lib/mayaUsd/utils/util.h
  lib/mayaUsd/utils/variantFallbacks.cpp
  lib/usd/hdMaya/adapters/lightAdapter.cpp
  lib/usd/hdMaya/adapters/materialAdapter.cpp
  lib/usd/hdMaya/delegates/sceneDelegate.cpp
  lib/usd/pxrUsdPreviewSurface/usdPreviewSurfaceShadingNodeOverride.cpp
  lib/usd/translators/particleWriter.cpp
  lib/usdUfe/ufe/UsdHierarchy.cpp
  plugin/adsk/plugin/plugin.cpp
Labels: build, ready-for-merge

#3823 EMSUSD-1351 - MayaUsd: Code cleanup
  lib/mayaUsd/base/tokens.h
  lib/mayaUsd/fileio/chaser/importChaserRegistry.h
  lib/mayaUsd/nodes/proxyStageProvider.h
  lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.h
  lib/mayaUsd/undo/OpUndoItems.h
  lib/usd/ui/layerEditor/abstractCommandHook.h
  lib/usd/ui/layerEditor/layerTreeItem.h
Labels: build, ready-for-merge

#3819 Explicitly setting legacyMaterialScope arg in tests
  test/lib/usd/pxrUsdPreviewSurface/testPxrUsdPreviewSurfaceExport.py
  test/lib/usd/translators/testUsdExport8BitNormalMap.py
  test/lib/usd/translators/testUsdExportAssignedMaterials.py
  test/lib/usd/translators/testUsdExportCustomConverter.template.py
  test/lib/usd/translators/testUsdExportDefaultPrim.py
  test/lib/usd/translators/testUsdExportDisplacement.py
  test/lib/usd/translators/testUsdExportFannedOutFileNodesMaterial.py
  test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
  test/lib/usd/translators/testUsdExportImportUDIM.py
  test/lib/usd/translators/testUsdExportMaterialScope.py
  test/lib/usd/translators/testUsdExportMaterialsOnly.py
  test/lib/usd/translators/testUsdExportMultiMaterial.py
  test/lib/usd/translators/testUsdExportRfMShaders.py
  test/lib/usd/translators/testUsdExportRoots.py
  test/lib/usd/translators/testUsdExportShadingInstanced.py
  test/lib/usd/translators/testUsdExportShadingModePxrRis.py
  test/lib/usd/translators/testUsdExportTexture.py
  test/lib/usd/translators/testUsdExportUVSetMappings.py
  test/lib/usd/translators/testUsdExportUVTransforms.py
  test/lib/usd/translators/testUsdExportUsdPreviewSurface.py
  test/lib/usd/translators/testUsdExportUsdzPackage.py
Labels: unit test, ready-for-merge

#3827 EMSUSD-1351 - MayaUsd: Code cleanup - never use reserved identifiers
  lib/mayaUsd/render/px_vp20/glslProgram.h
Labels: build, ready-for-merge

#3833 LOOKDEVX-3065 - Fixing renamed parameters
  lib/mayaUsd/render/MaterialXGenOgsXml/OgsFragment.cpp
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  lib/mayaUsd/render/vp2RenderDelegate/material.h
  lib/mayaUsd/render/vp2RenderDelegate/renderDelegate.cpp
  lib/mayaUsd/render/vp2RenderDelegate/renderDelegate.h
  lib/mayaUsd/render/vp2RenderDelegate/shader.h
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/DemoQuads_render.png
  test/testSamples/MaterialX/DemoQuads.usda
Labels: vp2renderdelegate, ready-for-merge, materials

#3830 LOOKDEVX-2937 - Fix diffuse lighting with aiAreaLight
  lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/SurfaceNodeMaya.cpp
Labels: vp2renderdelegate, ready-for-merge, materials

#3834 LOOKDEVX-939 - API implementation of UFE SceneSegmentHandler getter method for the dcc root path
  cmake/modules/FindUFE.cmake
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/ProxyShapeSceneSegmentHandler.cpp
  lib/mayaUsd/ufe/ProxyShapeSceneSegmentHandler.h
  test/lib/ufe/CMakeLists.txt
  test/lib/ufe/testSceneSegment.py
Labels: ufe-usd, ready-for-merge
