Repository Autodesk/maya-usd, pull requests merged in 2024-08, with the labels that each got.

#3869 EMSUSD-1410 - MayaUsdAPI - enhance with missing functions required for LookdevX
  cmake/mayausdapi_version.info
  lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.h
  lib/mayaUsdAPI/CMakeLists.txt
  lib/mayaUsdAPI/README.md
  lib/mayaUsdAPI/clipboard.cpp
  lib/mayaUsdAPI/clipboard.h
  lib/mayaUsdAPI/contextOps.cpp
  lib/mayaUsdAPI/contextOps.h
  lib/mayaUsdAPI/global.cpp
  lib/mayaUsdAPI/global.h
  lib/mayaUsdAPI/mayaUsdAPI.h.src
  lib/mayaUsdAPI/render.cpp
  lib/mayaUsdAPI/render.h
  lib/mayaUsdAPI/ufeHandlers.cpp
  lib/mayaUsdAPI/ufeHandlers.h
  lib/mayaUsdAPI/undo.cpp
  lib/mayaUsdAPI/undo.h
  lib/mayaUsdAPI/utils.cpp
  lib/mayaUsdAPI/utils.h
  lib/usdUfe/ufe/Global.cpp
  lib/usdUfe/ufe/Global.h
  lib/usdUfe/ufe/StagesSubject.cpp
  lib/usdUfe/ufe/StagesSubject.h
Labels: adsk, core, ready-for-merge

#3875 EMSUSD-1294 Changed tsverify to manual nullptr check
  lib/mayaUsd/ufe/ProxyShapeCameraHandler.cpp
  lib/mayaUsd/ufe/Utils.cpp
Labels: core, ready-for-merge

#3879 Merge v0.29.0 to dev
  doc/CHANGELOG.md
Labels: build, ready-for-merge

#3880 EMSUSD-1410 - MayaUsdAPI - enhance with missing functions required for LookdevX
  lib/mayaUsdAPI/CMakeLists.txt
Labels: adsk, core, ready-for-merge

#3871 LOOKDEVX-3214 - Improve UI name generation
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/lookdevKit.mtlx
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/usd_utilities.mtlx
  lib/mayaUsd/ufe/UsdShaderNodeDef.cpp
  lib/usdUfe/base/tokens.h
  lib/usdUfe/ufe/StagesSubject.cpp
  lib/usdUfe/ufe/UsdAttributeHolder.cpp
  lib/usdUfe/ufe/UsdShaderAttributeDef.cpp
  lib/usdUfe/ufe/Utils.cpp
  lib/usdUfe/utils/Utils.cpp
  test/lib/testAttributeEditorTemplate.py
  test/lib/ufe/testAttribute.py
Labels: ufe-usd, ready-for-merge

#3874 EMSUSD-1467 fix multi-layer parenting
  lib/usdUfe/ufe/UsdUndoInsertChildCommand.cpp
  lib/usdUfe/ufe/trf/UsdTransform3dUndoableCommands.cpp
  lib/usdUfe/utils/editRouterContext.cpp
  test/lib/ufe/testEditRouting.py
  test/lib/ufe/testParentCmd.py
Labels: ufe-usd, ready-for-merge

#3876 EMSUSD-1432 duplicate materials without meshes
  lib/mayaUsd/commands/PullPushCommands.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/jobs/writeJob.h
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/fileio/primUpdaterManager.h
  lib/mayaUsd/fileio/shading/shadingModeExporter.cpp
  lib/mayaUsd/fileio/writeJobContext.h
  lib/mayaUsd/python/wrapPrimUpdaterManager.cpp
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
  test/lib/mayaUsd/fileio/testDuplicateAs.py
Labels: workflows, ready-for-merge

#3887 EMSUSD-1442 - Update Maya Blessing so that the latest Hydra is picked up and used
  test/lib/CMakeLists.txt
  test/lib/testMayaHydraPlugin.py
  test/lib/testMayaUsdPlugVersionCheck.py
  test/lib/usd/translators/testUsdExportImportRoundtripPreviewSurface.py
Labels: unit test, mayaHydra

#3886 EMSUSD-1464 USD Support for Maya Dual Quaternion skinned shapes
  lib/mayaUsd/fileio/translators/translatorSkel.cpp
  lib/mayaUsd/fileio/utils/jointWriteUtils.cpp
  test/lib/usd/translators/UsdImportSkeleton/skelCubeDq.usda
  test/lib/usd/translators/testUsdExportSkeleton.py
  test/lib/usd/translators/testUsdImportSkeleton.py
Labels: import-export, ready-for-merge, usdSkel

#3891 EMSUSD-1550 - Build with USD v24.08
  cmake/modules/FindMaya.cmake
  lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.cpp
  lib/mayaUsd/render/vp2RenderDelegate/meshViewportCompute.h
  lib/mayaUsd/render/vp2RenderDelegate/renderDelegate.cpp
  lib/mayaUsd/render/vp2RenderDelegate/taskCommit.h
Labels: build, ready-for-merge

#3894 EMSUSD-1554 Fix materials options retention
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
Labels: ready-for-merge, materials

#3889 Update AE interface for Pxr Reference Assembly nodes
  plugin/pxr/maya/lib/usdMaya/AEpxrUsdReferenceAssemblyTemplate.py
Labels: pxr, ready-for-merge

#3884 EMSUSD-1527 support selection in duplicate to USD
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/utils/copyLayerPrims.cpp
  lib/mayaUsd/utils/copyLayerPrims.h
  plugin/adsk/scripts/mayaUsdMenu.mel
  test/lib/mayaUsd/fileio/testDuplicateAs.py
Labels: workflows, ready-for-merge
