Repository Autodesk/maya-usd, pull requests merged in 2024-11, with the labels that each got.

#3985 Merge v0.30.0 to dev
  doc/CHANGELOG.md
Labels: documentation, ready-for-merge

#3984 EMSUSD-1722 fix node origin detection
  lib/mayaUsd/nodes/layerManager.cpp
  lib/mayaUsd/nodes/layerManager.h
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/nodes/proxyShapeBase.h
  lib/mayaUsd/utils/util.cpp
  lib/mayaUsd/utils/util.h
  lib/usd/ui/layerEditor/mayaSessionState.cpp
  test/lib/testMayaUsdCreateStageInMayaRef.py
Labels: bug, workflows, ready-for-merge

#3989 EMSUSD-1777 namespace in USD default prim export argument
  lib/mayaUsd/fileio/jobs/writeJob.cpp
  test/lib/usd/translators/testUsdExportDefaultPrim.py
Labels: bug, import-export, ready-for-merge

#3993 EMSUSD-1745 fix export roots when no default prim is specified
  lib/mayaUsd/fileio/jobs/writeJob.cpp
  lib/mayaUsd/utils/util.cpp
  lib/mayaUsd/utils/util.h
  test/lib/usd/translators/testUsdExportDefaultPrim.py
Labels: bug, import-export, ready-for-merge

#3990 MAYA-133932 - Implement OpenPBR import/export
  cmake/modules/FindMaya.cmake
  cmake/modules/FindUSD.cmake
  lib/mayaUsd/CMakeLists.txt
  lib/mayaUsd/fileio/shading/shadingModeRegistry.h
  lib/mayaUsd/fileio/shading/shadingModeUseRegistry.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/CMakeLists.txt
  lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaClosureSourceCodeNode.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaClosureSourceCodeNode.h
  lib/mayaUsd/render/MaterialXGenOgsXml/libraries/mx39_lighting_maya_all.glsl
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  lib/usd/translators/CMakeLists.txt
  lib/usd/translators/shading/CMakeLists.txt
  lib/usd/translators/shading/mtlxFileTextureReader.cpp
  lib/usd/translators/shading/mtlxImageReader.cpp
  lib/usd/translators/shading/mtlxOpenPBRSurfaceReader.cpp
  lib/usd/translators/shading/mtlxOpenPBRSurfaceWriter.cpp
  lib/usd/translators/shading/mtlxStandardSurfaceReader.cpp
  lib/usd/translators/shading/mtlxStandardSurfaceWriter.cpp
  lib/usd/translators/shading/mtlxTranslationTableReader.cpp
  lib/usd/translators/shading/mtlxTranslationTableReader.h
  lib/usd/translators/shading/mtlxTranslationTableWriter.cpp
  lib/usd/translators/shading/mtlxTranslationTableWriter.h
  lib/usd/translators/shading/shadingTokens.cpp
  lib/usd/translators/shading/shadingTokens.h
  lib/usd/translators/shading/usdOpenPBRSurfaceReader.cpp
  lib/usd/translators/shading/usdOpenPBRSurfaceWriter.cpp
  lib/usd/translators/shading/usdStandardSurfaceWriter.cpp
  plugin/adsk/scripts/mayaUSDRegisterStrings.py
  plugin/adsk/scripts/mayaUsdTranslatorImport.mel
  test/lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/OpenPBRShowcase_MTLX_Import_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/OpenPBRShowcase_UsdPS_Import_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateMaterialX.py
  test/testSamples/MaterialX/OpenPBRShowcase.ma
Labels: ready-for-merge

#4002 EMSUSD-1813 fix custom AE callbacks
  lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
  test/lib/testAttributeEditorTemplate.py
Labels: bug, ready-for-merge

#3987 EMSUSD-1570 add a class-prims filter to USD UFE
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/MayaUsdContextOps.cpp
  lib/mayaUsd/ufe/MayaUsdHierarchyHandler.cpp
  lib/mayaUsd/ufe/MayaUsdHierarchyHandler.h
  lib/mayaUsd/ufe/ProxyShapeHierarchy.cpp
  lib/usdUfe/ufe/UsdContextOps.cpp
  lib/usdUfe/ufe/UsdHierarchy.cpp
  lib/usdUfe/ufe/UsdHierarchyHandler.cpp
  lib/usdUfe/ufe/Utils.cpp
  lib/usdUfe/ufe/Utils.h
  test/lib/ufe/testChildFilter.py
  test/testSamples/classPrims/class-prims.usda
Labels: ufe, ready-for-merge

#4005 Adjust test following renaming of the default OpenPBR material
  test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegatePerInstanceInheritedData.py
Labels: ready-for-merge, materials

#3988 EMSUSD-1518 As an artist, I want the ability to determine whether a collection includes all objects by default or not
  lib/mayaUsd/resources/ae/CMakeLists.txt
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/__init__.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/widget.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/__init__.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/list.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/persistentStorage.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/resizable.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/theme.py
  lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
  lib/mayaUsd/resources/ae/usdschemabase/lightCustomControl.py
  test/lib/testAttributeEditorTemplate.py
Labels: workflows, ready-for-merge

#4006 Shader parameter sections should be expanded
  lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
Labels: workflows, ready-for-merge

#3979 Fix crash in Attribute Editor when renaming a prim with pulled descendants
  lib/mayaUsd/fileio/orphanedNodesManager.cpp
  lib/mayaUsd/fileio/utils/proxyAccessorUtil.cpp
  lib/mayaUsd/nodes/proxyAccessor.py
Labels: core, crash

#4004 EMSUSD-1571 Manipulate prim schemas
  lib/mayaUsd/commands/CMakeLists.txt
  lib/mayaUsd/commands/Readme.md
  lib/mayaUsd/commands/schemaCommand.cpp
  lib/mayaUsd/commands/schemaCommand.h
  lib/usdUfe/python/wrapUtils.cpp
  lib/usdUfe/utils/CMakeLists.txt
  lib/usdUfe/utils/schemas.cpp
  lib/usdUfe/utils/schemas.h
  plugin/adsk/plugin/plugin.cpp
  plugin/adsk/scripts/CMakeLists.txt
  plugin/adsk/scripts/mayaUSDRegisterStrings.py
  plugin/adsk/scripts/mayaUsdMenu.mel
  plugin/adsk/scripts/mayaUsdMenu.py
  test/lib/CMakeLists.txt
  test/lib/testMayaUsdSchemaCommand.py
  test/lib/ufe/CMakeLists.txt
  test/lib/ufe/testSchemas.py
Labels: ufe-usd, schema, ready-for-merge

#4008 EMSUSD-1771 remove schema from prims
  lib/mayaUsd/commands/Readme.md
  lib/mayaUsd/commands/schemaCommand.cpp
  lib/mayaUsd/commands/schemaCommand.h
  lib/usdUfe/python/wrapUtils.cpp
  lib/usdUfe/utils/schemas.cpp
  lib/usdUfe/utils/schemas.h
  plugin/adsk/scripts/mayaUSDRegisterStrings.py
  plugin/adsk/scripts/mayaUsdMenu.py
  test/lib/testMayaUsdSchemaCommand.py
  test/lib/ufe/testSchemas.py
Labels: ufe-usd, schema, ready-for-merge

#4010 EMSUSD-1490 make group names more unique
  lib/usdUfe/ufe/UsdUndoCreateGroupCommand.cpp
  lib/usdUfe/ufe/Utils.cpp
  lib/usdUfe/ufe/Utils.h
  test/lib/ufe/testGroupCmd.py
  test/lib/ufe/testUngroupCmd.py
Labels: ufe-usd, ready-for-merge

#4011 EMSUSD-1625 - Disable EditAsMaya for cylinder, disk and dome light
  lib/usd/translators/lightReader.cpp
Labels: workflows, ready-for-merge

#4009 Improve stage edit target updates with refreshSystemLock callbacks
  lib/mayaUsd/commands/layerEditorCommand.cpp
  test/lib/testMayaUsdLayerEditorCommands.py
Labels: workflows, ready-for-merge

#4019 EMSUSD-1500 - Fix IOR image test
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/OpenPBRShowcase_MTLX_Import_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/OpenPBRShowcase_UsdPS_Import_render.png
  test/testSamples/MaterialX/OpenPBRShowcase.ma
Labels: unit test, ready-for-merge

#4021 EMSUSD-1770 - Initial support for USD v24.11
  CMakeLists.txt
Labels: build

#4017 EMSUSD-1856 make the collection widget support all collections
  lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
  lib/mayaUsd/resources/ae/usdschemabase/lightCustomControl.py
  test/lib/testAttributeEditorTemplate.py
Labels: workflows, ready-for-merge

#4022 EMSUSD-1522 I want the ability to see and set the expansion rule of the collection
  lib/mayaUsd/resources/ae/CMakeLists.txt
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/expressionRulesMenu.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/expressionWidget.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/includeExcludeWidget.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/widget.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/list.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/menuButton.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/persistentStorage.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/resizable.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/theme.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/icons/dark/menu_100.png
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/icons/dark/menu_150.png
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/icons/dark/menu_200.png
Labels: workflows, ready-for-merge
