Repository Autodesk/maya-usd, pull requests merged in 2024-12, with the labels that each got.

#4024 EMSUSD-1770 - Initial support for USD v24.11
  lib/mayaUsd/CMakeLists.txt
  lib/mayaUsdAPI/CMakeLists.txt
  lib/usdUfe/CMakeLists.txt
Labels: build, ready-for-merge

#4025 Fix AE extra attribute section.
  lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
Labels: bug, ready-for-merge

#4023 EMSUSD-1856 Add filtering search to the collection widget
  lib/mayaUsd/resources/ae/CMakeLists.txt
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/includeExcludeWidget.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/filteredStringListModel.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/filteredStringListView.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/list.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/resizable.py
Labels: workflows, ready-for-merge

#4016 Lobe pruning shader optimization
  lib/mayaUsd/render/MaterialXGenOgsXml/CMakeLists.txt
  lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/LobePruner.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/LobePruner.h
  lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaDarkClosureNode.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaDarkClosureNode.h
  lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.h
  lib/mayaUsd/render/vp2RenderDelegate/material.cpp
  lib/mayaUsdAPI/render.cpp
  lib/mayaUsdAPI/render.h
  test/lib/mayaUsd/utils/test_ShaderGenUtils.cpp
Labels: vp2renderdelegate, ready-for-merge

#4026 EMSUSD-1785 Update maya-usd Readme.md
  README.md
  doc/images/header.jpg
  doc/images/header.png
  doc/images/maya-usd.png
Labels: documentation, ready-for-merge

#4032 Update README.md
  README.md
Labels: documentation, ready-for-merge

#4028 EMSUSD-1891 Don't dirty stage when loading
  lib/mayaUsd/ufe/UsdLight.cpp
  test/lib/ufe/testLight.py
  test/testSamples/light/SimpleLight.usda
Labels: bug, ufe, ready-for-merge

#4029 EMSUSD-968 shorter nice names
  lib/usdUfe/utils/Utils.cpp
Labels: ufe-usd, ready-for-merge

#4033 EMSUSD-1912 disable new light test on USD 24.11
  test/lib/ufe/testLight.py
Labels: unit test, ready-for-merge

#4031 MAYA-133671 - Add textured mode handling to topo grapher
  lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/ShaderGenUtil.h
  lib/mayaUsdAPI/render.cpp
  lib/mayaUsdAPI/render.h
  test/lib/mayaUsd/utils/test_ShaderGenUtils.cpp
Labels: workflows, ready-for-merge

#4027 LayerManager: Prevent unintended overwriting of unmodified USD layers at Maya save.
  lib/mayaUsd/nodes/layerManager.cpp
Labels: workflows, ready-for-merge

#4030 EMSUSD-1541 - Drag and drop one or more scene objects from the outliner into the include or exclude list
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/includeExcludeWidget.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/filteredStringListView.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/list.py
Labels: workflows, ready-for-merge

#3986 EMSUSD-1686 Camera Performance Fix Backport
  cmake/modules/FindUFE.cmake
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/Global.cpp
  lib/mayaUsd/ufe/ProxyShapeCameraHandler.cpp
  lib/mayaUsd/ufe/ProxyShapeCameraHandler.h
  lib/usdUfe/ufe/CMakeLists.txt
  lib/usdUfe/ufe/UsdCameraHandler.cpp
  lib/usdUfe/ufe/UsdCameraHandler.h
Labels: bug, ufe-usd, ready-for-merge

#4035 Removing deprecated renderman attributes from test .ma file
  test/lib/usd/translators/UsdExportRfMLightTest/RfMLightsTest.ma
Labels: unit test, ready-for-merge

#4034 Explicitly add required export arg
  test/lib/ufe/testContextOps.py
Labels: ufe-usd, ready-for-merge

#4042 EMSUSD-1692 - Ignore Clang Format for LookdevXUsd folder
  .clang-format-ignore
Labels: build, ready-for-merge

#4043 Fix fatal error exit
  lib/mayaUsd/utils/diagnosticDelegate.cpp
Labels: bug, core, ready-for-merge, crash

#4037 Fix UsdMayaPrimWriter and UsdMayaPrimReader Python Wrappings
  lib/mayaUsd/python/wrapPrimReader.cpp
  lib/mayaUsd/python/wrapPrimWriter.cpp
Labels: core, ready-for-merge

#4038 EMSUSD-1912 Re-enable light test for USD 24.11
  test/lib/ufe/testLight.py
Labels: unit test, ready-for-merge

#4044 EMSUSD_1917 lock layer should preserve the selection
  lib/mayaUsd/commands/layerEditorCommand.cpp
Labels: bug, workflows, ready-for-merge

#4041 EMSUSD-1919 expose export job args to Python
  lib/mayaUsd/python/wrapPrimWriter.cpp
  test/lib/mayaUsd/fileio/testPrimWriter.py
Labels: import-export, ready-for-merge

#4046 Light linking sync
  lib/mayaUsd/resources/ae/CMakeLists.txt
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/includeExcludeWidget.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/widget.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/filteredStringListView.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/host.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/list.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/icons/dark/delete_100.png
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/icons/dark/delete_150.png
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/icons/dark/delete_200.png
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/icons/light/menu_100.png
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/icons/light/menu_150.png
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/icons/light/menu_200.png
  lib/mayaUsd/resources/ae/usdschemabase/lightCustomControl.py
Labels: workflows, ready-for-merge

#4051 Update reference images for a fix in OpenPBR native
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/OpenPBRShowcase_MTLX_Import_render.png
  test/lib/mayaUsd/render/vp2RenderDelegate/VP2RenderDelegateMaterialXTest/baseline/OpenPBRShowcase_UsdPS_Import_render.png
Labels: unit test, ready-for-merge

#4048 EMSUSD-1949 better support for grouping prims with references
  cmake/modules/FindUSD.cmake
  lib/usdUfe/CMakeLists.txt
  lib/usdUfe/ufe/UsdUndoInsertChildCommand.cpp
  test/lib/ufe/testGroupCmd.py
Labels: bug, ufe-usd, ready-for-merge

#4054 EMSUSD-1971 Make job context UI registeration be order-neutral
  lib/mayaUsd/fileio/jobContextRegistry.cpp
  lib/mayaUsd/fileio/jobContextRegistry.h
  test/lib/usd/plugin/nullApiExporter.cpp
Labels: enhancement, workflows, build, ready-for-merge

#4053 EMSUSD-1519 refactor collection UI
  lib/mayaUsd/resources/ae/CMakeLists.txt
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/expressionRulesMenu.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/expressionWidget.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/includeExcludeWidget.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/collection/widget.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/filteredStringListModel.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/filteredStringListView.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/stringListPanel.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/theme.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/data/__init__.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/data/collectionData.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/data/stringListData.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/__init__.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/usdCollectionData.py
  lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/usdData/usdCollectionStringListData.py
Labels: ready-for-merge, shared_components
