Repository Autodesk/maya-usd, pull requests merged in 2024-02, with the labels that each got.

#3586 EMSUSD-996 allowing meshes with insufficient primvars data size.
  lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
Labels: vp2renderdelegate, ready-for-merge

#3581 LOOKDEVX-2254 - Enable "Implicit Namespace Packages" feature
  lib/mayaUsd/resources/ae/CMakeLists.txt
Labels: build, ready-for-merge

#3592 EMSUSD-957 - Call CanExport() per object instead of per export
  lib/mayaUsd/fileio/primWriterRegistry.cpp
  lib/mayaUsd/fileio/primWriterRegistry.h
  lib/mayaUsd/fileio/writeJobContext.cpp
Labels: import-export, ready-for-merge

#3593 EMSUSD-987 undo edit prototype
  lib/mayaUsd/fileio/jobs/readJob.cpp
Labels: bug, workflows, ready-for-merge

#3590 EMSUSD-988 Maya node observer classes
  lib/mayaUsd/utils/CMakeLists.txt
  lib/mayaUsd/utils/mayaNodeObserver.cpp
  lib/mayaUsd/utils/mayaNodeObserver.h
  lib/mayaUsd/utils/mayaNodeTypeObserver.cpp
  lib/mayaUsd/utils/mayaNodeTypeObserver.h
Labels: enhancement, adsk, ready-for-merge

#3594 EMSUSD-1001 lost muted layer
  lib/mayaUsd/nodes/layerManager.cpp
  test/lib/mayaUsd/fileio/CMakeLists.txt
  test/lib/mayaUsd/fileio/testSaveMutedAnonLayer.py
Labels: bug, adsk, ready-for-merge

#3601 EMSUSD-1012 - Fix the issue caused duplicate as USD failed
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
Labels: adsk, import-export, ready-for-merge

#3602 Maya is no longer using a Preview Release number
  cmake/modules/FindMaya.cmake
  test/testUtils/mayaUtils.py
Labels: unit test, ready-for-merge

#3600 EMSUSD-1007 fix layers not muted on reload
  lib/mayaUsd/nodes/layerManager.cpp
  lib/mayaUsd/nodes/layerManager.h
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/utils/layerMuting.cpp
  lib/mayaUsd/utils/layerMuting.h
  test/lib/mayaUsd/fileio/testSaveMutedAnonLayer.py
Labels: bug, adsk, ready-for-merge

#3595 EMSUSD-870 - Added Locking mechanism to layers
  lib/mayaUsd/commands/abstractLayerEditorWindow.h
  lib/mayaUsd/commands/layerEditorCommand.cpp
  lib/mayaUsd/commands/layerEditorWindowCommand.cpp
  lib/usd/ui/layerEditor/abstractCommandHook.h
  lib/usd/ui/layerEditor/layerTreeItem.cpp
  lib/usd/ui/layerEditor/layerTreeItem.h
  lib/usd/ui/layerEditor/layerTreeItemDelegate.cpp
  lib/usd/ui/layerEditor/layerTreeItemDelegate.h
  lib/usd/ui/layerEditor/layerTreeModel.cpp
  lib/usd/ui/layerEditor/layerTreeModel.h
  lib/usd/ui/layerEditor/layerTreeView.cpp
  lib/usd/ui/layerEditor/layerTreeView.h
  lib/usd/ui/layerEditor/mayaCommandHook.cpp
  lib/usd/ui/layerEditor/mayaCommandHook.h
  lib/usd/ui/layerEditor/mayaLayerEditorWindow.cpp
  lib/usd/ui/layerEditor/mayaLayerEditorWindow.h
  lib/usd/ui/layerEditor/stringResources.h
  lib/usdUfe/ufe/Utils.cpp
  plugin/adsk/scripts/mayaUSDRegisterStrings.mel
  plugin/adsk/scripts/mayaUsdMenu.mel
  test/lib/testMayaUsdLayerEditorCommands.py
Labels: workflows, ready-for-merge

#3606 EMSUSD-1016 - Link against mayaUsdAPI to preload it for other plugins
  plugin/adsk/plugin/CMakeLists.txt
Labels: build, ready-for-merge

#3604 EMSUSD-499 - Fix the bug that variant not saving to maya file
  lib/mayaUsd/nodes/proxyShapeBase.cpp
Labels: core, ready-for-merge

#3612 Merge v0.27.0 to dev
  doc/CHANGELOG.md
Labels: build

#3609 EMSUSD-1003 Keep Maya Ref valid after saving
  lib/mayaUsd/fileio/primUpdaterManager.cpp
  lib/mayaUsd/nodes/layerManager.cpp
  lib/mayaUsd/nodes/layerManager.h
Labels: bug, adsk, ready-for-merge

#3607 EMSUSD-708 fix performance of instanceable prims
  lib/mayaUsd/render/vp2RenderDelegate/basisCurves.cpp
  lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp
  lib/mayaUsd/render/vp2RenderDelegate/points.cpp
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
  lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.h
Labels: enhancement, adsk, ready-for-merge

#3619 EMSUSD-872 - Adds the ability to System-lock a layer
  lib/mayaUsd/commands/Readme.md
  lib/mayaUsd/commands/abstractLayerEditorWindow.h
  lib/mayaUsd/commands/layerEditorCommand.cpp
  lib/mayaUsd/commands/layerEditorWindowCommand.cpp
  lib/mayaUsd/utils/CMakeLists.txt
  lib/mayaUsd/utils/layerLocking.cpp
  lib/mayaUsd/utils/layerLocking.h
  lib/usd/ui/layerEditor/abstractCommandHook.h
  lib/usd/ui/layerEditor/layerEditorWidget.cpp
  lib/usd/ui/layerEditor/layerTreeItem.cpp
  lib/usd/ui/layerEditor/layerTreeItem.h
  lib/usd/ui/layerEditor/layerTreeItemDelegate.cpp
  lib/usd/ui/layerEditor/layerTreeModel.cpp
  lib/usd/ui/layerEditor/layerTreeView.cpp
  lib/usd/ui/layerEditor/mayaCommandHook.cpp
  lib/usd/ui/layerEditor/mayaCommandHook.h
  lib/usd/ui/layerEditor/mayaLayerEditorWindow.cpp
  lib/usd/ui/layerEditor/mayaLayerEditorWindow.h
  lib/usd/ui/layerEditor/saveLayersDialog.cpp
  lib/usd/ui/layerEditor/stringResources.h
  plugin/adsk/scripts/mayaUsdMenu.mel
  test/lib/testMayaUsdLayerEditorCommands.py
Labels: workflows, ready-for-merge

#3599 EMSUSD-988 Avoid rebuilding the stage map when a path is not found
  lib/mayaUsd/base/debugCodes.cpp
  lib/mayaUsd/base/debugCodes.h
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/nodes/proxyShapeBase.h
  lib/mayaUsd/ufe/Global.cpp
  lib/mayaUsd/ufe/MayaStagesSubject.cpp
  lib/mayaUsd/ufe/ProxyShapeSceneSegmentHandler.cpp
  lib/mayaUsd/ufe/UsdStageMap.cpp
  lib/mayaUsd/ufe/UsdStageMap.h
  lib/mayaUsd/ufe/UsdUndoCreateStageWithNewLayerCommand.cpp
  lib/mayaUsd/ufe/Utils.cpp
  lib/mayaUsd/ufe/Utils.h
  lib/usd/ui/layerEditor/mayaSessionState.cpp
  lib/usd/ui/layerEditor/mayaSessionState.h
Labels: adsk, core, ready-for-merge

#3608 EMSUSD-1066 - Minimal API needed by LookdevX to decouple from mayaUsd
  lib/mayaUsdAPI/CMakeLists.txt
  lib/mayaUsdAPI/utils.cpp
  lib/mayaUsdAPI/utils.h
Labels: build, ready-for-merge

#3624 LOOKDEVX-2547 - Hide component connection nodes from AE
  lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
  test/lib/testAttributeEditorTemplate.py
  test/testSamples/MaterialX/multiple_connections.usda
Labels: ready-for-merge

#3625 EMSUSD-1017 Fix reverting multiple files
  lib/usd/ui/layerEditor/abstractCommandHook.h
  lib/usd/ui/layerEditor/layerTreeView.cpp
  lib/usd/ui/layerEditor/mayaCommandHook.cpp
  lib/usd/ui/layerEditor/mayaCommandHook.h
Labels: bug, adsk, ready-for-merge, crash

#3628 Use the Using Directive macro
  lib/mayaUsd/utils/copyLayerPrims.cpp
Labels: build, ready-for-merge

#3633 Update codingGuidelines.md
  doc/codingGuidelines.md
Labels: documentation, ready-for-merge

#3630 EMSUSD-801 - Add the feature to set the root prim type on export
  lib/mayaUsd/commands/Readme.md
  lib/mayaUsd/commands/baseExportCommand.cpp
  lib/mayaUsd/commands/baseExportCommand.h
  lib/mayaUsd/fileio/jobs/jobArgs.cpp
  lib/mayaUsd/fileio/jobs/jobArgs.h
  lib/mayaUsd/fileio/jobs/writeJob.cpp
  lib/mayaUsd/fileio/writeJobContext.cpp
  lib/mayaUsd/fileio/writeJobContext.h
  lib/mayaUsd/python/wrapPrimWriter.cpp
  lib/mayaUsd/resources/scripts/mayaUsdCacheMayaReference.py
  plugin/adsk/scripts/mayaUSDRegisterStrings.mel
  plugin/adsk/scripts/mayaUsdTranslatorExport.mel
  test/lib/usd/translators/CMakeLists.txt
  test/lib/usd/translators/UsdExportRootPrimTest/UsdExportRootPrimTest.ma
  test/lib/usd/translators/testUsdExportDefaultPrim.py
  test/lib/usd/translators/testUsdExportRenderLayerMode.py
  test/lib/usd/translators/testUsdExportRootPrim.py
  test/lib/usd/translators/testUsdExportRootsAndRootPrim.py
Labels: adsk, import-export, ready-for-merge

#3638 EMSUSD-871 - Locked layer status persists between Maya sessions
  lib/mayaUsd/commands/layerEditorCommand.cpp
  lib/mayaUsd/nodes/proxyShapeBase.cpp
  lib/mayaUsd/nodes/proxyShapeBase.h
  lib/mayaUsd/utils/layerLocking.cpp
  lib/mayaUsd/utils/layerLocking.h
  test/lib/testMayaUsdLayerEditorCommands.py
  test/testSamples/layerLocking/layerLocking.usda
Labels: workflows, ready-for-merge

#3603 Update github actions to node20 (node16 is out of support)
  .github/workflows/maya-usd-new-issues.yml
  .github/workflows/maya-usd-preflight-launcher.yml
Labels: build
