Repository Autodesk/maya-usd, pull requests merged in 2025-08, with the labels that each got.

#4298 Initialize PxrGL HdCamera attr value cache
  lib/mayaUsd/render/pxrUsdMayaGL/sceneDelegate.cpp
Labels: vp2renderdelegate, ready-for-merge

#4301 EMSUSD-2614 - Fix a bug when loading Maya project token to AR
  plugin/adsk/plugin/plugin.cpp
  plugin/adsk/scripts/mayaUsd_AdskAssetResolver.py
Labels: adsk, ready-for-merge

#4302 Define static class member in impl file
  lib/mayaUsd/utils/progressBarScope.cpp
Labels: build, ready-for-merge

#4291 EMSUSD-2655: Show Layer Data Window
  lib/usd/ui/layerEditor/CMakeLists.txt
  lib/usd/ui/layerEditor/layerContentsWidget.cpp
  lib/usd/ui/layerEditor/layerContentsWidget.h
  lib/usd/ui/layerEditor/layerEditorWidget.cpp
  lib/usd/ui/layerEditor/layerEditorWidget.h
  lib/usd/ui/layerEditor/layerTreeModel.cpp
  lib/usd/ui/layerEditor/layerTreeModel.h
  lib/usd/ui/layerEditor/layerTreeView.cpp
  lib/usd/ui/layerEditor/layerTreeView.h
  lib/usd/ui/layerEditor/mayaSessionState.cpp
  lib/usd/ui/layerEditor/mayaSessionState.h
  lib/usd/ui/layerEditor/sessionState.cpp
  lib/usd/ui/layerEditor/sessionState.h
  lib/usd/ui/layerEditor/stringResources.h
  lib/usd/ui/layerEditor/usdSyntaxConfig.json
  lib/usd/ui/layerEditor/usdSyntaxHighlighter.cpp
  lib/usd/ui/layerEditor/usdSyntaxHighlighter.h
Labels: enhancement, ready-for-merge

#4308 EMSUSD-2783 - Adds an envionment variable to disable layer auto targeting
  lib/mayaUsd/commands/layerEditorCommand.cpp
Labels: workflows, ready-for-merge
