Repository Autodesk/maya-usd, pull requests merged in 2025-07, with the labels that each got.

#4258 Fix define typo
  cmake/modules/FindUSD.cmake
  lib/mayaUsd/CMakeLists.txt
  lib/mayaUsd/fileio/transformWriter.cpp
  lib/mayaUsd/fileio/translators/translatorXformable.cpp
  lib/mayaUsd/fileio/utils/xformStack.cpp
  lib/mayaUsd/fileio/utils/xformStack.h
Labels: build, ready-for-merge

#4256 API doc is no longer included schema's "doc" field
  test/lib/ufe/testAttribute.py
Labels: unit test, ready-for-merge

#4268 Updates for MaterialX 1.39.4
  lib/mayaUsd/render/MaterialXGenOgsXml/GlslOcioNodeImpl.h
  lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaTransformVectorNodeGlsl.h
  lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/TexcoordNodeMaya.h
Labels: build, ready-for-merge

#4271 EMSUSD-2663 - MayaUsd: Maya blessing broken after Qt 6.8.3 update
  lib/usd/ui/CMakeLists.txt
  tutorials/import-export-plugin-c++/CMakeLists.txt
Labels: build, ready-for-merge

#4266 EMSUSD-2648/2648 - UsdUfe: move delete and rename commands from MayaUsd
  lib/mayaUsd/ufe/CMakeLists.txt
  lib/mayaUsd/ufe/MayaUsdUndoRenameCommand.cpp
  lib/mayaUsd/ufe/MayaUsdUndoRenameCommand.h
  lib/mayaUsd/ufe/UsdSceneItemOps.cpp
  lib/mayaUsd/ufe/UsdUndoCreateStageWithNewLayerCommand.cpp
  lib/mayaUsd/ufe/UsdUndoDuplicateCommand.cpp
  lib/mayaUsd/ufe/UsdUndoMaterialCommands.cpp
  lib/mayaUsd/ufe/Utils.cpp
  lib/mayaUsd/ufe/Utils.h
  lib/usdUfe/ufe/CMakeLists.txt
  lib/usdUfe/ufe/UsdUndoDeleteCommand.cpp
  lib/usdUfe/ufe/UsdUndoDeleteCommand.h
  lib/usdUfe/ufe/UsdUndoInsertChildCommand.cpp
  lib/usdUfe/ufe/UsdUndoRenameCommand.cpp
  lib/usdUfe/ufe/UsdUndoRenameCommand.h
  lib/usdUfe/ufe/Utils.cpp
  lib/usdUfe/ufe/Utils.h
Labels: ufe-usd, ready-for-merge

#4274 Bracket code backported from MaterialX 1.39.X
  lib/mayaUsd/render/MaterialXGenOgsXml/CMakeLists.txt
  lib/mayaUsd/render/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaShaderGraph.cpp
  lib/mayaUsd/render/MaterialXGenOgsXml/Nodes/MayaShaderGraph.h
  test/lib/mayaUsd/utils/test_ShaderGenUtils.cpp
  test/lib/usd/translators/testUsdExportMaterialX.py
Labels: ready-for-merge, materials

#4275 EMSUSD-2637 - Performance is slow with variants on certain Kitbash scene assets
  lib/usdUfe/ufe/StagesSubject.cpp
  lib/usdUfe/ufe/Utils.cpp
  lib/usdUfe/ufe/Utils.h
Labels: ufe-usd, ready-for-merge
